### PR TITLE
Using Fork to fix white Screen with Kernel 5.4.

### PR DESCRIPTION
**Pull request by phenomeus**

### CODE REVIEW

**Review by ChuckNorrison — COMMENTED** [review]
This is the commit you need and does not exists in the more updated goodtft repository. Maybe this should be a topic in the goodtft repo as pull request? Wait for the mods to check this out... this should be checked: waveshare35a over tft35a

https://github.com/MrYacha/LCD-show/commit/b012c487669afd3e997fc63fcc097d45a5a6a34e

// another lcd driver could be ads7846. Do we want to support all?

List of supported displays by LCD-Show:
http://www.lcdwiki.com/RaspberryPi-LCD-Driver

This driver download is referenced to (tft35a):
https://github.com/goodtft/LCD-show.git

**Comment by ChuckNorrison** [comment]
i got some issues with my LCD too, only white screen after i installed it again. It was working fine till the point i removed it. Already tried the LCD settings to reinstall and reconfigure, but seems not to help yet. Iam analyzing the shell scripts which dont give me a good error description "error=not installed".. what?^^

**Comment by ChuckNorrison** [comment]
Should we remove that git reset?
```
     # set comit hard to old version - that seemed to run better
     #
     sudo -u admin git reset --hard ce52014
```

Should we take care for that tft35a at this place?
```
   # make dietpi preparations
   if [ "${baseImage}" = "dietpi" ]; then
     echo "--> dietpi preparations"
     sudo rm -rf /etc/X11/xorg.conf.d/40-libinput.conf
     sudo mkdir /etc/X11/xorg.conf.d
     sudo cp ./usr/tft35a-overlay.dtb /boot/overlays/
     sudo cp ./usr/tft35a-overlay.dtb /boot/overlays/tft35a.dtbo
     sudo cp -rf ./usr/99-calibration.conf-35  /etc/X11/xorg.conf.d/99-calibration.conf
     sudo cp -rf ./usr/99-fbturbo.conf  /usr/share/X11/xorg.conf.d/
     sudo cp ./usr/cmdline.txt /DietPi/
     sudo cp ./usr/inittab /etc/
     sudo cp ./boot/config-35.txt /DietPi/config.txt
     # make LCD screen rotation correct
     sudo sed -i "s/dtoverlay=tft35a/dtoverlay=tft35a:rotate=270/" /DietPi/config.txt
   fi
```

**Comment by frennkie** [comment]
Duplicate of #1490

**Pull request closed without merging**
