### PR TITLE
configure ufw

### LINKED ISSUE #45: configuring firewall
I was looking to see if raspiblitz has a firewall activated but realized you just install it but don't configure it.

https://github.com/rootzoll/raspiblitz/blob/ee67947a631926779783d4cc22127108b4d8e284/build.sdcard/raspbianStretchDesktop.sh#L92

for basic usage (bitcoin + lightning) the following patch should fix this:

```
ufw allow ssh
ufw allow 8333
ufw allow 9735
ufw default deny incoming
ufw default allow outgoing
ufw enable
```

### PR DESCRIPTION
**Pull request by vnnkl**
added configuration as suggested by #45 
+ testnet

closes #45

### CODE REVIEW

**Comment by rootzoll** [comment]
thx. 
There is also litecoin mainnet: 9333
And maybe Port 80 for the Web-Admin to come in the future?

**Comment by vnnkl** [comment]
was not sure if we wanted to open ports which might not be used later rather than opening them on demand, your call, then shango 10009 as well

**Comment by rootzoll** [comment]
Also not sure if the torrent-download might have problems with a too tight firewall (some seeding while downloaded would be nice). FTP should be fine with downloading from behind that.

**Comment by charlesrocket** [comment]
@rootzoll @vnnkl `transmission` will require open firewall or port forwarding, so it might be easier to put `ufw` option after the torrent stage is complete?

**Pull request merged**
