### PR TITLE
detect os and print corresponding QR command

### PR DESCRIPTION
**Pull request by thehapax**
if merged this pull would close issue #193 for Linux and OSX

### CODE REVIEW

**Comment by raumi75** [comment]
Great idea, but it does not work for me, yet. When I ssh into my RaspiBlitz from macOS, I have to use the macOS keys, but uname returns "Linux". How can we detect the client OS?

**Comment by thehapax** [comment]
@raumi75 This pull request was for one script only. It hasn't been accepted yet. If you want to try it you can test it out on my repository. see issue #193 for code examples on how to detect the client OS

**Comment by raumi75** [comment]
I've tried it and it does not work. 

`uname` returns `Linux` on my Raspiblitz even if I connect from my Mac. That's the expected behavior. If I copy the script to my Mac, it would return Darwin, but that's not a solution to our problem.

Unfortunately I could not find a way to detect the OS of the client within the script. Maybe the `sshd` can log the ssh-client string or something. But after fiddling with it for an hour, I've given up for now.

**Comment by thehapax** [comment]
> Unfortunately I could not find a way to detect the OS of the client within the script. 

I don't believe what you are seeking is possible as it is beyond  the environment any script running in. Good luck if you can find something. 

However, you are incorrect in saying `it does not work.`.  It is doing what it can do within its scope. Its just not doing what you want specifically.

**Comment by raumi75** [comment]
Hi @thehapax, your commit is trying to display the correct key combination for decreasing or increasing the font size of the QR-code via ssh on a Mac/Linux/Windows client, right?

**Comment by rootzoll** [comment]
I merged into dev and will test again as part of the #193 - if its not working the issue will stay open.

**Pull request merged**
