### PR TITLE
JoinMarket update to v0.7.0

### PR DESCRIPTION
**Pull request by openoms**
joinmarket: update to v0.7.0
joinmarket: update joininbox menu to v0.1.3.1

Running ok on a v1.6 node + opened the QT GUI on Debian desktop

Related:
https://github.com/rootzoll/raspiblitz/issues/1488

### CODE REVIEW

**Comment by openoms** [comment]
Can be tested on a RaspiBlitz v1.6 with these commands:
```
wget https://raw.githubusercontent.com/openoms/raspiblitz/jm-0.7.0/home.admin/config.scripts/bonus.joinmarket.sh
chmod +x bonus.joinmarket.sh
sudo ./bonus.joinmarket.sh off
sudo ./bonus.joinmarket.sh on
```

Once installed start with:
`sudo su joinmarket`
or use the shortcut:
`jmarket`

**Comment by shawnyeager** [comment]
Thanks, @openoms. A note for those who made not be as CLI-savvy that calling the script with the `./` prefix was necessary, at least on my box.

```
wget https://raw.githubusercontent.com/openoms/raspiblitz/jm-0.7.0/home.admin/config.scripts/bonus.joinmarket.sh
chmod +x bonus.joinmarket.sh
sudo ./bonus.joinmarket.sh off
sudo ./bonus.joinmarket.sh on
```

**Comment by openoms** [comment]
thanks @shawnyeager edited to avoid confusion.

**Comment by dennisreimann** [comment]
Can confirm it works for me as well! Thanks :)

**Pull request merged**
