### PR TITLE
typos in lnd.install.sh

### PR DESCRIPTION
**Pull request by adevoss**

### CODE REVIEW

**Comment by openoms** [comment]
Is there a functional difference with these changes or are these more of a style suggestion?

**Comment by adevoss** [comment]
There is no functional difference but without these changes the script returns errors and exits.

**Comment by openoms** [comment]
The double `==` are not needed in bash scripts
the added spaces outside the brackets are not needed
comparing to single words with or without " " are also the same.
Are you sure the errors you are getting are fixed by these changes?

**Comment by adevoss** [comment]
No, not sure. At the same time I created this pr there was this (#2847) which you solved at the same time yourself.
I don't know if that caused the errors or the if statement syntax.
Now I will try an install of `dev` branch.
If that gives no errors then I will close this.

**Comment by adevoss** [comment]
Setup has no errors. But there is
```
/usr/local/bin/lnd --configfile=/home/bitcoin/.lnd/lnd.conf
-bash: /usr/local/bin/lnd: No such file or directory
```
(#2813)

**Pull request closed without merging**
