### PR TITLE
ip2tor: add https:// to link to make clickable

### PR DESCRIPTION
**Pull request by openoms**
as discussed: https://github.com/rootzoll/raspiblitz/issues/1194#issuecomment-650048682

### CODE REVIEW

**Comment by rootzoll** [comment]
I think https:// can make sense ... but only when the type of the Bridge is "CUSTOM". The same dialog is shown when the user creates a IP2TOR for the gRPC API ... where the https does make no sense and may even be confusing.

**Comment by openoms** [comment]
in that case would need to show the message with whiptail instead of dialog because currently the link cannot be highlighted and copied either.

**Comment by rootzoll** [comment]
whiptail is fine with me :)

**Comment by openoms** [comment]
Looking into it whiptail is not available in the pythondialog.
image

I did not find any reference on clickable links or text (http://pythondialog.sourceforge.net/doc/), but it does happen with the `http://` or `https://` prefixes.
I think it would be great help to the user (even myself) if all the `IP_ADRESS:PORT` entries and `.onion` addresses would be possible to be opened from the dialog messageboxes.

**Comment by frennkie** [comment]
Isn't rendering (e.g. underlining) and being able to click on a link something that is also affected by the terminal application being used...? So LXTerminal or the default Gnome terminal from which you would ssh into the RaspiBlitz... ?

**Comment by rootzoll** [comment]
I think we have for now live with it that the python scripts can just call dialog and not whiptail and so in standard terminal apps there are no klickable links or text that can be easy cut&pasted. Its a bit of a pain ... but that all will be good once we have the webUI.

@openoms I would propose to close this PR without merge.

**Comment by openoms** [comment]
@rootzoll if you think showing the prefix would be more confusing than not being able to click and copy the numbers than close this of course. It is not too long to type, only inconvenient.

@frennkie I've only tried in the Gnome terminal, but the behaviour of the bash dialog is similar and consistent in other OS-es / terminal apps as well.

**Comment by frennkie** [comment]
Do we agree that this is not targeted for v1.6?

**Comment by rootzoll** [comment]
I will close this .. if someone finds an easy way to make links clickable in dialog or use whiptail from python then we can reiterate on this.

**Pull request closed without merging**
