### PR TITLE
increase timeoutsec to avoid re-entering the password

### PR DESCRIPTION
**Pull request by Tracachang**
Related to the issue #2622 

Adding more time will avoid service to restart and having to re-enter password

### CODE REVIEW

**Comment by rootzoll** [comment]
its a duplicate to #2795 - or am I missing something?

**Comment by Tracachang** [comment]
I did 2, one for clightning and the other for lnd

**Comment by rootzoll** [comment]
Ah OK - got it :)

**Comment by rootzoll** [comment]
Will merge into temp branch to then cherry-pick into `dev` branch for v1.7.2 release candidates.

**Pull request merged**
