### PR TITLE
Tested app updates

### PR DESCRIPTION
**Pull request by openoms**
79e9b717 bos: update to v0.8.0
0fc3f828 btcpay: update to v2.1.49, nbxplorer to v1.0.6.8

### CODE REVIEW

**Comment by openoms** [comment]
fea26085 btcpay: update to v0.7.0 and cleanup script
ba9c7e56 joininbox update to v0.3.2
a1ebfbce joinmarket update to v0.8.2
13f2c64b specter update to v1.2.2
1c9312ac thunderhub update to v0.12.7
79e9b717 bos: update to v0.8.0
0fc3f828 nbxplorer update to v2.1.49

**Comment by rootzoll** [comment]
Testing this right now. @openoms BOS & Thunderhub already have newer version .. worth updating?

**Comment by openoms** [comment]
Yes, BOS and Thub are iterating quickly, makes sense to use the latest version.

Correction: BTCPayServer version is v1.0.7.0

**Comment by rootzoll** [comment]
@openoms BTCPayserver is not starting up correctly .. saying:
`Mar 16 23:14:36 raspberrypi dotnet[12088]: Unhandled exception. System.InvalidOperationException: No database option was configured.`

**Comment by openoms** [comment]
It is the same issue on fresh installs: https://github.com/rootzoll/raspiblitz/issues/1965

I have it in mind that the config ahould be modified afyer BTCPay is first started. Fix and testing incoming.

**Pull request merged**
