### PR TITLE
LNbits update to v0.12.4

### PR DESCRIPTION
**Pull request by openoms**
was able to update from v0.11.3 to the latest dev without issues using:

```
config.scripts/bonus.lnbits.sh repo lnbits dev
```

Apart from the update, here only making formatting changes.

The superuser account behaviour did not change.

### CODE REVIEW

**Comment by rootzoll** [comment]
On my test LNbits runs after install on http ... but not on https .. looking at the nginx logs:
```
--> CHECK CONFIG: sudo nginx -t
2024/03/21 19:56:44 [emerg] 2085561#2085561: open() "/etc/nginx/snippets/wss-proxy-params.conf" failed (2: No such file or directory) in /etc/nginx/sites-enabled/lnbits_ssl.conf:23
nginx: configuration file /etc/nginx/nginx.conf test failed
```

or 

```
Mar 21 19:39:17 raspberrypi systemd[1]: Reloading nginx.service - A high performance web server and a reverse proxy server...
Mar 21 19:39:17 raspberrypi nginx[1914159]: 2024/03/21 19:39:17 [emerg] 1914159#1914159: open() "/etc/nginx/snippets/wss-proxy-params.conf" failed (2: No such file or directory) in /etc/nginx/sites-enabled/lnbits_ssl.conf:23
Mar 21 19:39:17 raspberrypi systemd[1]: nginx.service: Control process exited, code=exited, status=1/FAILURE
Mar 21 19:39:17 raspberrypi systemd[1]: Reload failed for nginx.service - A high performance web server and a reverse proxy server.
```

**Comment by rootzoll** [comment]
Would recommend for v1.11.1 milestone

**Comment by openoms** [comment]
does `patch` sync the nginx snippets?

**Comment by rootzoll** [comment]
patch syncs the repo - if the nginx snippest got updated in the repo they will after `patch` also in the local repo BUT not be installed. For that you would need to uninstall&install the app.

**Comment by openoms** [comment]
not using the snippet any more (incorporated in the conf) and updated to v0.12.4

**Comment by rootzoll** [comment]
Just a research note - have to look deeper - after installing LNbits on my amd64VM it says on startup:

```
Mai 17 15:50:39 debian systemd[1]: Starting lnbits.service - lnbits...
Mai 17 15:50:39 debian bonus.lnbits.sh[3454850]: # Running: 'bonus.lnbits.sh prestart'
Mai 17 15:50:39 debian bonus.lnbits.sh[3454850]: ## lnbits.service PRESTART CONFIG
Mai 17 15:50:39 debian bonus.lnbits.sh[3454850]: # --> /home/lnbits/lnbits/.env
Mai 17 15:50:39 debian bonus.lnbits.sh[3454850]: # LNBitsFunding(lnd) --> network(bitcoin) chain(main) lightning(lnd)
Mai 17 15:50:39 debian bonus.lnbits.sh[3454850]: # setting lnd config fresh ...
Mai 17 15:50:39 debian bonus.lnbits.sh[3454876]: cat: /mnt/hdd/app-data/lnd/data/chain/bitcoin/mainnet/admin.macaroon: Datei oder Verzeichnis nicht gefunden
Mai 17 15:50:39 debian bonus.lnbits.sh[3454850]: # FAIL: missing lnd data in '/mnt/hdd/app-data/lnd' or missing access rights for lnbits user
Mai 17 15:50:40 debian systemd[1]: lnbits.service: Control process exited, code=exited, status=1/FAILURE
Mai 17 15:50:40 debian systemd[1]: lnbits.service: Failed with result 'exit-code'.
Mai 17 15:50:40 debian systemd[1]: Failed to start lnbits.service - lnbits.
```

But could also be because of my VM setup - LND itself has problems:
```
Mai 17 15:50:28 debian systemd[1]: Starting lnd.service - Lightning Network Daemon on mainnet...
Mai 17 15:50:30 debian lnd.check.sh[3454199]: FAIL: 'rpcpassword' not found in /mnt/hdd/bitcoin/bitcoin.conf
Mai 17 15:50:31 debian lnd[3454310]: failed to load config: ValidateConfig: unable to load RPC credentials for bitcoind: please set bitcoind.rpcuser *** bitcoind.rpcpass (or bitcoind.rpccookie) together with bitcoind.zmqpubrawblock, bitcoind.zmqpubrawtx
Mai 17 15:50:31 debian systemd[1]: lnd.service: Main process exited, code=exited, status=1/FAILURE
Mai 17 15:50:31 debian systemd[1]: lnd.service: Failed with result 'exit-code'.
Mai 17 15:50:31 debian systemd[1]: Failed to start lnd.service - Lightning Network Daemon on mainnet.
Mai 17 15:50:31 debian systemd[1]: lnd.service: Consumed 3.031s CPU time.
```

**Review by rootzoll — APPROVED** [review]

**Pull request merged**
