### PR TITLE
cln update to v23.02, backup-plugin update, add poetry

### PR DESCRIPTION
**Pull request by openoms**
fixing: #3675 #3676 #3677

on to testing

### CODE REVIEW

**Comment by openoms** [comment]
Having a new issue now:
```
 DEBUG   plugin-manager: started(3578707) /home/bitcoin/cl-plugins-available/plugins/backup/backup.py 
 INFO    plugin-backup.py: Killing plugin: exited before replying to getmanifest
```

```
₿ scl plugin start /home/bitcoin/scl-plugins-enabled/backup.py
{
   "code": -3,
   "message": "/home/bitcoin/cl-plugins-available/plugins/backup/backup.py: exited before replying to getmanifest"
}
```
Cannot reproduce yet on amd64, only happens on the RPi.

**Comment by openoms** [comment]
did a new install with v1.9.0rc2 minimal image with  this branch, now getting:
```
raspberrypi systemd[1]: Started c-lightning daemon on mainnet.
 sh[25987]: Traceback (most recent call last):
 sh[25987]:   File "/home/bitcoin/cl-plugins-available/plugins/backup/backup.py", line 2, in <module>
raspberrypi sh[25987]:     from pyln.client import Plugin
raspberrypi sh[25987]: ModuleNotFoundError: No module named 'pyln'
```

This could be a problem while running:
```
cd /home/bitcoin/cl-plugins-available/plugins/backup
sudo -u bitcoin poetry install

Installing dependencies from lock file
Warning: poetry.lock is not consistent with pyproject.toml. You may be getting improper dependencies. Run `poetry lock [--no-update]` to fix it.
```

**Comment by openoms** [comment]
Tested with a new install with v1.9.0rc2 minimal image with this branch and the backup plugin is activated now.

**Comment by openoms** [comment]
The CLN install with verification can be tested with:
```
# checkout this PR branch in UPDATE - PATCH
# REPO; rootzoll
# BRANCH: backup-plugin-update
# remove the old binary
sudo rm $(which lightningd)
# remove the old source code
sudo rm -rf /home/bitcoin/lightning
# install the new default version v23.02
config.scripts/cl.install.sh on
```

**Review by rootzoll — APPROVED** [review]

**Comment by rootzoll** [comment]
@openoms is this PR ready for merge?

**Comment by openoms** [comment]
@rootzoll yes, tests look good and full of fixes

**Comment by openoms** [comment]
updated CL REST and also tested ok so merging

**Pull request merged**
