### PR TITLE
btcpay update to v1.9.1, migration to postgres

### LINKED ISSUE #3755: BTCpay update to v1.9.0 to migrate all to postgres
Due to test the migration, if it works reliably it could be attempted automatically for the update to BTCpay v1.9.0 and the new version could be made default.

### PR DESCRIPTION
**Pull request by openoms**
fixes #3755 #1725 #3729

tested ok with a long running sqlite database and new install as well

### CODE REVIEW

**Comment by openoms** [comment]
got an error with nbxplorer on a new install on RPi4:
```
Apr 14 19:01:42 raspberrypi dotnet[1505048]: info: NBXplorer.Events: BTC: Node state changed: NotStarted => NBXplorerSynching
Apr 14 19:01:45 raspberrypi dotnet[1505048]: fail: NBXplorer.Indexer.BTC: Unhandled exception in the indexer, retrying in 15 seconds
Apr 14 19:01:45 raspberrypi dotnet[1505048]: Npgsql.PostgresException (0x80004005): XX000: could not create temporary file "base/pgsql_tmp/pgsql_tmp1508825.0": Permission denied
Apr 14 19:01:45 raspberrypi dotnet[1505048]:    at Npgsql.Internal.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|215_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
Apr 14 19:01:45 raspberrypi dotnet[1505048]:    at Npgsql.NpgsqlDataReader.<ReadMessage>g__ReadMessageSequential|44_0(NpgsqlConnector connector, Boolean async)
Apr 14 19:01:45 raspberrypi dotnet[1505048]:    at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
Apr 14 19:01:45 raspberrypi dotnet[1505048]:    at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
Apr 14 19:01:45 raspberrypi dotnet[1505048]:    at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
Apr 14 19:01:45 raspberrypi dotnet[1505048]:    at Npgsql.NpgsqlCommand.ExecuteScalar(Boolean async, CancellationToken cancellationToken)
Apr 14 19:01:45 raspberrypi dotnet[1505048]:    at Dapper.SqlMapper.ExecuteScalarImplAsync[T](IDbConnection cnn, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 1210
Apr 14 19:01:45 raspberrypi dotnet[1505048]:    at NBXplorer.Backends.Postgres.DbConnectionHelper.FetchMatches(IEnumerable`1 newOuts, IEnumerable`1 newIns) in /home/btcpay/NBXplorer/NBXplorer/Backends/Postgres/DbConnectionHelper.cs:line 131
Apr 14 19:01:45 raspberrypi dotnet[1505048]:    at NBXplorer.Backends.Postgres.PostgresRepository.GetMatches(DbConnectionHelper connection, IList`1 txs, SlimChainedBlock slimBlock, DateTimeOffset now, Boolean useCache, Boolean immediateSave) in /home/btcpay/NBXplorer/NBXplorer/Backends/Postgres/PostgresRepository.cs:line 618
Apr 14 19:01:45 raspberrypi dotnet[1505048]:    at NBXplorer.Backends.Postgres.PostgresIndexers.PostgresIndexer.SaveMatches(DbConnectionHelper conn, List`1 transactions, SlimChainedBlock slimChainedBlock, Boolean fireEvents) in /home/btcpay/NBXplorer/NBXplorer/Backends/Postgres/PostgresIndexers.cs:line 375
Apr 14 19:01:45 raspberrypi dotnet[1505048]:    at NBXplorer.Backends.Postgres.PostgresIndexers.PostgresIndexer.SaveMatches(DbConnectionHelper conn, Block block, SlimChainedBlock slimChainedBlock) in /home/btcpay/NBXplorer/NBXplorer/Backends/Postgres/PostgresIndexers.cs:line 359
Apr 14 19:01:45 raspberrypi dotnet[1505048]:    at NBXplorer.Backends.Postgres.PostgresIndexers.PostgresIndexer.IndexerLoopCore(CancellationToken token) in /home/btcpay/NBXplorer/NBXplorer/Backends/Postgres/PostgresIndexers.cs:line 114
Apr 14 19:01:45 raspberrypi dotnet[1505048]:    at NBXplorer.Backends.Postgres.PostgresIndexers.PostgresIndexer.IndexerLoopCore(CancellationToken token) in /home/btcpay/NBXplorer/NBXplorer/Backends/Postgres/PostgresIndexers.cs:line 104
Apr 14 19:01:45 raspberrypi dotnet[1505048]:    at NBXplorer.Backends.Postgres.PostgresIndexers.PostgresIndexer.IndexerLoopCore(CancellationToken token) in /home/btcpay/NBXplorer/NBXplorer/Backends/Postgres/PostgresIndexers.cs:line 165
Apr 14 19:01:45 raspberrypi dotnet[1505048]:    at NBXplorer.Backends.Postgres.PostgresIndexers.PostgresIndexer.IndexerLoopCore(CancellationToken token) in /home/btcpay/NBXplorer/NBXplorer/Backends/Postgres/PostgresIndexers.cs:line 78
Apr 14 19:01:45 raspberrypi dotnet[1505048]:    at NBXplorer.Backends.Postgres.PostgresIndexers.PostgresIndexer.IndexerLoop() in /home/btcpay/NBXplorer/NBXplorer/Backends/Postgres/PostgresIndexers.cs:line 56
Apr 14 19:01:45 raspberrypi dotnet[1505048]:   Exception data:
Apr 14 19:01:45 raspberrypi dotnet[1505048]:     Severity: ERROR
Apr 14 19:01:45 raspberrypi dotnet[1505048]:     SqlState: XX000
Apr 14 19:01:45 raspberrypi dotnet[1505048]:     MessageText: could not create temporary file "base/pgsql_tmp/pgsql_tmp1508825.0": Permission denied
Apr 14 19:01:45 raspberrypi dotnet[1505048]:     Where: SQL statement "CREATE TEMPORARY TABLE matched_outs AS
Apr 14 19:01:45 raspberrypi dotnet[1505048]:         SELECT o.* FROM scripts s
Apr 14 19:01:45 raspberrypi dotnet[1505048]:         JOIN unnest(in_outs)  WITH ORDINALITY AS o(tx_id, idx, script, value, asset_id, "order") USING (script)
Apr 14 19:01:45 raspberrypi dotnet[1505048]:         WHERE s.code=in_code
Apr 14 19:01:45 raspberrypi dotnet[1505048]:         ORDER BY "order""
Apr 14 19:01:45 raspberrypi dotnet[1505048]: PL/pgSQL function fetch_matches(text,new_out[],new_in[],boolean) line 8 at SQL statement
Apr 14 19:01:45 raspberrypi dotnet[1505048]:     File: fd.c
Apr 14 19:01:45 raspberrypi dotnet[1505048]:     Line: 1711
Apr 14 19:01:45 raspberrypi dotnet[1505048]:     Routine: OpenTemporaryFileInTablespace
```

it was a permission issue on my test machine, fixed manually, but adding a safety check in the postgres install which would have prevented it.

**Comment by openoms** [comment]
Adding the tor endpoint always - tested and doesn't break btcpay if Tor is off.

**Review by rootzoll — APPROVED** [review]

**Comment by rootzoll** [comment]
On testing install seems OK (fresh install). But when running I get a "502 Bad Gateway" and the logs show the following error:

```
Apr 18 22:11:16 raspberrypi dotnet[2072513]: info: Configuration:  Data Directory: /home/btcpay/.btcpayserver/Main
Apr 18 22:11:16 raspberrypi dotnet[2072513]: info: Configuration:  Configuration File: /home/btcpay/.btcpayserver/Main/settings.config
Apr 18 22:11:17 raspberrypi dotnet[2072513]: info: BTCPayServer.Plugins.PluginManager: Loading plugins from /home/btcpay/.btcpayserver/Plugins
Apr 18 22:11:19 raspberrypi dotnet[2072513]: info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer - 1.8.2
Apr 18 22:11:19 raspberrypi dotnet[2072513]: info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer.Plugins.Shopify - 1.8.2
Apr 18 22:11:19 raspberrypi dotnet[2072513]: info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer.Plugins.NFC - 1.8.2
Apr 18 22:11:19 raspberrypi dotnet[2072513]: info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer.Plugins.Crowdfund - 1.8.2
Apr 18 22:11:19 raspberrypi dotnet[2072513]: info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer.Plugins.PayButton - 1.8.2
Apr 18 22:11:19 raspberrypi dotnet[2072513]: info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer.Plugins.PointOfSale - 1.8.2
Apr 18 22:11:19 raspberrypi dotnet[2072513]: info: Configuration:  Supported chains: BTC
Apr 18 22:11:20 raspberrypi dotnet[2072513]: Unhandled exception. System.InvalidOperationException: No database option was configured.
Apr 18 22:11:20 raspberrypi dotnet[2072513]:    at BTCPayServer.Hosting.BTCPayServerServices.<>c__DisplayClass1_0.<AddBTCPayServer>b__11(DatabaseOptions options, IOptions`1 datadirs) in /home/btcpay/btcpayserver/BTCPayServer/Hosting/BTCPayServerServices.cs:line 185
Apr 18 22:11:20 raspberrypi dotnet[2072513]:    at Microsoft.Extensions.Options.ConfigureNamedOptions`2.Configure(String name, TOptions options)
Apr 18 22:11:20 raspberrypi dotnet[2072513]:    at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
Apr 18 22:11:20 raspberrypi dotnet[2072513]:    at Microsoft.Extensions.Options.UnnamedOptionsManager`1.get_Value()
Apr 18 22:11:20 raspberrypi dotnet[2072513]:    at BTCPayServer.Abstractions.Contracts.BaseDbContextFactory`1.ConfigureBuilder(DbContextOptionsBuilder builder) in /home/btcpay/btcpayserver/BTCPayServer.Abstractions/Contracts/BaseDbContextFactory.cs:line 71
Apr 18 22:11:20 raspberrypi dotnet[2072513]:    at BTCPayServer.Hosting.BTCPayServerServices.<>c.<AddBTCPayServer>b__1_2(IServiceProvider provider, DbContextOptionsBuilder o) in /home/btcpay/btcpayserver/BTCPayServer/Hosting/BTCPayServerServices.cs:line 88
Apr 18 22:11:20 raspberrypi dotnet[2072513]:    at Microsoft.Extensions.DependencyInjection.EntityFrameworkServiceCollectionExtensions.CreateDbContextOptions[TContext](IServiceProvider applicationServiceProvider, Action`2 optionsAction)
Apr 18 22:11:20 raspberrypi dotnet[2072513]:    at Microsoft.Extensions.DependencyInjection.EntityFrameworkServiceCollectionExtensions.<>c__DisplayClass17_0`1.<AddCoreServices>b__0(IServiceProvider p)
Apr 18 22:11:20 raspberrypi dotnet[2072513]:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
Apr 18 22:11:20 raspberrypi dotnet[2072513]:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
Apr 18 22:11:20 raspberrypi dotnet[2072513]:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
Apr 18 22:11:20 raspberrypi dotnet[2072513]:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
Apr 18 22:11:20 raspberrypi dotnet[2072513]:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
Apr 18 22:11:20 raspberrypi dotnet[2072513]:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
Apr 18 22:11:20 raspberrypi dotnet[2072513]:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
Apr 18 22:11:20 raspberrypi dotnet[2072513]:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
Apr 18 22:11:20 raspberrypi dotnet[2072513]:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
Apr 18 22:11:20 raspberrypi dotnet[2072513]:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
Apr 18 22:11:20 raspberrypi dotnet[2072513]:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
Apr 18 22:11:20 raspberrypi dotnet[2072513]:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
Apr 18 22:11:20 raspberrypi dotnet[2072513]:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
Apr 18 22:11:20 raspberrypi dotnet[2072513]:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
Apr 18 22:11:20 raspberrypi dotnet[2072513]:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
Apr 18 22:11:20 raspberrypi dotnet[2072513]:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
Apr 18 22:11:20 raspberrypi dotnet[2072513]:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
Apr 18 22:11:20 raspberrypi dotnet[2072513]:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
Apr 18 22:11:20 raspberrypi dotnet[2072513]:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
Apr 18 22:11:20 raspberrypi dotnet[2072513]:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
Apr 18 22:11:20 raspberrypi dotnet[2072513]:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
Apr 18 22:11:20 raspberrypi dotnet[2072513]:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
Apr 18 22:11:20 raspberrypi dotnet[2072513]:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitIEnumerable(IEnumerableCallSite enumerableCallSite, RuntimeResolverContext context)
Apr 18 22:11:20 raspberrypi dotnet[2072513]:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
Apr 18 22:11:20 raspberrypi dotnet[2072513]:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
Apr 18 22:11:20 raspberrypi dotnet[2072513]:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
Apr 18 22:11:20 raspberrypi dotnet[2072513]:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass2_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
Apr 18 22:11:20 raspberrypi dotnet[2072513]:    at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
Apr 18 22:11:20 raspberrypi dotnet[2072513]:    at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
Apr 18 22:11:20 raspberrypi dotnet[2072513]:    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
Apr 18 22:11:20 raspberrypi dotnet[2072513]:    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
Apr 18 22:11:20 raspberrypi dotnet[2072513]:    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetServices[T](IServiceProvider provider)
Apr 18 22:11:20 raspberrypi dotnet[2072513]:    at Microsoft.AspNetCore.Hosting.WebHostExtensions.StartWithTasksAsync(IWebHost webHost, CancellationToken cancellationToken)
Apr 18 22:11:20 raspberrypi dotnet[2072513]:    at BTCPayServer.Program.Main(String[] args) in /home/btcpay/btcpayserver/BTCPayServer/Program.cs:line 76
Apr 18 22:11:20 raspberrypi systemd[1]: btcpayserver.service: Main process exited, code=exited, status=134/n/a
Apr 18 22:11:20 raspberrypi systemd[1]: btcpayserver.service: Failed with result 'exit-code'.
Apr 18 22:11:20 raspberrypi systemd[1]: btcpayserver.service: Consumed 7.037s CPU time.
```

**Comment by openoms** [comment]
Tried to reproduce on rpi and amd64 after removing btcpay + data, but worked ok.

Your log suggests that it was missing the postgres connection string which should be filled in on every run of the install script either on install or update.

If you still have the node around can you check if there is a line:
```
postgres=User ID=btcpay;Host=localhost;Port=5432;Application Name=btcpay;MaxPoolSize=20;Database=btcpaymainnet;Password='raspiblitz';
```
in
```
/home/btcpay/.btcpayserver/Main/settings.config
```
?

**Comment by rootzoll** [comment]
The content of `/home/btcpay/.btcpayserver/Main/settings.config` after fresh install with the script:

```
admin@192.168.178.60:~ ₿ sudo cat /home/btcpay/.btcpayserver/Main/settings.config
### Global settings ###
#network=mainnet

### Server settings ###
#port=23000
#bind=127.0.0.1
#httpscertificatefilepath=devtest.pfx
#httpscertificatefilepassword=toto

### Database ###
#postgres=User ID=root;Password=myPassword;Host=localhost;Port=5432;Database=myDataBase;
#mysql=User ID=root;Password=myPassword;Host=localhost;Port=3306;Database=myDataBase;
#sqlitefile=sqlite.db

### NBXplorer settings ###
#BTC.explorer.url=http://127.0.0.1:24444/
#BTC.explorer.cookiefile=/home/btcpay/.nbxplorer/Main/.cookie
#BTC.blockexplorerlink=https://mempool.space/tx/{0}
#BTC.lightning=/root/.lightning/lightning-rpc
#BTC.lightning=https://apitoken:API_TOKEN_SECRET@charge.example.com/
```

**Comment by openoms** [comment]
this is the deafult config not overwritten 

it was probably because I had `lnd=on` on all test nodes so the `BtcPayConfig` function was running after the directory was created.

I presume you had no lnd installed on this node?

[0f7118c](https://github.com/rootzoll/raspiblitz/pull/3756/commits/0f7118cc405e09d6d4858913d6c63ebf187988a3) should fix the problem by making sure the directory exists before creating the custom config.

**Review by rootzoll — APPROVED** [review]

**Comment by rootzoll** [comment]
Installtest now looks good. thx. merging for v1.9.0rc4

**Pull request merged**
