### PR TITLE
c-lightning dev and systemd hardening

### PR DESCRIPTION
**Pull request by openoms**
Includes further functions and improvements for c-lightning, building on https://github.com/rootzoll/raspiblitz/pull/2334

Includes the systemd hardening measure discussed in: https://github.com/rootzoll/raspiblitz/issues/1167 so testing can go forward early.

### CODE REVIEW

**Comment by nyxnor** [comment]
Hi.
What is the command to get the onion address for c-lightning?
```
lightning-cli .......
bitcoin-cli getnetworkinfo | jq -r '.localaddresses [0] .address'
lncli getinfo | jq -r '.uris [0]'
```

**Comment by openoms** [comment]
Find all the commands here: https://lightning.readthedocs.io/lightning-getinfo.7.html

I use for cln:
`toraddress=$(echo "$lightning_alias getinfo" | grep ".onion" | cut -d= -f2)`


get the aliases with:
```
source <(/home/admin/config.scripts/network.aliases.sh getvars [lnd|cln] [mainnet|testnet|signet]) 
```

it follows the defaults if not specified

**Comment by openoms** [comment]
@nyxnor also make sure you catch the onion address for lnd in case there is a clearnet IP too:

example
``` 
  ln_getInfo=$($lncli_alias getinfo 2>/dev/null)
  ln_external=$(echo "${ln_getInfo}" | jq -r '.uris' | grep onion | cut -d'"' -f2 | cut -d':' -f1)
  ```

**Comment by openoms** [comment]
@rootzoll this is ready to be merged for further testing and movement towards the `dev` branch

**Comment by openoms** [comment]
ok merging this as discussed with @rootzoll

**Pull request merged**
