### PR TITLE
update lnbits to 0.10.2 and use poetry instead of venv

### PR DESCRIPTION
**Pull request by dni**
as the title states, updating lnbits to 0.10.2 and installing/running it with poetry now
i did not test it on a raspiblitz yet ;(

LNbits version 0.10.2 will be releases very soon.

### CODE REVIEW

**Comment by rootzoll** [comment]
Thanks for the PR :) - can you base it on the `dev` branch please.

**Comment by rootzoll** [comment]
And how soon is 0.10.2 .. next week or more next month?

**Comment by dni** [comment]
i hope 0.10.2 is today :) :crossed_fingers:

**Comment by rootzoll** [comment]
> i hope 0.10.2 is today :) 🤞

Bildschirm­foto 2023-03-08 um 13 06 33

**Comment by dni** [comment]
https://github.com/rootzoll/raspiblitz/pull/3703

**Pull request closed without merging**
