### PR TITLE
specter update to v1.13.1

### PR DESCRIPTION
**Pull request by openoms**
Updating to the last version before Python 3.10 is a requirement

fixes: https://github.com/raspiblitz/raspiblitz/issues/4024

Test:
```
# download
wget -O /home/admin/config.scripts/bonus.specter.sh https://raw.githubusercontent.com/raspiblitz/raspiblitz/specter-1.13.1/home.admin/config.scripts/bonus.specter.sh

# uninstall old version (can try keeping the data)
config.scripts/bonus.specter.sh off

# install
config.scripts/bonus.specter.sh on
```

### CODE REVIEW

**Comment by rootzoll** [comment]
I tried to install on v1.10.0rc1 - install ran thru but on starting in the browser I got this:

Bildschirmfoto 2023-07-28 um 22 02 17

**Comment by openoms** [comment]
Rebased to fix the conflict. Weird that it worked for me. Needs more testing.

**Comment by openoms** [comment]
der

**Comment by openoms** [comment]
I wonder if a pip upgrade would fix this. Either:
```
# update pip in the venv
sudo -u specter /home/specter/.env/bin/python3 -m pip install --upgrade pip
sudo systemctl restart specter
```
or  a full reinstall:
```
# download
wget -O /home/admin/config.scripts/bonus.specter.sh https://raw.githubusercontent.com/raspiblitz/raspiblitz/specter-1.13.1/home.admin/config.scripts/bonus.specter.sh

# uninstall old version (can try keeping the data)
config.scripts/bonus.specter.sh off

# upgrade global pip
sudo python3 -m pip install --upgrade pip

# install
config.scripts/bonus.specter.sh on
```

**Comment by rootzoll** [comment]
OK test looks good now - merging for further tests during release cadidates

**Review by rootzoll — APPROVED** [review]

**Pull request merged**
