### PR TITLE
 build: fix github web-flow PGPpubkeyFingerprint

### PR DESCRIPTION
**Pull request by openoms**
fixes: https://github.com/raspiblitz/raspiblitz/issues/4406

need to check if using the new fingerprint doesn't break the checks on the old commits eg the LCD display script. 
- [x] wait for successful rpi build https://github.com/raspiblitz/raspiblitz/actions/runs/7900058813/job/21560806728?pr=4417

### CODE REVIEW

**Comment by openoms** [comment]
As expected it is a problem in https://github.com/raspiblitz/raspiblitz/actions/runs/7889873824 :
```
    arm.raspiblitz-arm64-rpi: # INSTALL 64bit LCD DRIVER
==> arm.raspiblitz-arm64-rpi: sudo: unable to resolve host 3608ec51f8ca: Name or service not known
    arm.raspiblitz-arm64-rpi: raspberrypi-bootloader set on hold.
    arm.raspiblitz-arm64-rpi: # clone/download https://github.com/tux1c/wavesharelcd-64bit-rpi.git
==> arm.raspiblitz-arm64-rpi: sudo: unable to resolve host 3608ec51f8ca: Name or service not known
==> arm.raspiblitz-arm64-rpi: fatal: destination path 'wavesharelcd-64bit-rpi' already exists and is not an empty directory.
==> arm.raspiblitz-arm64-rpi: sudo: unable to resolve host 3608ec51f8ca: Name or service not known
==> arm.raspiblitz-arm64-rpi: sudo: unable to resolve host 3608ec51f8ca: Name or service not known
==> arm.raspiblitz-arm64-rpi: sudo: unable to resolve host 3608ec51f8ca: Name or service not known
==> arm.raspiblitz-arm64-rpi: Already on 'master'
    arm.raspiblitz-arm64-rpi: Your branch is up to date with 'origin/master'.
==> arm.raspiblitz-arm64-rpi: sudo: unable to resolve host 3608ec51f8ca: Name or service not known
    arm.raspiblitz-arm64-rpi: HEAD is now at 5a206a7 Update install.sh
==> arm.raspiblitz-arm64-rpi: sudo: unable to resolve host 3608ec51f8ca: Name or service not known
==> arm.raspiblitz-arm64-rpi: --2024-02-13 17:13:06--  https://github.com/web-flow.gpg
==> arm.raspiblitz-arm64-rpi: Resolving github.com (github.com)... 192.30.255.113
==> arm.raspiblitz-arm64-rpi: Connecting to github.com (github.com)|192.30.255.113|:443... connected.
==> arm.raspiblitz-arm64-rpi: HTTP request sent, awaiting response... 200 OK
==> arm.raspiblitz-arm64-rpi: Length: 2483 (2.4K) [text/plain]
==> arm.raspiblitz-arm64-rpi: Saving to: ‘/var/cache/raspiblitz/pgp_keys_GitHub.asc’
==> arm.raspiblitz-arm64-rpi:
==> arm.raspiblitz-arm64-rpi:      0K ..                                                    100% 1.66M=0.001s
==> arm.raspiblitz-arm64-rpi:
==> arm.raspiblitz-arm64-rpi: 2024-02-13 17:13:06 (1.66 MB/s) - ‘/var/cache/raspiblitz/pgp_keys_GitHub.asc’ saved [2483/2483]
==> arm.raspiblitz-arm64-rpi:
    arm.raspiblitz-arm64-rpi: # importing key of GitHub
==> arm.raspiblitz-arm64-rpi: gpg: directory '/home/admin/.gnupg' created
==> arm.raspiblitz-arm64-rpi: gpg: keybox '/home/admin/.gnupg/pubring.kbx' created
    arm.raspiblitz-arm64-rpi: pub   rsa2048 2017-08-16 [SC] [expired: 2024-01-16]
    arm.raspiblitz-arm64-rpi:       5DE3E0509C47EA3CF04A42D34AEE18F83AFDEB23
    arm.raspiblitz-arm64-rpi: uid                      GitHub (web-flow commit signing) <noreply@github.com>
    arm.raspiblitz-arm64-rpi:
    arm.raspiblitz-arm64-rpi: pub   rsa4096 2024-01-16 [SC]
    arm.raspiblitz-arm64-rpi:       968479A1AFF927E37D1A566BB5690EEEBB952194
    arm.raspiblitz-arm64-rpi: uid                      GitHub <noreply@github.com>
    arm.raspiblitz-arm64-rpi:
==> arm.raspiblitz-arm64-rpi: gpg: /home/admin/.gnupg/trustdb.gpg: trustdb created
==> arm.raspiblitz-arm64-rpi: gpg: key 4AEE18F83AFDEB23: public key "GitHub (web-flow commit signing) <noreply@github.com>" imported
==> arm.raspiblitz-arm64-rpi: gpg: key B5690EEEBB952194: public key "GitHub <noreply@github.com>" imported
==> arm.raspiblitz-arm64-rpi: gpg: Total number processed: 2
==> arm.raspiblitz-arm64-rpi: gpg:               imported: 2
    arm.raspiblitz-arm64-rpi: # running: git verify-commit 5a206a7
    arm.raspiblitz-arm64-rpi:
    arm.raspiblitz-arm64-rpi: gpg: Signature made Sun 16 Aug 2020 02:46:52 PM BST
    arm.raspiblitz-arm64-rpi: gpg:                using RSA key 4AEE18F83AFDEB23
    arm.raspiblitz-arm64-rpi: gpg: Good signature from "GitHub (web-flow commit signing) <noreply@github.com>" [expired]
    arm.raspiblitz-arm64-rpi: gpg: Note: This key has expired!
    arm.raspiblitz-arm64-rpi: Primary key fingerprint: 5DE3 E050 9C47 EA3C F04A  42D3 4AEE 18F8 3AFD EB23
    arm.raspiblitz-arm64-rpi:
    arm.raspiblitz-arm64-rpi: # goodSignature(1)
    arm.raspiblitz-arm64-rpi: # correctKey(0)
    arm.raspiblitz-arm64-rpi:
    arm.raspiblitz-arm64-rpi: # BUILD FAILED --> PGP verification not OK / signature(1) verify(0)
 ```
 
 Need to modify the script to check for the old key also.

**Comment by openoms** [comment]
the failed build here is a result of running out of disks space,  not related to the changes. Also the other two build succeed.

**Review by rootzoll — APPROVED** [review]

**Review by rootzoll — APPROVED** [review]
teseted parts of it - looks good

**Comment by ray-bun** [comment]
Not a disk space issue for me. Does this mean the install has failed? Do I need to try again?
Screenshot 2024-02-26 at 11 25 16 am

**Pull request merged**
