### PR TITLE
Service updates

### PR DESCRIPTION
**Pull request by openoms**
Tested service updates for Loop, BoS, Thunderhub and RTL
Waiting for RTL 0.9.0 for https://github.com/Ride-The-Lightning/RTL/issues/425

Related: 
https://github.com/rootzoll/raspiblitz/issues/1409

### CODE REVIEW

**Comment by openoms** [comment]
Shall we open a `dev` branch to continue from master towards to work towards the `v1.6.1` tag as suggested in https://github.com/rootzoll/raspiblitz/issues/1406?

**Comment by frennkie** [comment]
LGTM (tested all installs with off + on)

~Except for thunderhub.. getting a HTTP 500.~ Can't reproduce.. maybe it was a browser cookie/cache issue.

**Comment by rootzoll** [comment]
@openoms the PR conflicts with previous changes to v1.6 branch.

**Comment by openoms** [comment]
sorted with minimal changes

**Pull request merged**
