### PR TITLE
Update 00settingsMenuServices.sh

### PR DESCRIPTION
**Pull request by allyourbankarebelongtous**
Fixes a conflict between LightningTipBot and LNDg install on the SERVICES menu. Both LNDg and LightningTipBot were using "g" as the character to identify selection, resulting in the installation of both services when one is selected. Changes the identifier for LNDg to a ü.

### CODE REVIEW

**Comment by allyourbankarebelongtous** [comment]
Fixes [Issue #3537](https://github.com/rootzoll/raspiblitz/issues/3537)

Tests good

**Comment by openoms** [comment]
Thanks for catching this. As we are running out of characters I think it would be better to use double ASCII characters for the menu identification rather than starting to introduce non-ASCII letters. It can make thing complicated that `ü` is not on the most widely used English keyboards.

Would need to double all letters like adding `a` to the end of all of them to start with, then `b` as necessary like here it could be `ga` for LightningTipBot and `gb` for LNDg.

**Comment by allyourbankarebelongtous** [comment]
> Thanks for catching this. As we are running out of characters I think it would be better to use double ASCII characters for the menu identification rather than starting to introduce non-ASCII letters. It can make thing complicated that `ü` is not on the most widely used English keyboards.
> 
> Would need to double all letters like adding `a` to the end of all of them to start with, then `b` as necessary like here it could be `ga` for LightningTipBot and `gb` for LNDg.

Incoming!

**Comment by allyourbankarebelongtous** [comment]
Changed as suggested. Tests good on the nuc.

**Review by openoms — APPROVED** [review]
LGTM

**Review by rootzoll — APPROVED** [review]

**Pull request merged**
