### PR TITLE
RTL, clrest update, fix update options for cli

### PR DESCRIPTION
**Pull request by openoms**
Related: https://github.com/rootzoll/raspiblitz/issues/3837

To test the update:
```
# download
wget -O /home/admin/config.scripts/cl.rest.sh https://raw.githubusercontent.com/rootzoll/raspiblitz/cl-rest-update/home.admin/config.scripts/cl.rest.sh
# run 
/home/admin/config.scripts/cl.rest.sh update
```

### CODE REVIEW

**Comment by surfac3** [comment]
I tested these changes on my blitz with CL23.05 and it seem to have worked.
After instalation we had to do a restart of clrest `sudo systemctl restart clrest` , rebooting the node didnt work. 

After this was done both Zeus and RTL started to show correct balances of channels.

**Comment by openoms** [comment]
The latest here is https://github.com/Ride-The-Lightning/c-lightning-REST/releases/tag/v0.10.5, will update and test

**Review by rootzoll — APPROVED** [review]

**Comment by rootzoll** [comment]
I will already merge - but keep branch open if there are more changes to make on this. If done please delete branch.

**Comment by surfac3** [comment]
I have tested the latest RTL @openoms mentioned and all runs OK 

The channel balances are all there as they should. 

Tested it using Raspiblitz 1.9 with clightning 23.05.2 and bitcoincore v24.1

**Comment by chrisguida** [comment]
My channel balances in RTL are not working with this setup

Screenshot from 2023-08-20 21-03-38

**Pull request merged**
