### PR TITLE
Bonus script to install CLN Watchtower client rust-teos ("The Eye of Satoshi")

### PR DESCRIPTION
**Pull request by steepdawn974**
This adds a Bonus script and respective Menu items to install the Core Lightning Watchtower client "The Eye of Satoshi", as described in #3394

Status
- [x]  Tested successfully on amd64: install (`cl-plugin.watchtower-client.sh on`) | remove (`cl-plugin.watchtower-client.sh off`) | remove & purge (`cl-plugin.watchtower-client.sh off mainnet purge`)
- [x] Tested enabling/disabling through Menu
- [x]  Test on Raspi hardware (arm)  -- Help wanted
- [ ] Test with parallel testnet and signet enabled

Given this is my first development for the raspiblitz, I encourage review and feedback. In particular

- Am I cloning into the "correct" folder?
- Naming convention of the script and menu entries correct?
- Do we need this https://github.com/rootzoll/raspiblitz/pull/3404/files#diff-88d14d19c5add5919318691f372e9b09f415bdd2d8d62846b0cb2fc4c9f3f501R38-R41 cleanup before cloning?
- Does it make sense to use the `$runBehindTor` var? My itention is to check if this CLN node is tor-only, and if so, also connect the watchtower-client only via TOR. But if `$runBehindTor` setting only aplies to the bitcoind settings, then my check is obviously pointless..  
- Is it ok to use hardcoded value `9050` for TOR port? Or is there some raspi variable I should use instead?
- Should we pin a VERSION of `rust-teos` instead of cloning the latest?
- Are two commits fine, or is it recommended to rebase into one single commit, before opening a PR?

### CODE REVIEW

**Comment by rootzoll** [comment]
Thx. Marked for testing with v1.8.1 release (now called 1.9.0)

**Comment by rootzoll** [comment]
- [x] Add entry in the CHANGES file about new bonus app

**Comment by rootzoll** [comment]
@steepdawn974 Test install on RasperryPi it gave me the following error:

```
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_aarch64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
  run pkg_config fail: "`\"pkg-config\" \"--libs\" \"--cflags\" \"openssl\"` did not exit successfully: exit status: 1\nerror: could not find system library 'openssl' required by the 'openssl-sys' crate\n\n--- stderr\nPackage openssl was not found in the pkg-config search path.\nPerhaps you should add the directory containing `openssl.pc'\nto the PKG_CONFIG_PATH environment variable\nNo package 'openssl' found\n"

  --- stderr
  thread 'main' panicked at '

  Could not find directory of OpenSSL installation, and this `-sys` crate cannot
  proceed without this knowledge. If OpenSSL is installed and this crate had
  trouble finding it,  you can set the `OPENSSL_DIR` environment variable for the
  compilation process.

  Make sure you also have the development packages of openssl installed.
  For example, `libssl-dev` on Ubuntu or `openssl-devel` on Fedora.

  If you're in a situation where you think the directory *should* be found
  automatically, please open a bug at https://github.com/sfackler/rust-openssl
  and include information about your system as well as this message.

  $HOST = aarch64-unknown-linux-gnu
  $TARGET = aarch64-unknown-linux-gnu
  openssl-sys = 0.9.77

  ', /home/bitcoin/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-sys-0.9.77/build/find_normal.rs:191:5
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: failed to compile `watchtower-plugin v0.1.2 (/home/bitcoin/cl-plugins-available/rust-teos/watchtower-plugin)`, intermediate artifacts can be found at `/home/bitcoin/cl-plugins-available/watchtower-client`
Running: sudo -u bitcoin ln -s /home/bitcoin/cl-plugins-available/watchtower-client/release/watchtower-client /home/bitcoin/cl-plugins-enabled/watchtower-client
watchtower-proxy=127.0.0.1:9050
# Restart the lightningd.service to activate watchtower-client
```

**Comment by steepdawn974** [comment]
Thanks for reporting. 

It worked for me on my regular Raspi4 4GB node without issues. Will to try with a fresh Raspiblitz install based on latest `dev` and see if I can reproduce your problem.

**Comment by steepdawn974** [comment]
1. Bug confirmed on a fresh sd_card Raspiblitz build on a RaspberryPi4.

Here is a Fix for this issue  "Could not find directory of OpenSSL installation" 
 --> https://github.com/steepdawn974/raspiblitz/commit/8f5987d8f5cccf9a7b3e41f9455fa76b99ff738c


2. However, now another error appears:

```
   Compiling watchtower-plugin v0.1.2 (/home/bitcoin/cl-plugins-available/rust-teos/watchtower-plugin)
error[E0277]: the trait bound `Arc<std::sync::Mutex<WTClient>>: AsyncRead` is not satisfied
   --> watchtower-plugin/src/main.rs:527:32
    |
527 |     let builder = Builder::new(state, stdin(), stdout())
    |                   ------------ ^^^^^ the trait `AsyncRead` is not implemented for `Arc<std::sync::Mutex<WTClient>>`
    |                   |
    |                   required by a bound introduced by this call
    |
    = help: the following other types implement trait `AsyncRead`:
              &[u8]
              &mut T
              Box<T>
              BufStream<RW>
              DuplexStream
              Pin<P>
              h2::codec::framed_write::FramedWrite<T, B>
              hyper::server::tcp::addr_stream::AddrStream
            and 27 others
note: required by a bound in `cln_plugin::Builder::<S, I, O>::new`
   --> /home/bitcoin/.cargo/registry/src/github.com-1ecc6299db9ec823/cln-plugin-0.1.1/src/lib.rs:107:8
    |
107 |     I: AsyncRead + Send + Unpin + 'static,
    |        ^^^^^^^^^ required by this bound in `cln_plugin::Builder::<S, I, O>::new`

error[E0277]: the trait bound `tokio::io::Stdin: AsyncWrite` is not satisfied
   --> watchtower-plugin/src/main.rs:527:39
    |
527 |     let builder = Builder::new(state, stdin(), stdout())
    |                   ------------        ^^^^^^^ the trait `AsyncWrite` is not implemented for `tokio::io::Stdin`
    |                   |
    |                   required by a bound introduced by this call
    |
    = help: the following other types implement trait `AsyncWrite`:
              &mut T
              Box<T>
              BufStream<RW>
              DuplexStream
              Pin<P>
              Vec<u8>
              hyper::server::tcp::addr_stream::AddrStream
              hyper::upgrade::Upgraded
            and 27 others
note: required by a bound in `cln_plugin::Builder::<S, I, O>::new`
   --> /home/bitcoin/.cargo/registry/src/github.com-1ecc6299db9ec823/cln-plugin-0.1.1/src/lib.rs:105:15
    |
105 |     O: Send + AsyncWrite + Unpin + 'static,
    |               ^^^^^^^^^^ required by this bound in `cln_plugin::Builder::<S, I, O>::new`

error[E0061]: this function takes 2 arguments but 3 arguments were supplied
   --> watchtower-plugin/src/main.rs:527:19
    |
527 |     let builder = Builder::new(state, stdin(), stdout())
    |                   ^^^^^^^^^^^^                 -------- argument of type `tokio::io::Stdout` unexpected
    |
note: associated function defined here
   --> /home/bitcoin/.cargo/registry/src/github.com-1ecc6299db9ec823/cln-plugin-0.1.1/src/lib.rs:109:12
    |
109 |     pub fn new(input: I, output: O) -> Self {
    |            ^^^
help: remove the extra argument
    |
527 |     let builder = Builder::new(state, stdin())
    |                               ~~~~~~~~~~~~~~~~

error[E0277]: the trait bound `Arc<std::sync::Mutex<WTClient>>: AsyncRead` is not satisfied
   --> watchtower-plugin/src/main.rs:527:19
    |
527 |     let builder = Builder::new(state, stdin(), stdout())
    |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `AsyncRead` is not implemented for `Arc<std::sync::Mutex<WTClient>>`
    |
    = help: the following other types implement trait `AsyncRead`:
              &[u8]
              &mut T
              Box<T>
              BufStream<RW>
              DuplexStream
              Pin<P>
              h2::codec::framed_write::FramedWrite<T, B>
              hyper::server::tcp::addr_stream::AddrStream
            and 27 others
note: required by a bound in `cln_plugin::Builder`
   --> /home/bitcoin/.cargo/registry/src/github.com-1ecc6299db9ec823/cln-plugin-0.1.1/src/lib.rs:37:8
    |
37  |     I: AsyncRead + Unpin,
    |        ^^^^^^^^^ required by this bound in `cln_plugin::Builder`

error[E0277]: the trait bound `tokio::io::Stdin: AsyncWrite` is not satisfied
   --> watchtower-plugin/src/main.rs:527:19
    |
527 |     let builder = Builder::new(state, stdin(), stdout())
    |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `AsyncWrite` is not implemented for `tokio::io::Stdin`
    |
    = help: the following other types implement trait `AsyncWrite`:
              &mut T
              Box<T>
              BufStream<RW>
              DuplexStream
              Pin<P>
              Vec<u8>
              hyper::server::tcp::addr_stream::AddrStream
              hyper::upgrade::Upgraded
            and 27 others
note: required by a bound in `cln_plugin::Builder`
   --> /home/bitcoin/.cargo/registry/src/github.com-1ecc6299db9ec823/cln-plugin-0.1.1/src/lib.rs:38:15
    |
38  |     O: Send + AsyncWrite + Unpin,
    |               ^^^^^^^^^^ required by this bound in `cln_plugin::Builder`

error[E0599]: the method `option` exists for struct `cln_plugin::Builder<_, Arc<std::sync::Mutex<WTClient>>, tokio::io::Stdin>`, but its trait bounds were not satisfied
   --> watchtower-plugin/src/main.rs:528:10
    |
528 |         .option(ConfigOption::new(
    |          ^^^^^^ method cannot be called on `cln_plugin::Builder<_, Arc<std::sync::Mutex<WTClient>>, tokio::io::Stdin>` due to unsatisfied trait bounds
    |
   ::: /home/bitcoin/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/io/stdin.rs:29:5
    |
29  |     pub struct Stdin {
    |     ---------------- doesn't satisfy `tokio::io::Stdin: AsyncWrite`
    |
    = note: the following trait bounds were not satisfied:
            `tokio::io::Stdin: AsyncWrite`
            `Arc<std::sync::Mutex<WTClient>>: AsyncRead`

Some errors have detailed explanations: E0061, E0277, E0599.
For more information about an error, try `rustc --explain E0061`.
error: could not compile `watchtower-plugin` due to 6 previous errors
error: failed to compile `watchtower-plugin v0.1.2 (/home/bitcoin/cl-plugins-available/rust-teos/watchtower-plugin)`, intermediate artifacts can be found at `/home/bitcoin/cl-plugins-available/watchtower-client`
Running: sudo -u bitcoin ln -s /home/bitcoin/cl-plugins-available/watchtower-client/release/watchtower-client /home/bitcoin/cl-plugins-enabled/watchtower-client
watchtower-proxy=127.0.0.1:9050
# Restart the lightningd.service to activate watchtower-client

```

No idea what that means.

Raised https://github.com/talaia-labs/rust-teos/issues/154

**Comment by steepdawn974** [comment]
Bug confirmed to be upstream in `rust-teos`

Issue: https://github.com/talaia-labs/rust-teos/issues/152

Fix (still open): https://github.com/talaia-labs/rust-teos/pull/153

**Comment by steepdawn974** [comment]
@rootzoll Bug has been fixed upstream --> https://github.com/talaia-labs/rust-teos/pull/153

Can confirm `cl-plugin.watchtower-client.sh` now runs successfully on RPi4, and amd-64

**Comment by rootzoll** [comment]
OK, install test now looks good. @steepdawn974 I think whats still missing are two things:

- [ ] A entry in `_provision_.sh` to make reinstall the plugin on recover - see example: https://github.com/rootzoll/raspiblitz/blob/b589b57215b57a0a1a97153d354a35716c4669fa/home.admin/_provision_.sh#L422
- [ ] A info dialog for the SSH menus that when the plugin is installed offers more infos to the user how to get started (basic commands and where to find a watch tower for testing) - example see:  https://github.com/rootzoll/raspiblitz/blob/b589b57215b57a0a1a97153d354a35716c4669fa/home.admin/config.scripts/bonus.bos.sh#L17

**Comment by steepdawn974** [comment]
@rootzoll - this is done.

1) For infodialog, I used a `whiptail` info screen similar to how it was done for the clboos CL plugin
2) Added an entry to `_provision_.sh` . Noticed that an entry for the CL plugin `clboss` was missing as well, and added it in the same commit. Tested the script afterward, and it ran without errors.

**Review by rootzoll — APPROVED** [review]

**Comment by rootzoll** [comment]
LGTM - I will merge into a local developemnt branch `eos-watchtower`and finalize some last changes before final merge.

**Pull request merged**
