### PR TITLE
bonus.rtl.sh: Fix C-Lightning changes of config

### PR DESCRIPTION
**Pull request by theword3**
Is is typo or autoreplace bug?

### CODE REVIEW

**Comment by openoms** [comment]
Typo most likely, escaped the final testing.
Will testa and merge, thanks for the PR!

**Comment by steepdawn974** [comment]
Still not working for me. 

If I manually trigger the `prestart` phase of the script, you'll notice that this does not go down the 
  `if [ "${LNTYPE}" == "cl" ]; then` path, because we dont see the `    echo "# CL Config"` line after `# PREPARE /home/rtl/cRTL/RTL-Config.json`

```
admin@raspberrypi:~ $ sudo -u rtl /home/admin/config.scripts/bonus.rtl.sh prestart cl mainnet
# Running: 'bonus.rtl.sh prestart cl mainnet'
# LNTYPE(cl)
# CHAIN(mainnet)
# netprefix()
# portprefix()
# typeprefix(c)
# RTLHTTP(7000)
# configEntry(crtlWebinterface)
# systemdService(cRTL)
## RTL PRESTART CONFIG (called by systemd prestart)
# Using RPCPASSWORD(xxxxxx)
# No lit or loop single detected
# PREPARE /home/rtl/cRTL/RTL-Config.json
# RTL prestart config done
```


As compared to lnd (second to last line):
```
admin@raspberrypi:~ $ sudo -u rtl /home/admin/config.scripts/bonus.rtl.sh prestart lnd mainnet
# Running: 'bonus.rtl.sh prestart lnd mainnet'
# LNTYPE(lnd)
# CHAIN(mainnet)
# netprefix()
# portprefix()
# typeprefix()
# RTLHTTP(3000)
# configEntry(rtlWebinterface)
# systemdService(RTL)
## RTL PRESTART CONFIG (called by systemd prestart)
# Using RPCPASSWORD(xxxxxxxxxxxxx)
# No lit or loop single detected
# PREPARE /home/rtl/RTL/RTL-Config.json
# LND Config
# RTL prestart config done
```


Not sure what I'm doing wrong here.  I didnt pull the whole repo, just manually pulled the file from @theword3 's repo 
 ` curl https://raw.githubusercontent.com/theword3/raspiblitz/v1.7/home.admin/config.scripts/bonus.rtl.sh --output /home/admin/raspiblitz/home.admin/config.scripts/bonus.rtl.sh`

**Comment by steepdawn974** [comment]
I found my error; I edited the wrong file: `~/raspiblitz/home.admin/config.scripts/bonus.rtl.sh` instead of `~/config.scripts/bonus.rtl.sh`

When i patch the latter file, it all works. 

[Sorry, new to this project. Didnt know these existed twice.. and how they relate. I suppose the former is some sort of master version that one can reset to, while the latter is what's currently live]

**Comment by rootzoll** [comment]
@openoms it would be great if we can merge a fix to the `v1.7` branch (and cherrypick over to `dev`) quite soon so that people can simply use the UPDATE > PATCH to get RTL for c-lightnign running. Did you had time for testing?

**Comment by openoms** [comment]
Tested, thank you!
Merging now + `cherry-pick` to `dev`

**Pull request merged**
