### PR TITLE
Updated Italian Telegram group link

### PR DESCRIPTION
**Pull request by alex27riva**
Updated the italian Telegram support group link because previous owner deleted his account.

### CODE REVIEW

**Comment by openoms** [comment]
thank you for the update! Can you please just include the one change in: [27e826c](https://github.com/raspiblitz/raspiblitz/pull/4285/commits/27e826cce9558d474d2d04e5af2d6fe5b77349d4)

In your branch:
`git reset --hard HEAD~16`
add back the change
`git push -f`

**Comment by alex27riva** [comment]
> thank you for the update! Can you please just include the one change in: [27e826c](https://github.com/raspiblitz/raspiblitz/pull/4285/commits/27e826cce9558d474d2d04e5af2d6fe5b77349d4)
> 
> In your branch: `git reset --hard HEAD~16` add back the change `git push -f`

Thanks, done.

**Comment by openoms** [comment]
Thanks, so is this ready?

**Comment by alex27riva** [comment]
> Thanks, so is this ready?

Yes

**Review by openoms — APPROVED** [review]

**Comment by openoms** [comment]
Should we cherry-pick to the default branch too @rootzoll ?

**Comment by rootzoll** [comment]
Default branch has protection and would need a PR to be merged into. With the v1.11.0 not too far away I think its also OK to wait for the next release.

**Pull request merged**
