### PR TITLE
add manual page that can be called with 'man raspiblitz'

### PR DESCRIPTION
**Pull request by nyxnor**
See issue https://github.com/rootzoll/raspiblitz/issues/2601
The manual is written in Markdown format and converted to Man with pandoc.

can call the man as any other man page as it was added to mandb
```
man raspiblitz
```

Mans are for commands, but as blitz is just one of the commands, a single man page is better.

image
image

### CODE REVIEW

**Comment by rootzoll** [comment]
Because this needs another change of the sd card build ... moving to v1.8.0

**Comment by nyxnor** [comment]
you can also just pre generate the manual page and place it on the `assets` folder. But on every system it needs to be moved to `/usr/local/man/man1/` and update the `mandb`. Can be outside of the build_sdcard.sh but I don't know where exactly.

**Comment by rootzoll** [comment]
I think its good to have this as part of the v1.8.0 build script.

**Comment by rootzoll** [comment]
I would consider this PR as outdated since there is the `blitzhelp` command now? @nyxnor do you agree?

**Comment by nyxnor** [comment]
ok, it was just a manual format instead of just printed to the screen

**Pull request closed without merging**
