### PR TITLE
remove old torrent files from 2019

### PR DESCRIPTION
**Pull request by frennkie**
No reason to keep them on the current branch heads, right?

### CODE REVIEW

**Comment by rootzoll** [comment]
Yes for v1.6 were going to remove torrent.

**Comment by DrBlackross** [comment]
yea, ive been having an issue just with syncing and torrents... i have yet to see this sync fully yet over the past 5 months and numerous installs lol.

i get a bad block error (with bitcoin blockchain and HDD), used my desktop (linux) to map the bad blocks, none. torrents download and are corrupted (i think i posted it here) redownloaded those, nothing. 

straight up sync'd hangs at about 8gb of drive space (1tb drive), every time (never seen it above 10gb disk usage)...


built with rpi4 (quad core)
case https://smile.amazon.com/dp/B07GRZRW7J/ref=cm_sw_em_r_mt_dp_U_K5Z-Eb432NR7G
10a power supply (from old miner)
and the rpi4 adapter https://smile.amazon.com/dp/B073CGQD9C/ref=cm_sw_em_r_mt_dp_U_Z5Z-EbZHWKPR2

i just don't get it, i have upnp enable in the bitcoin.conf (got tired of setting up port rules)

Sooooooooooooooooooooooooooooooooooooooooo, when is 1.6 coming out LOL

**Comment by rootzoll** [comment]
We try to get the v1.6RC2 out by the end of the week .. that should be very close to the final and good for your testing.

Why your sync hangs with a RP4 is hard to say ... such things are mostly related to the hardware. Even the rpi4 adapter board should be solid I would maybe run the RP4 out of the case for setup and use it with the HDD case that is recommended in the shopping list.

**Comment by DrBlackross** [comment]
YAY!

**Comment by DrBlackross** [comment]
i've used the hdd adapter case for many projects, from minecraft servers for the kids to media servers for work and the house. never a problem. 

which is what i find kind of odd.

**Comment by DrBlackross** [comment]
just reinstalled (free sd card and all)

image

i'll wait for 1.6 and try this again

**Comment by rootzoll** [comment]
To take a look why bitcoind is not running there I would need the output if you run the command `debug`

**Comment by DrBlackross** [comment]
sure give me a sec

**Comment by DrBlackross** [comment]
[debug.log](https://github.com/rootzoll/raspiblitz/files/4858800/debug.log)

i've reset the block chain since...

# bitcoind configuration

# mainnet/testnet
testnet=0

# Bitcoind options
server=1
daemon=1
txindex=0
disablewallet=1
upnp=1

# Connection settings
rpcuser=raspibolt
rpcpassword=###########################################
main.rpcport=8332
rpcallowip=127.0.0.1
main.rpcbind=127.0.0.1:8332
zmqpubrawblock=tcp://127.0.0.1:28332
zmqpubrawtx=tcp://127.0.0.1:28333

# Raspberry Pi optimizations
dbcache=512
maxorphantx=10
maxmempool=64
maxconnections=40
maxuploadtarget=5000

datadir=/mnt/hdd/bitcoin

addnode=108.225.195.53:8333
addnode=45.76.251.184:8333
addnode=108.64.87.190:8333
addnode=135.23.228.90:8333

test.rpcport=18332
test.rpcbind=127.0.0.1:18332

theres the conf /\

**Comment by DrBlackross** [comment]
the only i've added after raspiblitz finished install was mc (midnight commander), and to the conf was upnp and a couple of addnodes from Bitnodes.io to start off of. 

every time i reinstall i usually choose different nodes, since i can't remember the last ones.

and itll sit for about a month or a couple weeks between installs and ill check in and see how its progressing on blockchain sync or torrents

**Comment by rootzoll** [comment]
Your bitcoind seems to crash but I dont know why - there is no error message, it just goes away and restarts

**Comment by DrBlackross** [comment]
right, it does this all the time

**Comment by DrBlackross** [comment]
it gets to 9 or 10gb and craps out
like i said earlier in here it never gets past 10gb
tried 3 different hds though over the months

admin@NuggetNode:~ df -h
df: /mnt/temp-stuff: Input/output error
Filesystem      Size  Used Avail Use% Mounted on
/dev/root        14G  2.9G   11G  22% /
devtmpfs        459M     0  459M   0% /dev
tmpfs           464M     0  464M   0% /dev/shm
tmpfs           464M   47M  417M  11% /run
tmpfs           5.0M  4.0K  5.0M   1% /run/lock
tmpfs           464M     0  464M   0% /sys/fs/cgroup
/dev/mmcblk0p1  253M   53M  200M  21% /boot
/dev/sda1       916G  9.9G  860G   2% /mnt/hdd
tmpfs            93M     0   93M   0% /run/user/1000
tmpfs            93M     0   93M   0% /run/user/1001

**Comment by DrBlackross** [comment]
the part i find funny.....

admin@NuggetNode:~ $ cat /proc/cpuinfo
processor       : 0
model name      : ARMv7 Processor rev 4 (v7l)
BogoMIPS        : 89.60
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4

processor       : 1
model name      : ARMv7 Processor rev 4 (v7l)
BogoMIPS        : 89.60
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4

processor       : 2
model name      : ARMv7 Processor rev 4 (v7l)
BogoMIPS        : 89.60
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4

processor       : 3
model name      : ARMv7 Processor rev 4 (v7l)
BogoMIPS        : 89.60
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4

Hardware        : BCM2835
Revision        : a020d3
Serial          : 00000000b5e1c372
Model           : Raspberry Pi 3 Model B Plus Rev 1.3

mine is a model 4 LOL not 3


i'll wait till 1.6

**Comment by DrBlackross** [comment]
(as a lark im updating with apt, already updated raspi-config)

**Comment by DrBlackross** [comment]
nah still crashes :(

would there be a way to update raspiblitz through git in the new 1.6 version?

**Comment by rootzoll** [comment]
Update thru git to a new version will not work because the sd card needs to be build for that version.
But hopefully by the end of the week a raspiblitz v1.6RC2 will be available - check the v1.6 github branch for download:
https://github.com/rootzoll/raspiblitz/tree/v1.6#downloading-the-software

**Comment by DrBlackross** [comment]
hmmmm.....

Generating new Wallet ....
/home/admin/70initLND.sh: line 200: /home/admin/python3-env-lnd/bin/activate: No such file or directory
Traceback (most recent call last):
  File "/home/admin/config.scripts/lnd.initwallet.py", line 239, in <module>
    main()
  File "/home/admin/config.scripts/lnd.initwallet.py", line 221, in main
    stub = lnrpc.WalletUnlockerStub(channel)
AttributeError: module 'lndlibs.rpc_pb2_grpc' has no attribute 'WalletUnlockerStub'
FAIL!! -> MISSING seedwords data - but also no err data ?!?
CHECK output data above - PRESS ENTER to restart 70initLND.sh

used balena to write the *.img file to the sdcard with a formated hdd... thats the error above.

**Pull request merged**
