### PR TITLE
Download Bitcoin whitepaper from the blockchain (service and command)

### PR DESCRIPTION
**Pull request by raulcano**
Duplicate of PR 2017 with (hopefully) a correct rebase of dev into the new feature for the whitepaper.

For info about this PR visit the original
https://github.com/rootzoll/raspiblitz/pull/2017

### CODE REVIEW

**Comment by raulcano** [comment]
When I saw so many conflicts I deleted the fork to recreate the whole thing fresh, so I hope this PR will still work.
I saw that you changed the base branch  and it seems that conflicts are gone.

**Comment by openoms** [comment]
Since there is a huge amount of divergence here I've done the rebases in VScode (so not all commands are given):
* revert your commit you want to add (save the commit message)
* stash the changes
* reset to the first commit you can see in this PR
 `git reset --hard 5542a1071693a61ed8a8ae7c592ad933f60f278f`
* revert one commit more to be in sync with the old state of the `dev` branch
* apply the latest stash, add and commit (with the saved commit message)
* force push
`git push -f`

You should only see your commit(s) to add in this PR

**Comment by raulcano** [comment]
Thanks @openoms  for the explanation. I haven't understood though if I need to do all those steps ?
If that's the case, I think it would be better for me to submit a new PR from my fresh fork and cancel this one.

**Comment by openoms** [comment]
@raulcano yes, you need to achieve to only PR your changes not 250 other commits

**Comment by raulcano** [comment]
Ok, then, please ignore this PR. 
After getting a fresh fork, the PR #2081 seems ok to me.

**Pull request closed without merging**
