### PR TITLE
Update Odroid_HC1_XU4.md

### PR DESCRIPTION
**Pull request by MichaIng**
- Add Odroid MC1 (another variant)
- Update image download links
- Fix dietpi.com links
- Update "getting started" link to point to a reasonable section in our new documentation
- Remove obsolete hassle with first run setup loop of the v6.14 image

### CODE REVIEW

**Comment by openoms** [comment]
Thank for this.
I did not test DietPi for a while, but the changes look straightforward.

ACK

**Comment by MichaIng** [comment]
Another thing is that the `dietpi.txt` should be updated. Actually a nice solution for this is to use a `Automation_Custom_PreScript.sh` script to only change the `dietpi.txt` to contain `AUTO_SETUP_AUTOMATED=1` and `AUTO_SETUP_INSTALL_SOFTWARE_ID=73`, so it doesn't require an updated whenever the `dietpi.txt` content changes in future DietPi versions.

The `Automation_Custom_PreScript.sh` runs at a very early boot stage, before any login ability is ready, so it can be used to adjust `dietpi.txt` itself and trigger automation. `Automation_Custom_Script.sh` runs after all first run installs have finished (as correctly stated), so is great the way it is used within these instructions.

**Comment by rootzoll** [comment]
merged into dev for v1.7.1 release

**Comment by MichaIng** [comment]
Great. I'll open another PR with the `Automation_Custom_PreScript.sh` suggestion.

**Pull request merged**
