### PR TITLE
btc-rpc-explorer: update to v2.2.0

### PR DESCRIPTION
**Pull request by notjustanyusername**
Just a patch release with minor fixes. Have tested on my node, works as expected.

### CODE REVIEW

**Comment by frennkie** [comment]
Current version is v2.2.0 - @JosephGoulden could you also test an adapt the PR?

**Comment by notjustanyusername** [comment]
Updated 2.2.0 and tested, looks good.

**Comment by rootzoll** [comment]
Hi @JosephGoulden can you rebase the PR on the `dev` branch?

**Comment by rootzoll** [comment]
This looks good now :) merging for v1.7RC1 much thanks

**Pull request merged**
