### PR TITLE
readme: add details to shopping list 

### PR DESCRIPTION
**Pull request by openoms**
* added the part details in the shopping list to avoid confusion when the referral link is broken (or out of stock)
* clarified that the amazon links are referral links

### CODE REVIEW

**Comment by rootzoll** [comment]
@openoms your reffer there a RaspberryPi 4GB (or 8GB) ... but the link goes to a 2GB version.

In general: Do we need to a 4GB minimum for the standard package? 2GB is still around 15 USD cheaper.

**Comment by openoms** [comment]
My 2GB Odroid node is running for about a year with 20-40 channels and needed to tweak the mem usage at times of high mempool and everything installed.
As the channel.db grows it takes more RAM. I will migrate to 4GB to avoid possible problems. Running out of RAM is nasty on a routing node.
2GB is ok for minimal, but would not recommend it as the best choice.

**Comment by rootzoll** [comment]
OK I can go with a 4GB as standard - then we have enough headroom for the future.

**Comment by LightRider5** [comment]
Looks good! The problem is that some parts are not available in the US atm. So it looks like the link is broken.

**Comment by rootzoll** [comment]
@animalmother1988 we would need a new link for the 4GB, would we?

**Comment by LightRider5** [comment]
We can use this link: https://geni.us/raspiblitz-4gb-new

It is has matches in all Amazon stores in the world except India. But it is not affiliated like most of the products in the shopping lists. So it is not 100% correct to call all links "affiliate links" cause most products on Amazon are not part of any affiliate program. But for the shoppers it is the easiest solution to link them to the right product in the right Amazon store. But if have no problem to call them all "affiliate links", it is the maximum package of transparency.

**Pull request merged**
