### PR TITLE
Add option to install pyblock

### PR DESCRIPTION
**Pull request by holgern**
Fixes issue #1648

This setup up the basic config for pyblock (bclock.conf and blndconnect.conf).

A pyblock command has been added to switch to the pyblock user and a pyblock alias has been added to bashrc to directly start PyBLOCK

### CODE REVIEW

**Comment by ChuckNorrison** [comment]
This is great, thanks. I tested this PR:
- New menu entry "PyBLOCK" was available in SERVICES
- Installation of pyblock results with success and a well described hint

I catched following error from console while installation was running. pyblock is not available at path and seems an issue with requests>=2.22.0 dependency (from lnbits):

> Requirement already satisfied: colorama in /usr/lib/python3/dist-packages (from python-cfonts->-r requirements.txt (line 19)) (0.3.7)
> Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (from protobuf==3.13.0->-r requirements.txt (line 24)) (40.8.0)
> lnpay-py 0.1.0 has requirement requests>=2.22.0, but you'll have requests 2.21.0 which is incompatible.
> Installing collected packages: art, six, qrcode, python-gnupg, sseclient-py, lnpay-py, xmltodict, python-cfonts, termcolor, pycoingecko, protobuf, googleapis-common-protos
>   The script qr is installed in '/home/pyblock/.local/bin' which is not on PATH.
>   Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
>   The script cfonts is installed in '/home/pyblock/.local/bin' which is not on PATH.
>   Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
 
After adding pyblock to PATH, it works :+1:

**Comment by holgern** [comment]
Thanks, the missing path is now fixed.

**Comment by rootzoll** [comment]
Test went good :) Will add as last minute addition to v1.6.1

**Comment by rootzoll** [comment]
+cp into dev branch

**Pull request merged**
