### PR TITLE
RTL update to v0.15.2, clnrest activation, rune creation, add CLNrest to CONNECT for Zeus

### PR DESCRIPTION
**Pull request by openoms**
- [x] test clnrest activation
- [x] create and copy rune
- [x] test installs

Related to #4722 and should be tested together.

### CODE REVIEW

**Comment by rootzoll** [comment]
@openoms this PR is sill on draft - is it targeted for v1.11.3 or v1.12.x?

**Comment by openoms** [comment]
it is a heavier change with introducing runes and replacing C-Lightning-REST with the clrest plugin. Could aim for v1.12.

**Comment by openoms** [comment]
Installed RTL ok on amd64
Connected Zeus over Tor and clearnet using CLNrest

**Comment by rootzoll** [comment]
@openoms you now did quite some work on this - should I test for v1.11.3?

**Comment by openoms** [comment]
yes, ready for an RC, works well so far

**Comment by rootzoll** [comment]
@openoms RTL on my Testnode (runningCL) after install:

Bildschirmfoto 2024-10-02 um 20 53 51

**Comment by openoms** [comment]
core lightning needs to updated using the updated script in dev to have clnrest installed.

Getting the error (after removing `LogLevel=4` from the service file):
```
Oct 03 11:34:48 raspberrypi systemd[1]: Starting cRTL.service - cRTL Webinterface...
Oct 03 11:34:48 raspberrypi bonus.rtl.sh[3651616]: /home/admin/config.scripts/bonus.rtl.sh: line 498: /home/bitcoin/.lightning/bitcoin/rune_for_RTL: Permission denied
Oct 03 11:34:48 raspberrypi systemd[1]: Started cRTL.service - cRTL Webinterface.
```

**Comment by openoms** [comment]
Reproduced the problem and the fix tested now on a RPi as well.

**Comment by rootzoll** [comment]
OK RTL install looks good now - with CL & LND on my test machine.

@openoms Both my Android & iPhone were not able to to connect to the CLNrest with Zeus trhu Tor still. Local LAN worked.

**Review by rootzoll — APPROVED** [review]
The faiing Tor connection could be a temp error - the other parts seem to work well. Aprrov to merge for RaspiBlitz v1.11.3rc1

**Comment by openoms** [comment]
Could connect to the new RPi node through Tor using CLNrest on Zeus v0.9.0 on GrapheneOS, but Tor is known to be unreliable, I prefer Tailscale in place of the LAN connection.

Merging.

**Pull request merged**
