### PR TITLE
lndk update to v0.2.0 and refactor

### PR DESCRIPTION
**Pull request by openoms**

### CODE REVIEW

**Comment by openoms** [comment]
Paying 1 sat to a CLN node offer:
```
lndk-cli pay-offer lno1pqpq86q2pp6x2um5x9ekzaqkyypql3lx9jv4dg6tekarpxjgp8x067ku4e9ckezv4jqmfhzc6sazg7g
Successfully paid for offer!
```

**Comment by openoms** [comment]
Paid to a Phoenix offer as well, connected to the latest LND v0.18.3 https://njump.me/nevent1qvzqqqqqqypzp2kq0k2s388x4hcghy2k6s7p5j44jnrpxzmaevfwcxvsprzcrx30qyw8wumn8ghj7mn0wd68ytngw4eh5mmwv4nhjtnhdaexcep0qy38wumn8ghj7mt4d36xjurvv4ux2u3wdp6hx7n0dejkw7fwwahhymry9uqzpsakfl3g4fywdsw6ldmyrm32vh7c4k9yskclt8ydhrmxlxpksf9wzkahld

**Review by rootzoll — APPROVED** [review]
utACK - final testing in v1.11.3RC1 - merging

**Comment by openoms** [comment]
was a good day to merge this https://x.com/niftynei/status/1838568847701360861

**Pull request merged**
