### PR TITLE
Adding #2152 Homer Dashboard

### PR DESCRIPTION
**Pull request by rootzoll**

### CODE REVIEW

**Comment by rootzoll** [comment]
@hashes4merkle OK this PR is prepared to be merged into dev branch for the v1.7.1RC2 release. Do you see still missing pieces?

**Comment by deverickapollo** [comment]
The work here should be complete.  Unfortunately, I'm not near a spare pi to test this.

**Comment by rootzoll** [comment]
Hmm .. after testinstall got on "offline" message.

Bildschirmfoto 2021-09-29 um 17 32 30

Needs some more testing ... moving to 1.8.0 milestone

**Comment by deverickapollo** [comment]
What's the current release schedule for 1.7.1/1.8?  A friend is shipping me a spare raspberry pi so I should be able to review this feature soon.

**Comment by rootzoll** [comment]
Starting to finalize 1.7.1 on beginning of next week. 1.8.0 will be months after.

**Comment by DocBrown101** [comment]
> Hmm .. after testinstall got on "offline" message.
> 
> Bildschirmfoto 2021-09-29 um 17 32 30
> 
> Needs some more testing ... moving to 1.8.0 milestone

I have also received this message several times and on a self-hosted server this check just doesn't make sense. Therefore, you can also disable this offline check very easily in the "config.yml". Just enter "connectivityCheck: false" in the config.

Is there anything else that needs to be adjusted so that we can integrate it?

**Comment by deverickapollo** [comment]
I don't see any other major blockers at this time.  We will need to test this again with those changes.

**Comment by rootzoll** [comment]
Merged for v1.8.0 release.

**Pull request merged**
