### PR TITLE
LiT and Pool fixes and update

### PR DESCRIPTION
**Pull request by openoms**
This CLI release is the first to test sidecar channels.

LiT will be uninstalled (with the data preserved) if installing the Pool CLI to avoid interference with the accounts.
(careful here and please report problems with using the accounts with Pool CLI and LiT interchangeably)

Sidecar channels documentation: https://github.com/lightninglabs/pool/blob/master/docs/sidecar_channels.md

Quickest way to test:
```
# download the update Pool install script
wget https://raw.githubusercontent.com/openoms/raspiblitz/pool-v0.5.0/home.admin/config.scripts/bonus.pool.sh -O /home/admin/config.scripts/bonus.pool.sh
# download the updated LiT install script
wget https://raw.githubusercontent.com/openoms/raspiblitz/pool-v0.5.0/home.admin/config.scripts/bonus.lit.sh -O /home/admin/config.scripts/bonus.lit.sh
# inspect
cat /home/admin/config.scripts/bonus.pool.sh
# run 
/home/admin/config.scripts/bonus.pool.sh on
```

### CODE REVIEW

**Comment by openoms** [comment]
Merged https://github.com/rootzoll/raspiblitz/pull/2276 to make sure to avoid https://github.com/rootzoll/raspiblitz/issues/2266#issuecomment-831411475 on Pool uninstall. 
Also using the updated LiT install script.

**Comment by rootzoll** [comment]
Do you want to merge this directly into the v1.7 or into dev first?

**Comment by openoms** [comment]
I think these fixes should be in the RC1 so whichever get used for that. Will be  the `dev` I presume?

Could go to `pre-1.7.1` as well or is the plan to merge it all to `dev`?

**Comment by rootzoll** [comment]
> Could go to pre-1.7.1 as well or is the plan to merge it all to dev?

Best would be to merge into dev which will be the branch the RC1 will be based on.

**Comment by openoms** [comment]
OK ready to merge after rebase @rootzoll

**Pull request merged**
