### PR TITLE
cln update to v24.08.1

### PR DESCRIPTION
**Pull request by openoms**
pending issues: https://github.com/ElementsProject/lightning/issues/7698

Shows  v24.08.1-modded version: 
https://t.me/lightningd/34310

### CODE REVIEW

**Comment by rootzoll** [comment]
@openoms this is targeted at  RaspiBlitz v1.11.3, correct?

**Comment by openoms** [comment]
> @openoms this is targeted at RaspiBlitz v1.11.3, correct?

yes, the install looks good, but the -modded label will only be fixed in the next release:

Screenshot_20240924-205321~2

>Yes, it happened due to an update in model.rs at compilation. It will be fixed with PR 7683 in v24.08.2
https://t.me/lightningd/34314

Not sure when the next bugix will be tagged, but could merge this for testing and hopefully the fix will make it in by the time v1.11.3 is final.

**Review by rootzoll — APPROVED** [review]
tACK - installs fine. Yes I recommend merge now - test during RCs & if lucky we get a patched version before final release.

**Comment by rootzoll** [comment]
@openoms just to make sure - there were no breaking changes to v24.02.1 that we shipped with "v1.11.0" correct?

**Comment by openoms** [comment]
This check https://github.com/raspiblitz/raspiblitz/pull/4751 broke probably because of the listpeers command output changing, but the changes are backward compatible (works with the previous CLN version too).

**Pull request merged**
