### PR TITLE
electrs fix missing local IP in CONNECT view

### PR DESCRIPTION
**Pull request by ChuckNorrison**
the local ip was not displayed correctly in ELECTRS->CONNECT menu

### CODE REVIEW

**Comment by ChuckNorrison** [comment]
Missing TOR Address is fixed here
https://github.com/rootzoll/raspiblitz/pull/3388

**Comment by rootzoll** [comment]
code change looks good - any reason to base thsi PR on "1.8" instead on dev?

**Comment by ChuckNorrison** [comment]
> code change looks good - any reason to base thsi PR on "1.8" instead on dev?

thought its very small fix without risk to get any functionality broke, so i did it in v1.8. Better use dev, even for small fixes?

**Comment by rootzoll** [comment]
thats fair - non breaking changes can be on active release branch. but if overlooked might be forgotten to be cherry picked into dev branch and so not getting into future versions. Always best to use dev branch for PRs and than note that its also a candidate to be also included in active release branch.

**Comment by rootzoll** [comment]
OK merged into active release branch and cherry-picked into dev. thx.

**Pull request merged**
