### PR TITLE
fix localIP assignment and improve SSD detection

### PR DESCRIPTION
**Pull request by rek79**
**Fix localip assignment**:
use `localip=$(hostname -I | awk '{print $1}')` instead of `localip=$(ip addr | grep 'state UP' -A2 | grep -E -v 'docker0|veth' | grep 'eth0\|wlan0\|enp0' | tail -n1 | awk '{print $2}' | cut -f1 -d'/')`.  The former assignment seems to work on a wider range of hardware.
related: https://github.com/rootzoll/raspiblitz/commit/5d61d0b216b281ff7b99e0488c39390d1d5e038c#commitcomment-89042523

**Improve reliability of solid state drive detection**:
smartctl seems to be more compatible with a wider array of hardware.
`isSSD=$(cat /sys/block/${hdd}/queue/rotational 2>/dev/null | grep -c 0)` incorrectly sets SSD to false for Odroid HC2.  `isSSD=$(sudo smartctl -a /dev/sda | grep 'Rotation Rate' | grep -c "Solid State")` correctly identifies the SSD.
Related issue: https://github.com/rootzoll/raspiblitz/issues/3423#issue-1439092806

### CODE REVIEW

**Comment by rek79** [comment]
@openoms @rootzoll this is follow on work to my related merged PR #2432 under [v1.7.1](https://github.com/rootzoll/raspiblitz/releases/tag/v1.7.1).  The solid state drive fix is not related but included here since it seems to be an improvement for hardware compatibility.  I can separate that out if we think that will take longer to test.  Please let me know.

**Review by ChuckNorrison — COMMENTED** [review]
smartctl: command not found

This needs to be installed

**Comment by rek79** [comment]
@ChuckNorrison check for package "smartmontools" added.  It should work now if not already installed.

**Comment by ChuckNorrison** [comment]
Looks good so far, but what if a device is unsupported by smartmontools like described [here](https://www.smartmontools.org/wiki/Unsupported_USB-Devices)?

Should we preserve the command `cat /sys/block/${hdd}/queue/rotational` as a fallback?

**Comment by rek79** [comment]
Fallback added.  If "Rotation Rate:" is found then` smartctl` method is used to detect the SSD.  Otherwise `cat /sys/block/${hdd}/queue/rotational` is used.
@ChuckNorrison in the link of unsupported devices, it seems that some of those devices still report rotation so this seems to be a robust way forward.  Thanks for the input!

**Comment by rootzoll** [comment]
PR basically looks good for final testing but is based on v1.8 release ... @rek79 could you re-base it on `dev` branch?

**Comment by rek79** [comment]
Opened a new pull request under #3439 which is re-based to `dev` branch.  I'll close this out.

**Pull request closed without merging**
