### PR TITLE
BTCPay Server 1.11.7

### PR DESCRIPTION
**Pull request by rootzoll**

### CODE REVIEW

**Comment by rootzoll** [comment]
Build is failing - pushing to later release:
```
/home/btcpay/dotnet/sdk/6.0.101/NuGet.targets(130,5): error : Failed to download package 'System.Security.Permissions.6.0.0' from 'https://api.nuget.org/v3-flatcontainer/system.security.permissions/6.0.0/system.security.permissions.6.0.0.nupkg'. [/home/btcpay/btcpayserver/BTCPayServer/BTCPayServer.csproj]
/home/btcpay/dotnet/sdk/6.0.101/NuGet.targets(130,5): error : The SSL connection could not be established, see inner exception. [/home/btcpay/btcpayserver/BTCPayServer/BTCPayServer.csproj]
/home/btcpay/dotnet/sdk/6.0.101/NuGet.targets(130,5): error :    Received an unexpected EOF or 0 bytes from the transport stream. [/home/btcpay/btcpayserver/BTCPayServer/BTCPayServer.csproj]
```

**Comment by openoms** [comment]
Tested 1.11.6, works ok and Nicolas is signing again.

Fixes #4000 

rebasing on dev

**Comment by openoms** [comment]
For the record the permission error on amd64 Debian12 before applying the permissions for the schema:
```
Oct 16 08:18:52 raspiblitz-amd64 dotnet[2935036]: info: Configuration:  Supported chains: BTC                                                                                                                                                                                   [385/3163]
Oct 16 08:18:52 raspiblitz-amd64 dotnet[2935036]: info: Configuration:  BTC: Explorer url is http://127.0.0.1:24444/                                                                                                                                                                      
Oct 16 08:18:52 raspiblitz-amd64 dotnet[2935036]: info: Configuration:  BTC: Cookie file is /home/btcpay/.nbxplorer/Main/.cookie                                                                                                                                                          
Oct 16 08:18:52 raspiblitz-amd64 dotnet[2935036]: info: Configuration:  Network: Mainnet                                                                                                                                                                                                  
Oct 16 08:19:02 raspiblitz-amd64 dotnet[2935036]: fail: BTCPayServer.Hosting.MigrationStartupTask: Error on the MigrationStartupTask                                                                                                                                                      
Oct 16 08:19:02 raspiblitz-amd64 dotnet[2935036]: Npgsql.PostgresException (0x80004005): 42501: permission denied for schema public                                                                                                                                                       
Oct 16 08:19:02 raspiblitz-amd64 dotnet[2935036]: POSITION: 14                                                                                                                                                                                                                            
Oct 16 08:19:02 raspiblitz-amd64 dotnet[2935036]:    at Npgsql.Internal.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|215_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)           
Oct 16 08:19:02 raspiblitz-amd64 dotnet[2935036]:    at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)                                                                                                                       
Oct 16 08:19:02 raspiblitz-amd64 dotnet[2935036]:    at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)                                                                                                                  
Oct 16 08:19:02 raspiblitz-amd64 dotnet[2935036]:    at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)                                                                                                                  
Oct 16 08:19:02 raspiblitz-amd64 dotnet[2935036]:    at Npgsql.NpgsqlCommand.ExecuteNonQuery(Boolean async, CancellationToken cancellationToken)                                                                                                                                          
Oct 16 08:19:02 raspiblitz-amd64 dotnet[2935036]:    at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQueryAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)                                                               
Oct 16 08:19:02 raspiblitz-amd64 dotnet[2935036]:    at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQueryAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)                                                               
Oct 16 08:19:02 raspiblitz-amd64 dotnet[2935036]:    at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQueryAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)                                                               
Oct 16 08:19:02 raspiblitz-amd64 dotnet[2935036]:    at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.MigrateAsync(String targetMigration, CancellationToken cancellationToken)                                                                                              
Oct 16 08:19:02 raspiblitz-amd64 dotnet[2935036]:    at BTCPayServer.Hosting.MigrationStartupTask.Migrate(CancellationToken cancellationToken) in /home/btcpay/btcpayserver/BTCPayServer/Hosting/MigrationStartupTask.cs:line 863                                                         
Oct 16 08:19:02 raspiblitz-amd64 dotnet[2935036]:    at BTCPayServer.Hosting.MigrationStartupTask.ExecuteAsync(CancellationToken cancellationToken) in /home/btcpay/btcpayserver/BTCPayServer/Hosting/MigrationStartupTask.cs:line 86                                                     
Oct 16 08:19:02 raspiblitz-amd64 dotnet[2935036]:   Exception data:                                                                                                                                                                                                                       
Oct 16 08:19:02 raspiblitz-amd64 dotnet[2935036]:     Severity: ERROR                                                                                                                                                                                                                     
Oct 16 08:19:02 raspiblitz-amd64 dotnet[2935036]:     SqlState: 42501                                                                                                                                                                                                                     
Oct 16 08:19:02 raspiblitz-amd64 dotnet[2935036]:     MessageText: permission denied for schema public                                                                                                                                                                                    
Oct 16 08:19:02 raspiblitz-amd64 dotnet[2935036]:     Position: 14                                                                                                                                                                                                                        
Oct 16 08:19:02 raspiblitz-amd64 dotnet[2935036]:     File: aclchk.c                                                                                                                                                                                                                      
Oct 16 08:19:02 raspiblitz-amd64 dotnet[2935036]:     Line: 3650                                                                                                                                                                                                                          
Oct 16 08:19:02 raspiblitz-amd64 dotnet[2935036]:     Routine: aclcheck_error                                                                                                                                                                                                             
Oct 16 08:19:02 raspiblitz-amd64 dotnet[2935036]: Unhandled exception. Npgsql.PostgresException (0x80004005): 42501: permission denied for schema public                                                                                                                                  
Oct 16 08:19:02 raspiblitz-amd64 dotnet[2935036]: POSITION: 14                                                                                                                                                                                                                            
Oct 16 08:19:02 raspiblitz-amd64 dotnet[2935036]:    at Npgsql.Internal.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|215_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)           
Oct 16 08:19:02 raspiblitz-amd64 dotnet[2935036]:    at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)                                                                                                                       
Oct 16 08:19:02 raspiblitz-amd64 dotnet[2935036]:    at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)                                                                                                                  
Oct 16 08:19:02 raspiblitz-amd64 dotnet[2935036]:    at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)                                                                                                                  
Oct 16 08:19:02 raspiblitz-amd64 dotnet[2935036]:    at Npgsql.NpgsqlCommand.ExecuteNonQuery(Boolean async, CancellationToken cancellationToken)                                                                                                                                          
Oct 16 08:19:02 raspiblitz-amd64 dotnet[2935036]:    at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQueryAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)                                                               
Oct 16 08:19:02 raspiblitz-amd64 dotnet[2935036]:    at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQueryAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)                                                               
Oct 16 08:19:02 raspiblitz-amd64 dotnet[2935036]:    at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQueryAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)                                                               
Oct 16 08:19:02 raspiblitz-amd64 dotnet[2935036]:    at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.MigrateAsync(String targetMigration, CancellationToken cancellationToken)                                                                                              
Oct 16 08:19:02 raspiblitz-amd64 dotnet[2935036]:    at BTCPayServer.Hosting.MigrationStartupTask.Migrate(CancellationToken cancellationToken) in /home/btcpay/btcpayserver/BTCPayServer/Hosting/MigrationStartupTask.cs:line 863                                                         
Oct 16 08:19:02 raspiblitz-amd64 dotnet[2935036]:    at BTCPayServer.Hosting.MigrationStartupTask.ExecuteAsync(CancellationToken cancellationToken) in /home/btcpay/btcpayserver/BTCPayServer/Hosting/MigrationStartupTask.cs:line 86                                                     
Oct 16 08:19:02 raspiblitz-amd64 dotnet[2935036]:    at Microsoft.AspNetCore.Hosting.WebHostExtensions.StartWithTasksAsync(IWebHost webHost, CancellationToken cancellationToken) in /home/btcpay/btcpayserver/BTCPayServer/Extensions/WebHostExtensions.cs:line 19                       
Oct 16 08:19:02 raspiblitz-amd64 dotnet[2935036]:    at BTCPayServer.Program.Main(String[] args) in /home/btcpay/btcpayserver/BTCPayServer/Program.cs:line 77                                                                                                                             
Oct 16 08:19:02 raspiblitz-amd64 dotnet[2935036]:   Exception data:                                                                                                                                                                                                                       
Oct 16 08:19:02 raspiblitz-amd64 dotnet[2935036]:     Severity: ERROR                                                                                                                                                                                                                     
Oct 16 08:19:02 raspiblitz-amd64 dotnet[2935036]:     SqlState: 42501                                                                                                                                                                                                                     
Oct 16 08:19:02 raspiblitz-amd64 dotnet[2935036]:     MessageText: permission denied for schema public                                                                                                                                                                                    
Oct 16 08:19:02 raspiblitz-amd64 dotnet[2935036]:     Position: 14                                                                                                                                                                                                                        
Oct 16 08:19:02 raspiblitz-amd64 dotnet[2935036]:     File: aclchk.c                                                                                                                                                                                                                      
Oct 16 08:19:02 raspiblitz-amd64 dotnet[2935036]:     Line: 3650                                                                                                                                                                                                                          
Oct 16 08:19:02 raspiblitz-amd64 dotnet[2935036]:     Routine: aclcheck_error                                                                                                                                                                                                             
Oct 16 08:19:02 raspiblitz-amd64 systemd[1]: btcpayserver.service: Main process exited, code=exited, status=134/n/a                                                                                                                                                                       
Oct 16 08:19:02 raspiblitz-amd64 systemd[1]: btcpayserver.service: Failed with result 'exit-code'.                                                                                                                                                                                        
Oct 16 08:19:02 raspiblitz-amd64 systemd[1]: btcpayserver.service: Consumed 7.549s CPU time.                                                                                                                                                                                              
Oct 16 08:19:12 raspiblitz-amd64 systemd[1]: Stopped btcpayserver.service - BtcPayServer daemon.                                                                                                                                                                                          
Oct 16 08:19:12 raspiblitz-amd64 systemd[1]: btcpayserver.service: Consumed 7.549s CPU time.      
```

**Review by openoms — APPROVED** [review]

**Comment by openoms** [comment]
Repeated install test looks good, merging.

**Pull request merged**
