### PR TITLE
electrs update to v0.10.6, fix update check

### PR DESCRIPTION
**Pull request by openoms**
tested ok on amd64

includes the compatibility fix with Bitcoin Core v28.0

### CODE REVIEW

**Comment by rootzoll** [comment]
Lets push all non critical updates now to v1.12.0 so that we dont delay v1.11.3 too long.

**Comment by openoms** [comment]
Would be good to have this in the patch release as running the current electrs version would break if someone updates to BItcoin Core v28.0 and the UPDATE menu option would also not work.

**Comment by rootzoll** [comment]
Ok so we mark it as critical

**Comment by rootzoll** [comment]
@openoms On my Pi5 install failed:

```
Length: 1236 (1.2K) [text/plain]
Saving to: ‘/var/cache/raspiblitz/pgp_keys_romanz.asc’

/var/cache/raspiblitz/pgp_keys_ 100%[====================================================>]   1.21K  --.-KB/s    in 0s

2024-10-08 13:29:14 (29.6 MB/s) - ‘/var/cache/raspiblitz/pgp_keys_romanz.asc’ saved [1236/1236]

# importing key of romanz
gpg: directory '/home/electrs/.gnupg' created
gpg: keybox '/home/electrs/.gnupg/pubring.kbx' created
pub   nistp256 2016-10-29 [SC]
      15C8C3574AE4F1E25F3F35C587CAE5FA46917CBB
uid                      Roman Zeyde <me@romanzey.de>
uid                      Roman Zeyde <roman.zeyde@gmail.com>
sub   nistp256 2016-10-29 [E]

gpg: /home/electrs/.gnupg/trustdb.gpg: trustdb created
gpg: key 87CAE5FA46917CBB: public key "Roman Zeyde <me@romanzey.de>" imported
gpg: Total number processed: 1
gpg:               imported: 1
# running: git verify-commit ea9a924


# goodSignature(0)
# correctKey(0)

# BUILD FAILED --> PGP verification not OK / signature(0) verify(0)
Install failed .. removing again.
```

**Comment by openoms** [comment]
Installing now on v1.11.3rc1, was testing the update before. Basically the release commit is not signed only the tag itself.

**Review by rootzoll — APPROVED** [review]
tACK

**Pull request merged**
