### PR TITLE
add a 'last refresh' line to infoBlitz

### LINKED ISSUE #1161: status display has no date or time on it, data displayed is of unknown freshness
There's no way to know if the status display is current or not.   It could have frozen; a date and time display (with seconds) should be incorporated into the LCD layout.

### PR DESCRIPTION
**Pull request by frennkie**
Fix #1161

The change is pretty simple. I'm just nor sure about the exact wording and placement. Any better ideas?

Updated Proposal:

RPi_RefreshR

Old Proposal

RPi_Refresh

### CODE REVIEW

**Comment by openoms** [comment]
Good idea!
The placement is ok, but would prefer to use a clearer time format eg.:
```
$ date +"%X %F %Z"
09:19:54 2020-09-20 BST
```

**Comment by frennkie** [comment]
Yeah.. let's have that discussion..! :-D 

Seriously.. I agree that the default date string which I use here is pretty verbose. But I would say it also makes it very clear. Day of week (Sat) might also be handy. Writing out the month (Sep) will avoid anybody from ask whether 2020-10-09 is Oct. 9th or Sep. 10th.. ;-)

We could also use `date -R`: `Sun, 20 Sep 2020 10:47:26 +0200`

Anyway - for me the perfect date is definitely ISO-8601 (https://xkcd.com/1179/) ;-P

**Comment by openoms** [comment]
we agree on the perfect date format since that is the only one usable for sorting.

Anyway, verbosity might make it more straighforward as you write. 
I am ok with the default format too.

**Comment by frennkie** [comment]
I changed it to the RFC 5322 (email) format because I find the "distance" between the Day+Month and the Year in the default very awkward (Day, Month, Time, TZ, Year).

**Comment by rootzoll** [comment]
LGTM merging for v1.6.1 release

**Comment by rootzoll** [comment]
fixes #1161

**Comment by rootzoll** [comment]
+cp into v1.6 branch

**Pull request merged**
