### PR TITLE
change ascii art for JoinMarket stats

### PR DESCRIPTION
**Pull request by grnqrtr**
This was my attempt at a simpler ascii art for the JoinMarket stats.
It's just a simple JM underlined with a chain.

joinmarket

### CODE REVIEW

**Comment by openoms** [comment]
Tested, but got an issue on the physical touchscreen.
The xterm does not seem to support the unicode characters.
@frennkie is there an acceptable solution to this?
image

Looks great when the touchscreen is not active:
image

**Comment by holgern** [comment]
The touchscreen uses xterm: https://github.com/rootzoll/raspiblitz/blob/v1.6/home.admin/BlitzTUI/blitztui/main.py#L157 which has a problem with unicode chars:
https://unix.stackexchange.com/questions/196152/xterm-not-displaying-unicode

A fast solution is to replace xterm by uxterm, I will provide a PR.

**Comment by holgern** [comment]
https://github.com/rootzoll/raspiblitz/pull/1614

**Comment by openoms** [comment]
Confirmed to work with https://github.com/rootzoll/raspiblitz/pull/1614
Ready for v1.6.1 @rootzoll

**Comment by rootzoll** [comment]
+cp into dev branch

**Pull request merged**
