### PR TITLE
Bitcoinminds.org to be made available as a service in Raspiblitz

### PR DESCRIPTION
**Pull request by raulcano**
With this PR I would like to enable a new Raspiblitz service to allow any Raspi to host and run fully the BitcoinMinds.org site.
This pull request adds 3 things:
- A bonus script to download the code from the bitcoinminds.org repo https://github.com/raulcano/bitcoinminds
- A menu item to enable and disable this service.
- A command 'bm' to start the server (npm run serve) and make the site available to be visited from the LAN

I leave this PR in draft until I have properly tested it in my Raspiblitz.

image

image

image

image

image

image

### CODE REVIEW

**Comment by raulcano** [comment]
When I try to install the whole thing it gives an error. Looks like node-sass is not supported in ARM .
Not sure if we can do something to fix that.

https://gitmemory.com/issue/sass/node-sass/3141/872608039

**Comment by rootzoll** [comment]
I am not familiar with the node-sass .. so I move this to "future release collector" until somebody finds a solution.

**Comment by raulcano** [comment]
Yes, makes sense. Thanks!

rootzoll ***@***.***> schrieb am Di., 17. Aug. 2021, 11:34:

**Comment by AaronDewes** [comment]
@raulcano You can simply replace `node-sass` by `sass`.

`sass-loader` will recognize it automatically, node-sass is deprecated anyway.

**Comment by raulcano** [comment]
Oh! Interesting! I'll try this in the next days and report back 👍

Aaron Dewes ***@***.***> schrieb am Di., 11. Jan. 2022, 19:07:

**Comment by raulcano** [comment]
Hi @AaronDewes , yes, that worked :) Thanks!
I have submitted a new PR, since merging this one on the current dev branch was kind of a headache.
See #2933

**Pull request closed without merging**
