### PR TITLE
Add commands confirmation message

### PR DESCRIPTION
**Pull request by ChuckNorrison**
for interrupting commands, ask first

### CODE REVIEW

**Comment by rootzoll** [comment]
Please not the `patch` command ... its used in some development flows and always a yes/no confirmation would slow that down.

**Comment by ChuckNorrison** [comment]
> Please not the `patch` command ... its used in some development flows and always a yes/no confirmation would slow that down.

found only the 99updateMenu.sh file who would use the command. Should we change the first parameter from "" to "all" if called from there? Than in _commands.sh we could just check for "" and then print the confirmation message.

// confirmation message for `patch` command removed

**Comment by rootzoll** [comment]
> Than in _commands.sh we could just check for "" and then print the confirmation message.

Yeah that can be a good compromise. If there this no further parameter it wants a confirmation. If there is a second paramter (all, code, ...) it will assume the user knows already and there will be no Y/N to not further interrupt the workflow.

**Review by rootzoll — APPROVED** [review]
tests look good

**Pull request merged**
