### PR TITLE
add clHTTPplugin with Fully noded connection

### PR DESCRIPTION
**Pull request by openoms**
- [x] test install and uninstall
- [x] test provision
- [ ] test connection to Fully Noded

Discussed in: https://github.com/rootzoll/raspiblitz/issues/2579

### CODE REVIEW

**Comment by openoms** [comment]
The installation looks good. Rust and the CL plugin is installed when `LN_CL` is selected in the `MOBILE` menu.
There are now 3 type of connections to Fully Noded (depending on the services running)
Can someone with an iOS device please test the connections? @rootzoll maybe?

- [ ] FN_LND - lndconnect over Tor
- [ ] FN_CL - hidden service to the CL HTTP plugin
- [ ] FN_BTC - hidden service to the bitcoin RPC


Tested all three successfully with:
```
torsocks telnet xxxxxxxxxxx.onion PORT
```
so could be merged if that helps.

**Comment by rootzoll** [comment]
So finally I want to wrapup for a RC3 feature freeze tomorrow (Friday) - do we want to add this PR still for the v1.7.1 or have it for the v1.8.0?

**Comment by openoms** [comment]
@rootzoll I'd like to have this is to test the provision and the connections.

It improves upon the whole Fully Noded connect implementation as the wallet now has the ability to connect bitcoind, LND and CL.
I think it would be confusing to just leave one option (with the original bitcoind) there.

**Comment by rootzoll** [comment]
@openoms  when will it be ready to merge?

**Comment by openoms** [comment]
this is ready to merge just needs an iPhone to test the connections

**Comment by rootzoll** [comment]
merging to be part of RC3

**Pull request merged**
