### PR TITLE
confirmation for reboot and shutdown (issue #1354)

### PR DESCRIPTION
**Pull request by adevoss**
Extra dialog box to confirm reboot or shutdown

### CODE REVIEW

**Review by frennkie — COMMENTED** [review]
This is a modal/two choice dialog. Ever since Windows 95 if have disliked 'Yes' / 'No' buttons.. 

We can do better..! 😜

Can you please make it that the confirm button says what will happen when it is pressed (here reboot or shutdown)?

**Comment by adevoss** [comment]
Sure.
My point to make this pr is to prevent accidentally shutdown the Pi. What buttons or text there should be is only about preference.

Made it general for reuse. Try to keep it that way. I'll change the text.
Or do you mean there should be three buttons (Shutdown/Reboot/Cancel)? Then the main menu has one option less.

**Comment by rootzoll** [comment]
Thanks. Will be part of v1.6 final release.

**Comment by rootzoll** [comment]
OK tested and worked :)

**Pull request merged**
