### PR TITLE
JoinMarket Web UI: Verify updates

### PR DESCRIPTION
**Pull request by dennisreimann**
Building on #3005 this adds updates via git and verification of commits to those updates.

### CODE REVIEW

**Comment by openoms** [comment]
does this mean you will continue with the GitFlow signatures?
didn't change the update deliberately to avoid breaking as the the future keys might change depending on the discussion here: https://github.com/joinmarket-webui/joinmarket-webui/issues/142

**Comment by dennisreimann** [comment]
Good point, let's wait for the decision there and see how to fit it in.

**Comment by ghost** [comment]
An update on this: 

Starting with the most recent release ([v0.0.6](https://github.com/joinmarket-webui/joinmarket-webui/releases/tag/v0.0.6)), tags will be signed by @dergigi using this key: [dergigi.com/pgp](https://dergigi.com/pgp/).

See https://github.com/joinmarket-webui/joinmarket-webui/issues/142.

**Comment by dergigi** [comment]
Any update on this? Let me know if I can help in any way.

**Comment by dennisreimann** [comment]
@dergigi I think it's best to start anew here, because I don't know the current state of the developments, so feel free to close this one and submit a new PR.

**Comment by rootzoll** [comment]
Closing this PR on old v1.7 code base. Please open a new PR based on `dev` branch.

**Comment by openoms** [comment]
Ok PGP verification with Gigi's key tested ok and will be part of #3321 

image

**Pull request closed without merging**
