### PR TITLE
Add packages to install-script

### PR DESCRIPTION
**Pull request by adevoss**
Package is needed for formatting datadrive

### CODE REVIEW

**Comment by rootzoll** [comment]
As this is a change to the `build.sh` file ... this would either wait for the next major release v1.7 or if needed to fix a bug adding the install into the `datadrive` script to make sure dependency is getting installed before use.

**Comment by adevoss** [comment]
Think there is no need to rush this pr. It is needed for formatting. Simple to do manually.
I don't know if it is part of standard Raspbian install. It was not installed when I installed Debian without GUI.

My preference would be build_sdcard.sh script because there is where all the other packages are installed/removed.

**Comment by rootzoll** [comment]
> Think there is no need to rush this pr. It is needed for formatting. Simple to do manually.

then moving to v1.7 milestone

**Comment by rootzoll** [comment]
With the emergency update of LND we needed to change the sd card build - so adding this also to fix BTRFS.

**Pull request merged**
