### PR TITLE
lnbits: add dedicated user 

### PR DESCRIPTION
**Pull request by openoms**
- added modifications to use a non-sudo separate user `lnbits`
- fixed typo in menu

### CODE REVIEW

**Comment by openoms** [comment]
Tested successfully on 1.5RC1.

**Comment by frennkie** [comment]
@openoms as @arcbtc asked in https://github.com/rootzoll/raspiblitz/pull/1135#issuecomment-620529351. Do you have the macaroons as a hex string in the `.env` file now (instead of a file path)? If so - then how should this work when `LNbits` can only use a file path currently for gRPC...

**Comment by openoms** [comment]
@frennkie 
no, actually the .env does  not even have the macaroons since there is only a `sed -i` to put them an the variables are not even there yet.
```
admin@raspberrypi:~ $ sudo cat /home/lnbits/lnbits/.env
FLASK_APP=lnbits
FLASK_ENV=production
LNBITS_BACKEND_WALLET_CLASS=LndWallet
LND_GRPC_ENDPOINT=127.0.0.1
LND_GRPC_PORT=10009
LNBITS_FORCE_HTTPS=0
```

are you saying we would need to copy the macaroon for the new user anyway?

**Comment by openoms** [comment]
indeed it is looking for the files:
image
image
```
Apr 28 12:57:13 raspberrypi sh[25790]: Could not find macaroon in /home/lnbits/.lnd/data/chain/bitcoin/mainnet/admin.macaroon. This might happenin versions of lnd < v0.5-beta or those not using defaultinsta
```

**Comment by arcbtc** [comment]
lnd_rpc needs file paths, which was the original concern @frennkie had. 
I have been trying to find a way to pretend the hex strings are file path objects in the lndrpc LNbits funding source, as I know there is limited access to the macaroons outside of lnd in the blitz. 
So far I have had no luck :( 
https://github.com/lnbits/lnbits/blob/master/lnbits/wallets/lndgrpc.py

**Comment by frennkie** [comment]
I think it might make sense to open an issue with the ln rpc author so that they accept either hex bytes or a file path. The alternative would be to not use ln rpc..

**Comment by arcbtc** [comment]
Back to REST it is! Unless we can just use the file paths. If we are able to set the macaroons as hex strings in env/as vars, what's the difference to allowing LNbits access to the macaroon files? 

Isnt LNbits using a user anyway? 
Its just the difference between reading the macaroons in the install and reading them on demand

**Comment by openoms** [comment]
I have added to copy the macaroons to `/home/lnbits/.lnd/`.
It works now with the separate user.

Will need to include this in the refactor of macaroon access: https://github.com/rootzoll/raspiblitz/issues/1143

**Comment by frennkie** [comment]
Shouldn't this script run `source /mnt/hdd/raspiblitz.conf` somewhere at the top?

I just pulled your branch and ran it on the console and $network and $chain are empty.

**Comment by rootzoll** [comment]
@frennkie merged and added loading raspiblitz.conf

**Pull request merged**
