### PR TITLE
Correct typo

### PR DESCRIPTION
**Pull request by pretyflaco**
Update 00settingsMenuServices.sh

Typo 'Cryptoadvance' in lines 83, 104

### CODE REVIEW

**Comment by frennkie** [comment]
@pretyflaco 137 commits and 40 files changed..? Can you please review 1) into which branch you would like this to be merged and 2) what you actually want to change/improve.

**Comment by pretyflaco** [comment]
> @pretyflaco 137 commits and 40 files changed..? Can you please review 1) into which branch you would like this to be merged and 2) what you actually want to change/improve.

Oops :) 1st pull request, sorry
I wanted to correct 2 typos in branch v1.5 00settingsMenuServices.sh

**Comment by frennkie** [comment]
No worries.. go to the PR, click edit next to the title an change the destination branch.

**Comment by rootzoll** [comment]
@pretyflaco Much thanks :) ... merging.

**Pull request merged**
