### PR TITLE
Update RTL and Loop

### PR DESCRIPTION
**Pull request by openoms**
RTL update: https://github.com/rootzoll/raspiblitz/issues/1085
Loop update: https://github.com/rootzoll/raspiblitz/issues/1082

+ improved handling of the RTL config file.

### CODE REVIEW

**Comment by openoms** [comment]
Update to test:
```
cd /home/admin/raspiblitz
git remote set-url origin https://github.com/openoms/raspiblitz.git
/home/admin/XXsyncScripts.sh RTLv0.7.0Loop -clean
# repeat to update
/home/admin/XXsyncScripts.sh RTLv0.7.0Loop -clean
# reinstall LOOP and RTL from the service menu or run:
/home/admin/config.scripts/bonus.loop.sh off
/home/admin/config.scripts/bonus.loop.sh on
/home/admin/config.scripts/bonus.rtl.sh off
/home/admin/config.scripts/bonus.rtl.sh on
sudo systemctl start loopd
sudo systemctl start RTL
```

**Comment by bitsam** [comment]
> Update to test:
> 
> ```
> cd /home/admin/raspiblitz
> git remote set-url origin https://github.com/openoms/raspiblitz.git
> /home/admin/XXsyncScripts.sh RTLv0.7.0Loop -clean
> # repeat to update
> /home/admin/XXsyncScripts.sh RTLv0.7.0Loop -clean
> # reinstall LOOP and RTL from the service menu or run:
> /home/admin/config.scripts/bonus.loop.sh off
> /home/admin/config.scripts/bonus.loop.sh on
> /home/admin/config.scripts/bonus.rtl.sh off
> /home/admin/config.scripts/bonus.rtl.sh on
> sudo systemctl start loopd
> sudo systemctl start RTL
> ```

Have you made a similar script to upgrade from RTL 7.0 to RTL 8.1 or 8.2. I tried to upgrade to RTL 8.2 based on main RTL github, however after a reboot RTL is still running 7.0.

**Comment by bitsam** [comment]
I also tried disabling it and re-enabling it under the Raspiblitz Services menu, and it looked like it was requesting the latest version. However, still running RTL 7.0

**Comment by rootzoll** [comment]
@bitsam RTL 0.8.1 will come with RaspiBlitz v1.6 (final release soon) ... is there any reason you would not update to that new version?

**Pull request merged**
