### PR TITLE
Added lightning forwarding event report

### PR DESCRIPTION
**Pull request by ghost**
Scripts to generate an LND forwarding report with channel id's resolved to node aliases

### CODE REVIEW

**Review by openoms — APPROVED** [review]
Thanks this is working great!

On armbian I needed to install `bsdmainutils` to get `column`, so let`s add that to the dependencies in build_sdcard.sh.

Otherwise happy to have this @rootzoll

**Comment by ghost** [comment]
> On armbian I needed to install `bsdmainutils` to get `column`, so let`s add that to the dependencies in build_sdcard.sh.

Done.

**Review by openoms — APPROVED** [review]
Raspbian has bsdmainutils packed already so this is looks good to me.

**Comment by openoms** [comment]
@rootzoll this one is not controversial, gives a nice menu entry to check LN forwarding events.
Shall we include in the final tests?

**Comment by frennkie** [comment]
LGTM

**Pull request merged**
