### PR TITLE
#2400 adjust command prompt

### PR DESCRIPTION
**Pull request by rsauerwein**
I solved issue #2400 by overriding the defaults $PS1 value in .bashrc. Is my solution fine or do I have to tackle the issue in a different way? Thanks for your feedback.

### CODE REVIEW

**Comment by frennkie** [comment]
You changed the color intentionally, right? (would be completely ok for me)

Did you also intentionally remove the @raspberrypi part? (would be - mostly- ok for me)

Before

image


After

image

But I really like the general idea..! ;-D

**Comment by frennkie** [comment]
I do have a concern that this **might** "break" some default system behavior for when no colors are used (non-interactive stuff - e.g. using bash completion from a remote ssh/scp session). 

An alternative approach would be to clone the existing lines and make your modifications there:

```
# raspiblitz #2651
if ! grep -Eq "^[[:space:]]*PS1.*₿" /home/admin/.bashrc; then
    sed -i '/^unset color_prompt force_color_prompt$/i # raspiblitz custom command prompt https://github.com/rootzoll/raspiblitz/issues/2400' /home/admin/.bashrc
    sed -i '/^unset color_prompt force_color_prompt$/i if [ "$color_prompt" = yes ]; then' /home/admin/.bashrc
    sed -i '/^unset color_prompt force_color_prompt$/i \    PS1=\x27${debian_chroot:+($debian_chroot)}\\[\\033[00;33m\\]\\u \\[\\033[00;34m\\]\\w \\[\\033[01;33m\\]₿\\[\\033[00m\\] \x27' /home/admin/.bashrc
    sed -i '/^unset color_prompt force_color_prompt$/i else' /home/admin/.bashrc
    sed -i '/^unset color_prompt force_color_prompt$/i \    PS1=\x27${debian_chroot:+($debian_chroot)}\\u@\\h:\\w₿ \x27' /home/admin/.bashrc
    sed -i '/^unset color_prompt force_color_prompt$/i fi' /home/admin/.bashrc
fi
```

image

But I would prefer:

```
# raspiblitz #2651
if ! grep -Eq "^[[:space:]]*PS1.*₿" /home/admin/.bashrc; then
    sed -i '/^unset color_prompt force_color_prompt$/i # raspiblitz custom command prompt https://github.com/rootzoll/raspiblitz/issues/2400' /home/admin/.bashrc
    sed -i '/^unset color_prompt force_color_prompt$/i if [ "$color_prompt" = yes ]; then' /home/admin/.bashrc
    sed -i '/^unset color_prompt force_color_prompt$/i \    PS1=\x27${debian_chroot:+($debian_chroot)}\\[\\033[00;33m\\]\\u@\\h:\\[\\033[00;34m\\]\\w \\[\\033[01;33m\\]₿\\[\\033[00m\\] \x27' /home/admin/.bashrc
    sed -i '/^unset color_prompt force_color_prompt$/i else' /home/admin/.bashrc
    sed -i '/^unset color_prompt force_color_prompt$/i \    PS1=\x27${debian_chroot:+($debian_chroot)}\\u@\\h:\\w₿ \x27' /home/admin/.bashrc
    sed -i '/^unset color_prompt force_color_prompt$/i fi' /home/admin/.bashrc
fi
```

image

**Comment by rsauerwein** [comment]
Thanks for your feedback. 

About your questions:

- Of course I had no intentions to hide the hostname (raspberrypi) from the shell. So thanks for mentioning that :)
- About the colors - I adopted them from [the Raspibolt guide](https://stadicus.github.io/RaspiBolt/raspibolt_62_commandline.html) and liked them. That's how the shell looks in my KDE environment:
 
konsole
Pretty Fullnode Shell in my opinion ;O

Also thanks for your feedback. You are right, it's safer to stick with the default system behavior. I'll modify my Pull Request.

**Comment by frennkie** [comment]
I agree that your colors look much nicer (and not as uninspired as the default).

**Comment by rsauerwein** [comment]
I just adjusted and tested my PR according to frennkie`s feedback and snippets, which btw helped me a lot to learn about sed - thanks again. For now that's the new command line draft:

thebitcoinstandardshell

**Comment by nyxnor** [comment]
Could you also add git branch on the ps1 to the same PR?
image

```sh
PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[01;35m\]$(__git_ps1 "(%s)")\[\033[01;33m\]₿\[\033[00m\] '
```
This is more useful on other services cloned than this folder, which is just an example.

**Comment by rsauerwein** [comment]
Sure, good idea

New draft:
adjustedPS1

**Comment by openoms** [comment]
what do you think about dropping the hostname (which is kept generic for privacy reasons) and put the LAN IP address after the username which would help identifying the terminal on networks where multiple nodes are running?

**Comment by rsauerwein** [comment]
I replaced the hostname with the IP address:

ps1withip

To determine the IP, I use the output from `hostname -I`.

**Comment by openoms** [comment]
That's useful I think.
`hostname -I` was the most reliable way to get the IP which I tested as well in various environment.
If it is thought to be too long could cut it to the last number, but that would probably introduce some confusion.

Like it as it is and nice idea about the branch name @nyxnor !

**Pull request merged**
