### PR TITLE
Remove white spaces

### PR DESCRIPTION
**Pull request by openoms**
Only cosmetic changes, should not change any functionality, but PR-d to `dev` as many files are affected.

Was simply using:
```
find . -type f -name '*.py' -exec sed --in-place 's/[[:space:]]\+$//' {} \+
find . -type f -name '*.sh' -exec sed --in-place 's/[[:space:]]\+$//' {} \+
```

### CODE REVIEW

**Comment by rootzoll** [comment]
We have quite some PRs waiting for v1.8 ... adding such massive cosmetic changes might break lots of them. Not sure its worse to do.

**Comment by openoms** [comment]
Not a priority indeed, Will draft it indefinitely and wait for a time with less conflicts.

**Comment by YBHQ** [comment]
#

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by openoms** [comment]
Going forward we should encourag to use shellcheck and be stricter about formatting. Maybe a formatting github action could help all new PRs.

**Pull request closed without merging**
