### PR TITLE
Update lnd 0.17.5 & recommended bitcoin update 27.0

### PR DESCRIPTION
**Pull request by rootzoll**
adresses: #4551

### CODE REVIEW

**Comment by rootzoll** [comment]
OK I tested:
- Do a "recommended Bitcoin update to 27.0" - worked OK
- Did a minimal image sd card recovery provisioned with these scripts and it recovered OK to Bitcoin 27.0.
- Then installed lnd and it installed lnd 0.17.5 OK
... recommend merging.

**Comment by openoms** [comment]
was using LND 0.17.5 all right, but now LND v0.18.0 is out. Updated ok.

**Comment by rootzoll** [comment]
I would not add lnd 0.18.0 as default yet (never go with a .0 ;) .. lnd 018.x is a good candidate for RaspiBlitz v1.12.0

**Comment by openoms** [comment]
Agreed.

**Pull request merged**
