### PR TITLE
Complete kitlist for BTC

### PR DESCRIPTION
**Pull request by we-do-it-lu**
I don't have any stake with ShopInBits although I know the guys; I find it odd/unacceptable that Raspiblitz even suggests to buy from an Amazon whereas circular economy is key in BTC adoption.

### CODE REVIEW

**Comment by openoms** [comment]
Checking the link I have concerns with the parts offered:
- the SDcard is not the Endurance model (there is difference)
- not sure about the USB-disk adapter offered. Did anyone test it?

**Comment by we-do-it-lu** [comment]
Hi Openoms, checking this out, will revert as soon as I can.

**Comment by we-do-it-lu** [comment]
A. Lando (ShopInBits) tells me he got this validated by lightrider @Fulmo // I understand the SD card topic is touchy (I had issues myself with "cheaper" SD cards - I will recommend to him what you told me (and is what is in the kitlist of Raspiblitz on GitHub), suggest to update is kitlist accordingly.
B. The USB-disk adapter has been tested positively by Lando himself. 
Thank you openoms.

**Comment by we-do-it-lu** [comment]
A. Resolved: Lando managed to get good deals on Endurence SD card, the link has not changed but the product, description and photo of the pack have been updated accordingly -> https://shopinbit.com/en/concierge-service/361498/raspiblitz-kit
B. Confirmed 100% it works.

**Comment by openoms** [comment]
Looking good, ACK from me.

**Comment by rootzoll** [comment]
@Animalmother9000 can you take a second look at the PR/Shoppinglist?

**Comment by rootzoll** [comment]
The link to ShopInBits seemed to have been a time limited thing ... it now says "This BITDROP is over and was successful!".

**Pull request closed without merging**
