### PR TITLE
Fix white screen

### PR DESCRIPTION
**Pull request by frennkie**
After updating v1.6 to a newer kernel (running `apt-get upgrade`) my screen stayed white.

This fixes it for the newer kernel. Might not work on the old kernel.

### CODE REVIEW

**Comment by ChuckNorrison** [comment]
i got this working on my system manually with that referenced repo. i played a lot with the common way, ended up copiying the code to a script and after the reboot i just have to enter `lcd` and wait for the reboot.

Here are the parts which worked

```
#!/bin/bash
echo "*** LCD DRIVER ***"
echo "--> Downloading LCD Driver from Github"
cd /home/admin
sudo -u admin git clone https://github.com/MrYacha/LCD-show.git
sudo -u admin chmod -R 755 LCD-show
sudo -u admin chown -R admin:admin LCD-show
cd LCD-show/
# set comit hard to old version - that seemed to run better
#
#sudo -u admin git reset --hard ce52014

# install xinput calibrator package
echo "--> install xinput calibrator package"  
sudo apt install -y libxi6 
sudo dpkg -i xinput-calibrator_0.7.5-1_armhf.deb                                  
                                                                                    

sudo sed -i 's/^lcd2hdmi=.*/lcd2hdmi=on/g' /home/admin/raspiblitz.info 2>/dev/null
sudo sed -i 's/^lcd2hdmi=.*/lcd2hdmi=on/g' /mnt/hdd/raspiblitz.conf 2>/dev/null
cd /home/admin/LCD-show
./LCD-hdmi
```

After reboot i have to execute `lcd`. now my screen is back :+1: 

// the last line should be working with ./LCD35-show, but i got it not working this way.

**Comment by rootzoll** [comment]
Its a bit more complicated if we want to include the fix into the v1.6.1 ... because the base image will stay the same for such a service release. This PR is more for a v1.7 release ... but that might a bit long for people wanna upgrade their kernel.

So I will take parts of this PR and also scripts from @ChuckNorrison and turn this into a solution that RaspiBlitz will check on boot time if kernel has been updated and then might correct the LCD driver. This should then worl for the v1.6.1

**Comment by rootzoll** [comment]
closing this PR because I needed to fix this with more detail - but used parts of this PR. See: 
https://github.com/rootzoll/raspiblitz/issues/1436#issuecomment-685847430

**Comment by frennkie** [comment]
@rootzoll this is really confusing..! Please use PRs for the things you do too!

**Pull request closed without merging**
