### PR TITLE
CLN to cl

### PR DESCRIPTION
**Pull request by openoms**
Big change renaming all `cln` / `CLN` to `cl` / `CL` except `CLNETWORK`

feels fairly safe this way (would be much more problematic the other way around)

will test regardless

Simply reacting to a discussion on the cl-lightning Telegram making sense. See the poll: https://t.me/lightningd/7528

### CODE REVIEW

**Comment by openoms** [comment]
The aliases and raspiblitz.conf entries can be manually modified by the early testers.

```
# fix the configs before installing a new SDcard
sed -i 's/cln/cl/g' _aliases
sudo sed -i 's/cln/cl/g' /mnt/hdd/raspiblitz.conf

sudo sed -i 's/cln/cl/g' /home/bitcoin/.lightning/config 
sudo sed -i 's/cln/cl/g' /home/bitcoin/.lightning/testnet/config 
sudo sed -i 's/cln/cl/g' /home/bitcoin/.lightning/signet/config 

# fix to continue to use the current image (v1.7.1rc2)
sudo mv /home/bitcoin/cln-plugins-available /home/bitcoin/cl-plugins-available
sudo mv /home/bitcoin/cln-plugins-enabled /home/bitcoin/cl-plugins-enabled
sudo mv /home/bitcoin/tcln-plugins-enabled /home/bitcoin/tcl-plugins-enabled
sudo mv /home/bitcoin/scln-plugins-enabled /home/bitcoin/scl-plugins-enabled

sudo sed -i 's/cln/cl/g'  /etc/systemd/system/lightningd.service
sudo sed -i 's/cln/cl/g'  /etc/systemd/system/tlightningd.service
sudo sed -i 's/cln/cl/g'  /etc/systemd/system/slightningd.service

restart
```

**Comment by nyxnor** [comment]
Oh boy, and I thought s/TOR/Tor was a difficult task to not break things.

the files names also?
https://github.com/openoms/raspiblitz/blob/CLNtoCL/home.admin/config.scripts/.cln-plugin.spark.sh

**Comment by openoms** [comment]
> Oh boy, and I thought s/TOR/Tor was a difficult task to not break things.
> 
> the files names also?
> https://github.com/openoms/raspiblitz/blob/CLNtoCL/home.admin/config.scripts/.cln-plugin.spark.sh

thanks, that file is WIP still, removed

**Comment by openoms** [comment]
tests look good so merging

**Comment by rootzoll** [comment]
I am removing that part in prep for a v1.7.2 release because v1.7.1 should already have that changed and it might cause side effect is in the futue

**Pull request merged**
