### PR TITLE
sphinxrelay: fix update option

### PR DESCRIPTION
**Pull request by openoms**
as in: https://github.com/rootzoll/raspiblitz/issues/1758#issuecomment-734513624

### CODE REVIEW

**Comment by rootzoll** [comment]
I think we worked on the same thing the same time - this should be fixed already in v1.6 branch - please check.

**Comment by rootzoll** [comment]
@openoms ah OK the config overwrite could be a think still on my impelementation. Please rebase again against my latest merge.

**Comment by openoms** [comment]
> I think we worked on the same thing the same time - this should be fixed already in v1.6 branch - please check.

yes I've seen and I have also started with the same update method. 
Tested this to update from v1.1.0 to v1.1.1 and worked ok. 
It is based on the latest commit.

**Comment by rootzoll** [comment]
Ah thats clever to use the git stash to preserve config .. will merge much thx.

**Pull request merged**
