### PR TITLE
adding helipad as a service

### PR DESCRIPTION
**Pull request by SpencerPearson**
This is my rough draft of a branch adding Helipad to Raspiblitz services menu! I am sure I'm probably missing some things and am happy to add or edit what is needed, but the on and off in my config script seem to be working so far. Any feedback is welcome and appreciated!

### CODE REVIEW

**Comment by valcanobacon** [comment]
I have used this and it does indeed work. I think it needs https setup.

**Comment by rootzoll** [comment]
Looks good for a first integration :) Let me know when ready for testing.

**Comment by SpencerPearson** [comment]
@rootzoll any tips for proper https configuration? what should I be getting in place before I make this ready for testing? I added the update argument to the config script but I haven't quite cracked the whole tor/ssl/tor_ssl part yet...are there any good pointers for how to write the proper nginx for it somewhere?

**Comment by rootzoll** [comment]
> @rootzoll any tips for proper https configuration?

Basically you just need to create those three configuration files for nginx for `ssl, tor & tor+ssl` in the `/home.admin/assets/nginx/sites-available` folder. Take `thub_ssl.conf` and the related as a template. Basically all should proxy to the local http service.

Then in your install script .. make sure those assets get copied over to the `/etc/nginx/sites-available` directory (use sudo) and get linked into the `/etc/nginx/sites-enabled` directory. Restart nginx and make sure ports get opened on the `ufw` firewall. As an example see here: https://github.com/rootzoll/raspiblitz/blob/eb66ab1b77592b04bb418fe1c00e97fa6289d749/home.admin/config.scripts/bonus.thunderhub.sh#L184

On deinstall make sure to delete those assets in `/etc/nginx/sites-available` like done here:
https://github.com/rootzoll/raspiblitz/blob/eb66ab1b77592b04bb418fe1c00e97fa6289d749/home.admin/config.scripts/bonus.thunderhub.sh#L276

**Comment by adevoss** [comment]
If I'm not mistaken helipad uses lnd so maybe best to add that in the readme for people who use c-lightning.

**Comment by SpencerPearson** [comment]
Ok the nginx conf files have been added, as have the install/uninstall rules, so I'm going to flag it ready for review @rootzoll 
cc @valcanobacon and @adevoss also

**Comment by SpencerPearson** [comment]
sorry about the last 2 commits I wanted to get gpg configured for the final commit

**Comment by rootzoll** [comment]
OK this looks good - will include this as a last minute addition to the v1.7.2 release :)

**Pull request merged**
