### PR TITLE
print debug logs and blitz help on terminal

### PR DESCRIPTION
**Pull request by nyxnor**
https://github.com/rootzoll/raspiblitz/issues/2012
print debug logs fully and link option. Raspiblitz help menu

Hope this pull comes without another 999 pulls...

### CODE REVIEW

**Comment by openoms** [comment]
good idea, but couple of notes:

lndmanage (`manage`) will be not included in the GUI in 1.7
the users `loop`, `pool` and `faraday` will be deprecated and the install scripts to be left CLI only as well because all their interfaces will be the part of the `lit` user.

**Comment by rootzoll** [comment]
I also like having a help menu for the commands ... I mark this for v1.7.1

**Comment by nyxnor** [comment]
@openoms `manage` wont be on the gui. So should I exclude from this help menu as one just will get to it through command line?

**Comment by openoms** [comment]
yes, since lndmanage is not supported currently (hopefully temporarily) I suggest to no put it into the help text either (same with the separate loop, pool and faraday)

**Pull request merged**
