### PR TITLE
Fix lndmanage

### PR DESCRIPTION
**Pull request by frennkie**
The `cd lndmanage` caused an issue during my restore.. I assume the directory had not been reset from a previous script.

### CODE REVIEW

**Comment by openoms** [comment]
this happened to me in couple of scripts as I was tetsing and running the scripts with the `admin` user from the `00settingMenu.sh` but the restore script is run with sudo.

Other way is to make sure it the bonus.lndmanage.sh is run everywhere with `sudo -u admin`.

Thanks for fixing!

**Comment by rootzoll** [comment]
With the fixes its now not working anymore when I try to install from service menu. I will change back until its working and try the ´sudo -u admin´ in the provision.

**Comment by rootzoll** [comment]
OK. Install from service menu is now working again ... but running lndmanage I get this error - could this be python3 related?
Bildschirmfoto 2020-01-20 um 23 19 26

**Comment by rootzoll** [comment]
Trying if lndmanage is working during update/recovery now.

**Comment by rootzoll** [comment]
OK now LNDMANAGE is also getting installed during recovery. But still when running LNDMANAGE I get that error like above.

**Pull request merged**
