### PR TITLE
specter: update to v0.8.0

### PR DESCRIPTION
**Pull request by openoms**
Updated + added short comments to HWW udev rules
Related:
https://github.com/rootzoll/raspiblitz/issues/1411

### CODE REVIEW

**Comment by rootzoll** [comment]
+cp into dev branch

**Comment by ChuckNorrison** [comment]
result after update and login specter from current version:
```
Server error!
Exception: 'cryptoadvance.specter.specter.Specter object' has no attribute 'network_info'
```
Opened issue on cryptoadvance specter
https://github.com/cryptoadvance/specter-desktop/issues/446

**Comment by openoms** [comment]
@ChuckNorrison did you install the extra dependencies before updating as described here: https://github.com/rootzoll/raspiblitz/issues/1411#issuecomment-696565570?

Try reinstalling after running this:
`sudo apt install -y libffi-dev`

**Comment by ChuckNorrison** [comment]
`libffi-dev is already the newest version (3.2.1-9).`

i uninstalled manually and reinstalled from services menu as described in #1411, works for me.

**Pull request merged**
