### PR TITLE
fix: remove lnbits user when off, improve checks

### PR DESCRIPTION
**Pull request by openoms**
fixes: #3794 and other reported issues when updating

### CODE REVIEW

**Comment by openoms** [comment]
Download this updated script to update lnbits to v0.10.5:
```
# download the script in place
wget -O config.scripts/bonus.lnbits.sh https://raw.githubusercontent.com/rootzoll/raspiblitz/dev/home.admin/config.scripts/bonus.lnbits.sh

# uninstall old version while keeping data
config.scripts/bonus.lnbits.sh off --keep-data

# install lnbits v0.10.5
config.scripts/bonus.lnbits.sh on
```

Edit: since merged the latest version is in the `dev` branch, Edited the link above.

**Comment by kravens** [comment]
I tried the steps above, this is the error I run into next (0.19rc4):
```May 06 20:28:23 raspberrypi systemd[1]: Started lnbits.
May 06 20:28:28 raspberrypi sh[1234646]: Traceback (most recent call last):
May 06 20:28:28 raspberrypi sh[1234646]:   File "<string>", line 1, in <module>
May 06 20:28:28 raspberrypi sh[1234646]:   File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
May 06 20:28:28 raspberrypi sh[1234646]:     return _bootstrap._gcd_import(name[level:], package, level)
May 06 20:28:28 raspberrypi sh[1234646]:   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
May 06 20:28:28 raspberrypi sh[1234646]:   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
May 06 20:28:28 raspberrypi sh[1234646]:   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
May 06 20:28:28 raspberrypi sh[1234646]:   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
May 06 20:28:28 raspberrypi sh[1234646]:   File "<frozen importlib._bootstrap_external>", line 790, in exec_module
May 06 20:28:28 raspberrypi sh[1234646]:   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
May 06 20:28:28 raspberrypi sh[1234646]:   File "/home/lnbits/lnbits/lnbits/server.py", line 11, in <module>
May 06 20:28:28 raspberrypi sh[1234646]:     from lnbits.settings import set_cli_settings, settings
May 06 20:28:28 raspberrypi sh[1234646]:   File "/home/lnbits/lnbits/lnbits/settings.py", line 10, in <module>
May 06 20:28:28 raspberrypi sh[1234646]:     import httpx
May 06 20:28:28 raspberrypi sh[1234646]: ModuleNotFoundError: No module named 'httpx'
May 06 20:28:28 raspberrypi systemd[1]: lnbits.service: Main process exited, code=exited, status=1/FAILURE
May 06 20:28:28 raspberrypi systemd[1]: lnbits.service: Failed with result 'exit-code'.
May 06 20:28:28 raspberrypi systemd[1]: lnbits.service: Consumed 4.400s CPU time.```

**Comment by openoms** [comment]
on rc4 you would have lnbits 0.10.5 already? Was that you were starting with and just tested the scrip to reinstall?

do you have a poetry under the lnbits user or only in `/usr/local/bin/`?

**Comment by kravens** [comment]
I started with 0.10.4.1 I believe, and indeed tested the script to reinstall 0.10.5 again.
Poetry is not under the lnbits user I believe, only on admin account.

**Comment by openoms** [comment]
it shouldn't be admin,but installed with root.
What does
`which poetry`
show?

I also got:
```
# *** INSTALL LNBITS 0.10.5 ***                                                           
*** Add the 'lnbits' user ***                
Adding user `lnbits' ...   
Adding new group `lnbits' (1004) ...
Adding new user `lnbits' (1004) with group `lnbits' ...                                   
Creating home directory `/home/lnbits' ...
Copying files from `/etc/skel' ...  
# get the github code user(lnbits) branch(0.10.5)                                         
Cloning into 'lnbits'...                                                                  
remote: Enumerating objects: 46619, done.    
remote: Counting objects: 100% (767/767), done.
remote: Compressing objects: 100% (346/346), done.            
remote: Total 46619 (delta 512), reused 629 (delta 420), pack-reused 45852                
Receiving objects: 100% (46619/46619), 29.24 MiB | 2.49 MiB/s, done.                      
Resolving deltas: 100% (33045/33045), done.                                               
Note: switching to '0.10.5'.
                                                                                          
You are in 'detached HEAD' state. You can look around, make experimental                  
changes and commit them, and you can discard any commits you make in this                 
state without impacting any branches by switching back to a branch.                       
                                                                                          
If you want to create a new branch to retain commits you create, you may                  
do so (now or later) by using -c with the switch command. Example:                        
                                             
  git switch -c <new-branch-name>
                                             
Or undo this operation with:
                                                                                          
  git switch -                                                                            
                                             
Turn off this advice by setting config variable advice.detachedHead to false              

HEAD is now at 3c92ef29 FIX: #1661 (#1663)
# installing application dependencies
/usr/local/bin/poetry
Creating virtualenv lnbits-Me3QFGJB-py3.9 in /home/lnbits/.cache/pypoetry/virtualenvs

No module named 'virtualenv.activation.xonsh' 
# running with default lightning as funing source: lnd
# preparing env file
# install database: SQLite
# Running: 'bonus.lnbits.sh switch lnd'
## bonus.lnbits.sh switch lnd
```
so it is not consistent :/


Edit: 
this was solved by running:
`sudo pip uninstall virtualenv`
and resinstalling poetry
looks like an edge case

**Comment by kravens** [comment]
```
admin@192.168.1.xx:~ ₿ which poetry
/home/admin/.local/bin/poetry
admin@192.168.1.xx:~ ₿ sudo su root
root@raspberrypi:/home/admin# which poetry
/usr/local/bin/poetry
```

This is what I get for poetry under each account. After installing again using the root account I see:

```
# Running: 'bonus.lnbits.sh on'
# Installing code base & dependencies first ..
# Running: 'bonus.lnbits.sh install'
# *** INSTALL LNBITS 0.10.5 ***
*** Add the 'lnbits' user ***
Adding user `lnbits' ...
Adding new group `lnbits' (1018) ...
Adding new user `lnbits' (1018) with group `lnbits' ...
Creating home directory `/home/lnbits' ...
Copying files from `/etc/skel' ...
# get the github code user(lnbits) branch(0.10.5)
Cloning into 'lnbits'...
remote: Enumerating objects: 46619, done.
remote: Counting objects: 100% (767/767), done.
remote: Compressing objects: 100% (346/346), done.
remote: Total 46619 (delta 512), reused 629 (delta 420), pack-reused 45852
Receiving objects: 100% (46619/46619), 29.24 MiB | 5.49 MiB/s, done.
Resolving deltas: 100% (33045/33045), done.
Note: switching to '0.10.5'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at 3c92ef29 FIX: #1661 (#1663)
# installing application dependencies
/usr/local/bin/poetry
Creating virtualenv lnbits-Me3QFGJB-py3.9 in /home/lnbits/.cache/pypoetry/virtualenvs
Installing dependencies from lock file

Package operations: 88 installs, 2 updates, 0 removals

  • Installing idna (3.4)
  • Installing pycparser (2.21)
  • Installing sniffio (1.3.0)
...
# OK install done ... might need to restart or call: sudo systemctl start lnbits
result='OK'
```
image
And my LNBits is up and running again ⚡

**Review by rootzoll — APPROVED** [review]

**Comment by rootzoll** [comment]
Testinstall worked - merging for next v1.9.0rc5

**Pull request merged**
