### PR TITLE
Service to install Jimmy Song's "Programming Bitcoin" book and programming environment

### PR DESCRIPTION
**Pull request by raulcano**
The idea behind this feature is to enable Raspiblitz to quickly deploy the environment for programming on Bitcoin, following the book "Programming Bitcoin" by Jimmy Song.
This pull request adds 3 things:
- A bonus script to download the book and materials from the Github repo [https://github.com/jimmysong/programmingbitcoin](https://github.com/jimmysong/programmingbitcoin) .
- A menu item to enable and disable this service.
- A command 'pb' to start the Jupyter Notebook server and make it available to work on.

At the moment, in order to open the Jupyter Notebook from your laptop (assuming it's connected via LAN), you need to tunnel the port 8888 from the Raspiblitz to your laptop. Something like this must be run from the device accessing the Raspiblitz:
`ssh -L 8888:localhost:8888 admin@192.168.1.XX`

After this, the Jupyter Notebook is accessible in the LAN connected device (i.e. your laptop) under the address
`http://localhost:8888`

image
image

image
image
image

### CODE REVIEW

**Comment by rootzoll** [comment]
Thats a cool idea .. I mark to for v1.7.1

**Comment by raulcano** [comment]
Great. I'll do some more fine tunning in the meantime.

**Comment by raulcano** [comment]
Something I found that's not working as intended since yesterday and I don't know why. This behaviour was working as intended and at some point it switched to what I describe here.

In my installation script I add to the bashrc a few lines , so a python environment is started and one command is run within the environment. 
The problem is that the command I want to run *within* the environment is executed outside of it, and it is of no value like that. I believe this can be achieved, but I have no idea now how to proceed. Any thoughts?

**Comment by originaljeremy** [comment]
What do you think about expanding the scope a bit and pulling in resources from:
https://github.com/BlockchainCommons/Learning-Bitcoin-from-the-Command-Line , and
https://github.com/bitcoinbook/bitcoinbook , https://github.com/lnbook/lnbook , etc
with the idea being that the service is a broader 'school for bitcoin programming' featuring courses and source material from many creators? Could be a really cool aspect to running a full node - so many people spin one up and then say, 'what do I do now?' Well, the answer is you go to school 'in your node' and learn how to contribute and maybe even create your own project.
Just a thought...

**Comment by raulcano** [comment]
> 
> 
> What do you think about expanding the scope a bit and pulling in resources from:
> https://github.com/BlockchainCommons/Learning-Bitcoin-from-the-Command-Line , and
> https://github.com/bitcoinbook/bitcoinbook , https://github.com/lnbook/lnbook , etc
> with the idea being that the service is a broader 'school for bitcoin programming' featuring courses and source material from many creators? Could be a really cool aspect to running a full node - so many people spin one up and then say, 'what do I do now?' Well, the answer is you go to school 'in your node' and learn how to contribute and maybe even create your own project.
> Just a thought...

This is a pretty cool idea. And what interesting sources you just linked.
Let me have a look and check how to put all this together...

**Comment by originaljeremy** [comment]
It may be overkill, but I recently gave Stephan Livera's course on Saylor Academy a whirl, and it might be cool to add a curated collection of Bitcoin-relevant articles and essays. It wouldn't take up too much space and would add to the 'cool factor' in my humble opinion. You'd almost be building a cypherpunk library full of interesting resources to better understand the technology. You could even have a fiction section - there's a neat list of books at https://www.goodreads.com/shelf/show/cypherpunk...

**Comment by raulcano** [comment]
Yes, if I rescope this as a "bitcoin academy" then we can add lots of resources. Thanks for the link, even though we cannot add copyrighted books to this feature, maybe there are some that can be shared..

**Comment by raulcano** [comment]
Given the broader scope as originally thought, what about renaming this to "Raspi Academy"? :D

**Comment by rootzoll** [comment]
> Given the broader scope as originally thought, what about renaming this to "Raspi Academy"? :D

The "Raspi" might change in the future .. if you wanna go broader maybe go for "Node", "Fullnode" or "Bitcoin Fullnode", etc

**Comment by originaljeremy** [comment]
> > Given the broader scope as originally thought, what about renaming this to "Raspi Academy"? :D
> 
> The "Raspi" might change in the future .. if you wanna go broader maybe go for "Node", "Fullnode" or "Bitcoin Fullnode", etc

Why not 'Blitz'?

**Comment by raulcano** [comment]
BlitzSchool? BlitzAcademy? :)

**Comment by originaljeremy** [comment]
I like BlitzAcademy

I also like just 'Blitz' as an overall brand. Correct me if I am wrong, but I think this project has outgrown its RaspberryPi roots...

**Comment by originaljeremy** [comment]
Also, about any papers, etc that aren't public, how does everyone feel about linking to sci hub?

This paper is available elsewhere, but as an example:
https://sci-hub.se/10.1109/TIT.1976.1055638

Also, didn't/doesn't the nodl ship with a ton of papers? I seem to remember someone working on that a few years ago, wonder how far they got?

**Comment by rootzoll** [comment]
Ok I am putting this PR up for testing ... @raulcano everthing ready from your side?

**Comment by raulcano** [comment]
Sorry, didn't have the time to refine it. I can move it to draft or any
other thing you suggest.

rootzoll ***@***.***> schrieb am Do., 19. Aug. 2021, 20:55:

**Comment by rootzoll** [comment]
@raulcano Yeah draft status would be good signal that this PR is still in the works. And you can take your time and pick up when you find the time or help others completing it.

**Comment by raulcano** [comment]
Good. Done. 
It's now in draft mode so I can come back to this later. Thanks for the understanding.
Cheers!

**Pull request closed without merging**
