### PR TITLE
replace xterm by uxterm for unicode support

### PR DESCRIPTION
**Pull request by holgern**
https://invisible-island.net/xterm/manpage/uxterm.html

### CODE REVIEW

**Comment by openoms** [comment]
Thank you for the PR, but did you test this?

I have changed `xterm` to `uxterm` in the 
`./python3-env-lnd/lib/python3.7/site-packages/blitztui/main.py`
and restarted with:
`config.scripts/blitz.touchscreen.sh calibrate`
and the unicode characters are still not showing.

**Comment by holgern** [comment]
It seems that addionally unicode fonts need to be loaded. I will try and update the PR.

**Comment by holgern** [comment]
@openoms I fixed it now. I tested it, it works for me.
You need to install `sudo apt-get install -y fonts-inconsolata` for testing. I added the installation of the package to blitz.touchscree.sh

**Comment by holgern** [comment]
I switched to the Terminus font, which has a better appearance:
```
sudo apt-get install xfonts-terminus
```

**Comment by openoms** [comment]
the unicode characters now show, but the physical touchscreen has completely fallen apart due to the size difference in the font. 
Will need to play with this a bit more.
I presume @holgern you don't have an LCD yourself?

**Comment by holgern** [comment]
Have you set ` '-fs', '9'` after `'-fa', 'Terminus'` ? I have a LCD and when using size 9 it looks ok.

**Comment by openoms** [comment]
Ok, my problem was not running :
`sudo apt-get install xfonts-terminus`
on the same node where editing the `main.py`.

Now works and looks awesome, unicode characters unlocked!
image

**Comment by rootzoll** [comment]
OK my tests of this PR look also good .. will merge and be part of v1.6.1

**Comment by rootzoll** [comment]
+cp into dev branch

**Pull request merged**
