### PR TITLE
Mail improvements

### PR DESCRIPTION
**Pull request by dennisreimann**
Some previous changes from #1299 got overwritten by fe69fae. Details in the individual commit messages. :)

/cc @frennkie

### CODE REVIEW

**Comment by frennkie** [comment]
Oh.. Sorry, my bad. I missed those changes.

**Comment by rootzoll** [comment]
Thanks. Also cherry-picked into dev branch.

**Comment by dennisreimann** [comment]
Thanks, should PRs be submitted against the dev branch?

**Comment by rootzoll** [comment]
If its a feature that targets to be in the 1.6.1 having a PR against the v1.6 branch is perfect ... we then just also cherry-pick merge that in to the dev so that it also will be in future releases. If your PR is targeting for a next main-release ... like v1.7 basing the PR on the dev branch would be better. For this one being based on v1.6 best.

**Comment by dennisreimann** [comment]
Thanks for the clarification!

**Pull request merged**
