### PR TITLE
updated dietpi readme and added torrent with SDcard image for Odroid HC1 / HC2

### PR DESCRIPTION
**Pull request by openoms**

### CODE REVIEW

**Comment by rootzoll** [comment]
@openoms There seems to be conflict in the FAQ  .. can you resolve it?

**Comment by openoms** [comment]
@rootzoll sorted now

**Comment by openoms** [comment]
I have rewrote the dietpi readme, so even the experimental part is looking much better.

**Comment by openoms** [comment]
I`ve rewritten the dietpi readme so even the experimental part is looking much better.

**Pull request merged**
