### PR TITLE
Display number of connected peers for bitcoind and lnd

### PR DESCRIPTION
**Pull request by ppachur**

### CODE REVIEW

**Comment by rootzoll** [comment]
@piezzo there is a conflict with master - can you resolve it?

**Comment by ppachur** [comment]
resolved.

**Comment by rootzoll** [comment]
Sorry can you rebase and resolve conficts again, then I will merge it in this time before I start making changes again.

**Review by ppachur — COMMENTED** [review]
should be up to date and mergeable now.

**Comment by rootzoll** [comment]
its now merged. thx :)

**Pull request merged**
