### PR TITLE
catch error on vulnerability

### PR DESCRIPTION
**Pull request by vv01f**
a vulnerable dependency (normalize-url for npm) broke the install script, auto trying `npm audit fix` here to iron it out

### CODE REVIEW

**Comment by rootzoll** [comment]
@dennisreimann wanna take a look?

General Info: At the moment I am preparing a RC1 for 1.7.1 which target is to test run the c-lightning integration and new setup refactoring. I will go thru the waiting PRs for v1.7.1 after that testrun and have them in later Release Candidates. This can still take some days .. because there is much going on at the moment.

**Comment by dennisreimann** [comment]
I don't think this is the right way to solve this issue and it should rather be fixed by providing a valid dependency tree in the package itself. However, `npm audit` does not report a vulnerability for the current stacking-sats-kraken version for me.

**Comment by vv01f** [comment]
it did for me when I setup a new pi 4 with v1.7 though, so I figured as npm dependecies could break any time this may help for future stuff and keep the install script not breaking. fixing the tree needs to be done each time again.

reproducing on the fresh pi:
1. `./config.scripts/bonus.stacking-sats-kraken.sh off`
2. `./config.scripts/bonus.stacking-sats-kraken.sh on`

> found 1 high severity vulnerability
>  run `npm audit fix` to fix them, or `npm audit` for details

```
$ npm audit
                                                                                
                       === npm audit security report ===                        
                                                                                
# Run  npm update normalize-url --depth 4  to resolve 1 vulnerability
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Regular Expression Denial of Service                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ normalize-url                                                │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ kraken-api                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ kraken-api > got > cacheable-request > normalize-url         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1755                            │
└───────────────┴──────────────────────────────────────────────────────────────┘


found 1 high severity vulnerability in 32 scanned packages
  run `npm audit fix` to fix 1 of them.
```

this gives error code 1… next time could be another package of the tree and still be fixed.

**Comment by cstenglein** [comment]
IMO the correct way to handle it would be to turn the audit of with the `--no-audit` flag, i.e. `npm install --no-audit`.

If you look at the advisory, the vulnerability would be a `ReDoS (regular expression denial of service) issue because it has exponential performance for data: URLs.`

Neither `stacking-sats-kraken` nor `kraken-api` make use of `data:` URLs though, so I don't think that is an issue.

**Comment by dennisreimann** [comment]
Here's a PR with an updated version:  #2483

**Comment by rootzoll** [comment]
With PR #2483 merged ... is this PR still relevant?

**Comment by dennisreimann** [comment]
It can be closed.

**Pull request closed without merging**
