### PR TITLE
Add torthistx() function to _commands.sh

### PR DESCRIPTION
**Pull request by 21isenough**
Maybe there's a better name for this function in the RaspiBlitz "lingo" :smiley:  Let me know.

### CODE REVIEW

**Comment by rootzoll** [comment]
Can you describe in what situation you are using this?

**Comment by 21isenough** [comment]
I'm using this when I want to easily broadcast a bitcoin transaction over Tor. I might not have a node that's running completely behind Tor. So, instead of accessing some website over Tor where I have to paste the tx into a form and send it, I just use this. 

Simple tx broadcasting over Tor at your fingertips.

**Comment by openoms** [comment]
Take the signed txn ready made in Electrum export to clipboard and paste into the RaspiBlitz terminal.  
`torthistx <RAW_txn>`  

Returns the txid.

**Comment by frennkie** [comment]
Can this info how/when/why this would be used please be included somewhere in the script or the documentation.

**Pull request merged**
