### PR TITLE
LNbits update to v0.11.2

### PR DESCRIPTION
**Pull request by rootzoll**
also to take care of the moved superuser file
https://github.com/lnbits/lnbits/pull/1900/files

### CODE REVIEW

**Comment by rootzoll** [comment]
@dni I updated to lnbits v0.11.1 ... but on testing a fresh install (there is no lnbits db in postgress before install) I get this errror on first boot - can you give me a hint?

```
Nov 23 14:45:35 raspberrypi systemd[1]: Started lnbits.service - lnbits.
Nov 23 14:45:39 raspberrypi sh[3856874]: 2023-11-23 14:45:39.88 | INFO | Started server process [3856874]
Nov 23 14:45:39 raspberrypi sh[3856874]: 2023-11-23 14:45:39.88 | INFO | Waiting for application startup.
Nov 23 14:45:39 raspberrypi sh[3856874]: 2023-11-23 14:45:39.92 | ERROR | (psycopg2.errors.InsufficientPrivilege) permission denied for schema public
Nov 23 14:45:39 raspberrypi sh[3856874]: LINE 2:     CREATE TABLE IF NOT EXISTS dbversions (
Nov 23 14:45:39 raspberrypi sh[3856874]:                                        ^
Nov 23 14:45:39 raspberrypi sh[3856874]: [SQL:
Nov 23 14:45:39 raspberrypi sh[3856874]:     CREATE TABLE IF NOT EXISTS dbversions (
Nov 23 14:45:39 raspberrypi sh[3856874]:         db TEXT PRIMARY KEY,
Nov 23 14:45:39 raspberrypi sh[3856874]:         version INT NOT NULL
Nov 23 14:45:39 raspberrypi sh[3856874]:     )
Nov 23 14:45:39 raspberrypi sh[3856874]:     ]
Nov 23 14:45:39 raspberrypi sh[3856874]: (Background on this error at: http://sqlalche.me/e/13/f405)
Nov 23 14:45:39 raspberrypi sh[3856874]: 2023-11-23 14:45:39.93 | ERROR | Traceback (most recent call last):
Nov 23 14:45:39 raspberrypi sh[3856874]:   File "/home/lnbits/.cache/pypoetry/virtualenvs/lnbits-Me3QFGJB-py3.11/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
Nov 23 14:45:39 raspberrypi sh[3856874]:     self.dialect.do_execute(
Nov 23 14:45:39 raspberrypi sh[3856874]:   File "/home/lnbits/.cache/pypoetry/virtualenvs/lnbits-Me3QFGJB-py3.11/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
Nov 23 14:45:39 raspberrypi sh[3856874]:     cursor.execute(statement, parameters)
Nov 23 14:45:39 raspberrypi sh[3856874]: psycopg2.errors.InsufficientPrivilege: permission denied for schema public
Nov 23 14:45:39 raspberrypi sh[3856874]: LINE 2:     CREATE TABLE IF NOT EXISTS dbversions (
Nov 23 14:45:39 raspberrypi sh[3856874]:                                        ^
Nov 23 14:45:39 raspberrypi sh[3856874]: The above exception was the direct cause of the following exception:
Nov 23 14:45:39 raspberrypi sh[3856874]: Traceback (most recent call last):
Nov 23 14:45:39 raspberrypi sh[3856874]:   File "/home/lnbits/lnbits/lnbits/app.py", line 351, in lnbits_startup
Nov 23 14:45:39 raspberrypi sh[3856874]:     await migrate_databases()
Nov 23 14:45:39 raspberrypi sh[3856874]:   File "/home/lnbits/lnbits/lnbits/commands.py", line 88, in migrate_databases
Nov 23 14:45:39 raspberrypi sh[3856874]:     await core_migrations.m000_create_migrations_table(conn)
Nov 23 14:45:39 raspberrypi sh[3856874]:   File "/home/lnbits/lnbits/lnbits/core/migrations.py", line 10, in m000_create_migrations_table
Nov 23 14:45:39 raspberrypi sh[3856874]:     await db.execute(
Nov 23 14:45:39 raspberrypi sh[3856874]:   File "/home/lnbits/lnbits/lnbits/db.py", line 215, in execute
Nov 23 14:45:39 raspberrypi sh[3856874]:     return await self.conn.execute(
Nov 23 14:45:39 raspberrypi sh[3856874]:            ^^^^^^^^^^^^^^^^^^^^^^^^
Nov 23 14:45:39 raspberrypi sh[3856874]:   File "/home/lnbits/.cache/pypoetry/virtualenvs/lnbits-Me3QFGJB-py3.11/lib/python3.11/site-packages/sqlalchemy_aio/base.py", line 291, in execute
Nov 23 14:45:39 raspberrypi sh[3856874]:     rp = await self._run_in_thread(
Nov 23 14:45:39 raspberrypi sh[3856874]:          ^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 23 14:45:39 raspberrypi sh[3856874]:   File "/home/lnbits/.cache/pypoetry/virtualenvs/lnbits-Me3QFGJB-py3.11/lib/python3.11/site-packages/sqlalchemy_aio/base.py", line 234, in _run_in_thread
Nov 23 14:45:39 raspberrypi sh[3856874]:     return await _self._worker.run(_func, args, kwargs)
Nov 23 14:45:39 raspberrypi sh[3856874]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 23 14:45:39 raspberrypi sh[3856874]:   File "/home/lnbits/.cache/pypoetry/virtualenvs/lnbits-Me3QFGJB-py3.11/lib/python3.11/site-packages/sqlalchemy_aio/asyncio.py", line 70, in run
Nov 23 14:45:39 raspberrypi sh[3856874]:     return request.response.unwrap()
Nov 23 14:45:39 raspberrypi sh[3856874]:            ^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 23 14:45:39 raspberrypi sh[3856874]:   File "/home/lnbits/.cache/pypoetry/virtualenvs/lnbits-Me3QFGJB-py3.11/lib/python3.11/site-packages/outcome/_impl.py", line 138, in unwrap
Nov 23 14:45:39 raspberrypi sh[3856874]:     raise captured_error
Nov 23 14:45:39 raspberrypi sh[3856874]:   File "/home/lnbits/.cache/pypoetry/virtualenvs/lnbits-Me3QFGJB-py3.11/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1003, in execute
Nov 23 14:45:39 raspberrypi sh[3856874]:     return self._execute_text(object_, multiparams, params)
Nov 23 14:45:39 raspberrypi sh[3856874]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 23 14:45:39 raspberrypi sh[3856874]:   File "/home/lnbits/.cache/pypoetry/virtualenvs/lnbits-Me3QFGJB-py3.11/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1172, in _execute_text
Nov 23 14:45:39 raspberrypi sh[3856874]:     ret = self._execute_context(
Nov 23 14:45:39 raspberrypi sh[3856874]:           ^^^^^^^^^^^^^^^^^^^^^^
Nov 23 14:45:39 raspberrypi sh[3856874]:   File "/home/lnbits/.cache/pypoetry/virtualenvs/lnbits-Me3QFGJB-py3.11/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
Nov 23 14:45:39 raspberrypi sh[3856874]:     self._handle_dbapi_exception(
Nov 23 14:45:39 raspberrypi sh[3856874]:   File "/home/lnbits/.cache/pypoetry/virtualenvs/lnbits-Me3QFGJB-py3.11/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
Nov 23 14:45:39 raspberrypi sh[3856874]:     util.raise_(
Nov 23 14:45:39 raspberrypi sh[3856874]:   File "/home/lnbits/.cache/pypoetry/virtualenvs/lnbits-Me3QFGJB-py3.11/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
Nov 23 14:45:39 raspberrypi sh[3856874]:     raise exception
Nov 23 14:45:39 raspberrypi sh[3856874]:   File "/home/lnbits/.cache/pypoetry/virtualenvs/lnbits-Me3QFGJB-py3.11/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
Nov 23 14:45:39 raspberrypi sh[3856874]:     self.dialect.do_execute(
Nov 23 14:45:39 raspberrypi sh[3856874]:   File "/home/lnbits/.cache/pypoetry/virtualenvs/lnbits-Me3QFGJB-py3.11/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
Nov 23 14:45:39 raspberrypi sh[3856874]:     cursor.execute(statement, parameters)
Nov 23 14:45:39 raspberrypi sh[3856874]: sqlalchemy.exc.ProgrammingError: (psycopg2.errors.InsufficientPrivilege) permission denied for schema public
Nov 23 14:45:39 raspberrypi sh[3856874]: LINE 2:     CREATE TABLE IF NOT EXISTS dbversions (
Nov 23 14:45:39 raspberrypi sh[3856874]:                                        ^
Nov 23 14:45:39 raspberrypi sh[3856874]: [SQL:
Nov 23 14:45:39 raspberrypi sh[3856874]:     CREATE TABLE IF NOT EXISTS dbversions (
Nov 23 14:45:39 raspberrypi sh[3856874]:         db TEXT PRIMARY KEY,
Nov 23 14:45:39 raspberrypi sh[3856874]:         version INT NOT NULL
Nov 23 14:45:39 raspberrypi sh[3856874]:     )
Nov 23 14:45:39 raspberrypi sh[3856874]:     ]
Nov 23 14:45:39 raspberrypi sh[3856874]: (Background on this error at: http://sqlalche.me/e/13/f405)
Nov 23 14:45:39 raspberrypi sh[3856874]: During handling of the above exception, another exception occurred:
Nov 23 14:45:39 raspberrypi sh[3856874]: Traceback (most recent call last):
Nov 23 14:45:39 raspberrypi sh[3856874]:   File "/home/lnbits/.cache/pypoetry/virtualenvs/lnbits-Me3QFGJB-py3.11/lib/python3.11/site-packages/starlette/routing.py", line 677, in lifespan
Nov 23 14:45:39 raspberrypi sh[3856874]:     async with self.lifespan_context(app) as maybe_state:
Nov 23 14:45:39 raspberrypi sh[3856874]:   File "/home/lnbits/.cache/pypoetry/virtualenvs/lnbits-Me3QFGJB-py3.11/lib/python3.11/site-packages/starlette/routing.py", line 566, in __aenter__
Nov 23 14:45:39 raspberrypi sh[3856874]:     await self._router.startup()
Nov 23 14:45:39 raspberrypi sh[3856874]:   File "/home/lnbits/.cache/pypoetry/virtualenvs/lnbits-Me3QFGJB-py3.11/lib/python3.11/site-packages/starlette/routing.py", line 654, in startup
Nov 23 14:45:39 raspberrypi sh[3856874]:     await handler()
Nov 23 14:45:39 raspberrypi sh[3856874]:   File "/home/lnbits/lnbits/lnbits/app.py", line 380, in lnbits_startup
Nov 23 14:45:39 raspberrypi sh[3856874]:     raise ImportError("Failed to run 'startup' event.")
Nov 23 14:45:39 raspberrypi sh[3856874]: ImportError: Failed to run 'startup' event.
Nov 23 14:45:39 raspberrypi sh[3856874]: 2023-11-23 14:45:39.93 | ERROR | Application startup failed. Exiting.
```

As background info ... a lnbits db got created in postgres:
```
admin@192.168.178.182:~ ₿ ./config.scripts/bonus.postgresql.sh info
       data_directory
-----------------------------
 /var/lib/postgresql/15/main
(1 row)

  datname
-----------
 postgres
 template1
 template0
 lnbits_db
(4 rows)
```

**Comment by rootzoll** [comment]
As far as I can see the error is due to a table schema cannot get created - because if missing Privilege:
```
Dec 01 12:14:38 raspberrypi sh[1625901]: 2023-12-01 12:14:38.89 | INFO | Waiting for application startup.
Dec 01 12:14:38 raspberrypi sh[1625901]: 2023-12-01 12:14:38.93 | ERROR | (psycopg2.errors.InsufficientPrivilege) permission denied for schema public
Dec 01 12:14:38 raspberrypi sh[1625901]: LINE 2:     CREATE TABLE IF NOT EXISTS dbversions (
Dec 01 12:14:38 raspberrypi sh[1625901]:                                        ^
Dec 01 12:14:38 raspberrypi sh[1625901]: [SQL:
Dec 01 12:14:38 raspberrypi sh[1625901]:     CREATE TABLE IF NOT EXISTS dbversions (
Dec 01 12:14:38 raspberrypi sh[1625901]:         db TEXT PRIMARY KEY,
Dec 01 12:14:38 raspberrypi sh[1625901]:         version INT NOT NULL
Dec 01 12:14:38 raspberrypi sh[1625901]:     )
Dec 01 12:14:38 raspberrypi sh[1625901]:     ]
Dec 01 12:14:38 raspberrypi sh[1625901]: (Background on this error at: http://sqlalche.me/e/13/f405)
```

But the lnbits_user seems quite Privileged ....

```
admin@192.168.178.182:~ ₿ sudo cat /home/lnbits/lnbits/.env
LNBITS_ADMIN_UI=true
LNBITS_DATABASE_URL=postgres://lnbits_user:raspiblitz@localhost:5432/lnbits_db
```

```
postgres=# SELECT nsp.nspname AS schema, a.grantor, a.grantee, a.privilege_type
FROM pg_namespace nsp
LEFT JOIN pg_authid ON (nsp.nspowner = pg_authid.oid)
CROSS JOIN LATERAL aclexplode(nsp.nspacl) AS a
WHERE a.grantee = (SELECT oid FROM pg_roles WHERE rolname = 'lnbits_user');
 schema | grantor | grantee | privilege_type
--------+---------+---------+----------------
 public |    6171 |   16387 | USAGE
 public |    6171 |   16387 | CREATE
```

@dni & @callebtc what am I missing here?

**Comment by rootzoll** [comment]
OK it seems that the lnbits_user is missing the priviledge for database migration. When running with default `postgres` user (havr to set a password first) it works. So how to fix this in the raspiblitz scripts?

**Comment by openoms** [comment]
> OK it seems that the lnbits_user is missing the priviledge for database migration. When running with default `postgres` user (havr to set a password first) it works. So how to fix this in the raspiblitz scripts?

did not look deep yet, but looks like a similar issue as found here for btcpay:
https://github.com/raspiblitz/raspiblitz/pull/4058#issuecomment-1764675597
fixed in this commit:
https://github.com/raspiblitz/raspiblitz/pull/4058/commits/29de9e10d1127b6b0be04e5700f46cfa92814c9e

could try to grant privileges  to the `public`  SCHEMA for the `lnbits_user` like:
```
sudo -u postgres psql -d btcpaymainnet -c "GRANT ALL PRIVILEGES ON SCHEMA public TO btcpay;"
```

**Comment by rootzoll** [comment]
Tried a similar thing with no success ... I now got it running by adding a password to the default postgres user and make lnbits use that one.

**Comment by openoms** [comment]
Updated my Lnbits still on SQlite and CLN
install went ok

tried migration -> had a migration error moving the cashu table - will follow that up

Question:
is the sync (pulling the latest commits) step needed for migration?

Ok, the migration was successful with the v0.11.2 version (without `sync`) after deleted the conflicting extensions.

We can remove these two lines:
https://github.com/raspiblitz/raspiblitz/blob/fbd234f796efa2bf5822487305c933b85c69e403/home.admin/config.scripts/bonus.lnbits.sh#L1179-L1180

**Review by openoms — APPROVED** [review]

**Pull request merged**
