### PR TITLE
Upgrade mempool to v2.2.2

### PR DESCRIPTION
**Pull request by wiz**

### CODE REVIEW

**Comment by wiz** [comment]
@softsimon

**Comment by rootzoll** [comment]
PR is is still in "draft" .. is there anything more needed for the update? We will ship v1.7.1 soon ... would be great of have the lastest mempool version as part of it.

**Comment by wiz** [comment]
Waiting for @softsimon to test the PR but if you can test feel free to merge :)

**Comment by softsimon** [comment]
tested ACK

**Pull request merged**
