### PR TITLE
Update broken links / use GitHub links.

### PR DESCRIPTION
**Pull request by FeedMyTummy**
Need help with one more link. Do not know which one is the new link for
https://raspibolt.github.io/raspibolt/raspibolt_20_pi.html#raspi-config

### CODE REVIEW

**Comment by rootzoll** [comment]
About the links in general ... I think the official links are now to `raspibolt.org` - like this one:
https://raspibolt.org/operating-system.html#configure-boot-options

**Comment by FeedMyTummy** [comment]
@rootzoll Yes. I changed to the GitHub repo as https://github.com/raspibolt/raspibolt/ is the backing source for https://raspibolt.org. Do you prefer links to https://raspibolt.org?

**Comment by rootzoll** [comment]
Yeah I dont think we should have links with long blobIDs `a21788c0518618d17093e3f447f68a53e4efa6e7` and use the raspibolt.org ones.

**Comment by FeedMyTummy** [comment]
@rootzoll Moved to the raspibolt.org links. The reason for the prepare-wifi long blob is that it has been removed from the repo (Thus, from raspibolt.org) and using Raspberry Pi Imager is what is now recommend by the author. I left the manual  instructions (the one found in the long blob) as that may be of use to someone who is using a flashing software other than Raspberry Pi Imager.

**Comment by rootzoll** [comment]
perfect. much tanks. merging :)

**Pull request merged**
