### PR TITLE
fix fulcrum uninstall (tor service)

### PR DESCRIPTION
**Pull request by resignedScientist**
Here the wrong TOR service was turned off on uninstall.

### CODE REVIEW

**Comment by resignedScientist** [comment]
I don't know to which branch to merge it though

**Comment by openoms** [comment]
use the `dev` branch please

**Comment by resignedScientist** [comment]
ok, I do this again with dev branch

**Comment by resignedScientist** [comment]
nvm, its already fixed on dev branch 😅

**Pull request closed without merging**
