### PR TITLE
fix moved config.txt

### PR DESCRIPTION
**Pull request by rootzoll**

### CODE REVIEW

**Comment by rootzoll** [comment]
@openoms plz give it a review

**Comment by rootzoll** [comment]
First tests show problems ... needs more testing

**Comment by rootzoll** [comment]
OK first test now look OK .. will need to test more, but removing draft status.

**Comment by openoms** [comment]
LGTM, but will flash the image as well

**Comment by neversleep404** [comment]
I modify my config.txt to rotate the display and using NVMe gen3.

Bildschirmfoto 2024-04-09 um 00 24 23

NVMe detection works. Rotation not.
IMG_2514

config.txt after setup:

Bildschirmfoto 2024-04-09 um 01 25 33

**Comment by rootzoll** [comment]
@neversleep404 I just releaaed rc7 that should contain all needed config.txt modifications .. is it working for you?

**Comment by rootzoll** [comment]
rotation during recovery is still wrong but should fix itself when recovery finishes.

**Comment by neversleep404** [comment]
@rootzoll is not. See the last screenshot above after the setup and after the final reboot.
Good news: R7 runing with a lower CPU load than R5 and R6 on my configuration (CL, CL Boss, mempool, Electrum).

**Comment by rootzoll** [comment]
@neversleep404 did you switched rotation on/off thru the SSHMAINMENU > SETTINGS ? If you just edited the config.txt manually before that cannot be remembered on recovery - rotation needs to be set thru `/mnt/hdd/raspiblitz.conf`using `lcdrotate`parameter (where 1 is default).

**Comment by neversleep404** [comment]
Ssh Menue Rotation is on and I set it manually in the config.txt.
In all builds until RC6 it works.

**Comment by rootzoll** [comment]
Ok I am testing here with my RaspiBlitz. I go into the SSHMAINMENU > SETTINGS and I turn the Rotation OFF which results after a reboot in the LCD being rotated ... I know, its a bit confusing. By default rotation is ON - which is the normal. So by turning Rotaion OFF I set the RaspiBlitz into the non-default Rotation. And when I look now into `cat /mnt/hdd/raspiblitz.conf` I can see that is `lcdrotate=0` as it should be now ... I did no manual change of config.txt, etc.

Bildschirmfoto 2024-04-09 um 14 09 22

Now I use a v1.11.0rc7 fatpack image to recover ... and once I am completly thru with recovery, the screen is again in non-default rotation as it should be with my changed settings. @neversleep404 So everything works as it should - I cannot reproduce your problem.

**Comment by neversleep404** [comment]
I can try it tomorrow.
(Lot of meetings and a long day today) 
Thanks for your description.

**Comment by neversleep404** [comment]
Ok. I used now my testing PI 5. insert only one line before the recovery in the config.txt:  dtparam=pciex1_gen=3 and use a v1.11.0rc7 lean image to recover.
After the recovery and final reboot I go into the SSHMAINMENU > SETTINGS and I turn the Rotation OFF and reboot, which did not change the LCD rotation after after a reboot

Bildschirmfoto 2024-04-10 um 02 53 02

And when I look now into cat /mnt/hdd/raspiblitz.conf I can see that is lcdrotate=0.

Bildschirmfoto 2024-04-10 um 02 54 21

the config file looks fine, but nothing changed.
 
Bildschirmfoto 2024-04-10 um 02 55 30

 I doubled now the last line in the config.txt
 dtoverlay=waveshare35a:rotate=270
 dtoverlay=waveshare35a:rotate=270
 
 reboot and nothing changed.
 
I go into the SSHMAINMENU > SETTINGS and I turn the Rotation ON

reboot. LCD did not changed.


Bildschirmfoto 2024-04-10 um 03 20 38

and in the config.txt:

Bildschirmfoto 2024-04-10 um 03 22 42


Now I'm confused because the change in the config.txt 'rotate=270' normally rotated the screen. But there is now no change with '90' and '270'. On my other Pi 5 'rotate=270' worked when I changed it after the final reboot.
The only difference compared to my other Pi 5 was that the recovery was done without the LCD because the installation always failed without an additional external cooling fan, as the NVMe was no longer recognized. Likely an overheating issue.
But in all the documented steps mentioned above, the LCD was mounted, and I did not remove it.

**Comment by neversleep404** [comment]
I could install it now as new "Raspiblitz" and see what happened then?

**Comment by rootzoll** [comment]
@neversleep404 yeah it could be that some old changes somehow make troubles. Best to fresh setup your Testpi5 and just reuse the blockchain and check then again if the rc7 respects the LCD rotation.

**Comment by neversleep404** [comment]
@rootzoll ok. You used the fatpack. I'll use the lean image.

**Comment by neversleep404** [comment]
@rootzoll: FRESH setup with CL with config.txt: dtparam=pciex1_gen=3.

Bildschirmfoto 2024-04-10 um 17 04 20

Setting:
Bildschirmfoto 2024-04-10 um 17 26 18

Raspi try to reboot, but screen is white and nothing happens. SSH did not work. SD-Card light is on, no blinking. System hangs.

PowerOff and PowerOn. Reboot starts. **LCD has not rotated**. Config.txt looks good.

Bildschirmfoto 2024-04-10 um 17 36 55
Bildschirmfoto 2024-04-10 um 17 39 43



I'll try it later with the fatpack. Then we see if the Problem is my HW, or the Package.

**Comment by neversleep404** [comment]
@rootzoll: Fatpack works as it should work. The Problem is only in the lean Image.
 LCD rotates after the SSHMAINMENU > SETTINGS and turning the Rotation OFF (and the automatic reboot)

**Comment by rootzoll** [comment]
@neversleep404 I just tested with minimal image rc7 and on both RaspberryPi 4 & 5 that have both rotation turned off (non-default) its as the old setting before the recovery. 

So I think for the final v1.11.0 release we are good. If you can stull reproduce after final release please open a seperate issue for it and we will further investigate.

**Comment by neversleep404** [comment]
HW:
Geekworm X1001 PCIe to M.2 NVMe 
WD_BLACK SN770 NVMe SSD 2 TB
ELEGOO Display 3.5" Zoll TFT LCD 

SW: minimal image RC7 from your RaspiBlitz RPi5 Testing link: https://docs.raspiblitz.org/docs/setup/software-setup/download#downloading-the-software

unmodified config.txt

What happened: Insert the fresh burned SD-Card. Power on. Fan is loud. Screen stays white. SSH did also not work.
Manual Power off. Manual Power on. Fan is loud. nothing happens. After a few minutes(?) Fan goes out, fan goes on. Nothing happens. A few minutes later fan goes out, fan goes on. SSH works, screen is white:

Bildschirmfoto 2024-04-16 um 11 19 09

I retesting it now with the fat and a new loaded lean image. Please Wait.

**Comment by neversleep404** [comment]
Second try with the new loaded lean Image:
Fan goes on and off, fan goes on. SSH works, screen is white:

Bildschirmfoto 2024-04-16 um 11 35 13

Bildschirmfoto 2024-04-16 um 11 35 41

Not good. I have a full synced Blockchain on the NVMe.

Next try, fat Image...

**Comment by neversleep404** [comment]
HW:
Geekworm X1001 PCIe to M.2 NVMe
WD_BLACK SN770 NVMe SSD 2 TB
ELEGOO Display 3.5" Zoll TFT LCD

SW: fat image RC7 from your RaspiBlitz RPi5 Testing link: https://docs.raspiblitz.org/docs/setup/software-setup/download#downloading-the-software

unmodified config.txt

What happened: Insert the fresh burned SD-Card. Power on. Fan is loud. Screen stays white. SSH did also not work.
Manual Power off. Manual Power on. Fan is loud. system boots. Screen is on.

Bildschirmfoto 2024-04-16 um 11 54 25

**Comment by neversleep404** [comment]
Now. I copied the config.txt from the fat image to the lean image. And insert 
dtparam=pciex1_gen=3

display is on, setup process runs. NVMe and Blockchain is recognized

Bildschirmfoto 2024-04-16 um 12 03 08

Bildschirmfoto 2024-04-16 um 12 03 27

Bildschirmfoto 2024-04-16 um 12 03 53

Bildschirmfoto 2024-04-16 um 12 04 04

looking good. Installation runs.

**Pull request merged**
