### PR TITLE
Migrate initwallet to Python3

### PR DESCRIPTION
**Pull request by frennkie**
As this touches a file that handles private keys/seed words I would like to be as careful as possible with the changes in order to not break anything. 

I think these are the outstanding steps

* [x] do manual tests

This is related to #822

### CODE REVIEW

**Comment by frennkie** [comment]
@rootzoll the build process gives a big warning for Python2:

```
Installing setuptools, pkg_resources, pip, wheel...done.
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
```

Do you think we can drop Python2 (and migrate this script) in time for the 1.4 release?

**Comment by rootzoll** [comment]
@frennkie I think a move to python3 is good - if you think the migration is ready/working, feel free to merge.

**Comment by openoms** [comment]
Built the SD 18h ago before the latest commit: https://github.com/rootzoll/raspiblitz/pull/878#issuecomment-558244166

I got this error when creating a new wallet:
```
Generating new Wallet ....
Traceback (most recent call last):
  File "/home/admin/config.scripts/lnd.initwallet.py", line 7, in <module>
    import grpc
ModuleNotFoundError: No module named 'grpc'
FAIL!! -> MISSING seedwords data - but also no err data ?!?
CHECK output data above - PRESS ENTER to restart 70initLND.sh
```
Is it fixed now? Will do a XXsyncScripts and try again.

**Comment by openoms** [comment]
was running:
```
cd raspiblitz/
git remote set-url origin https://github.com/frennkie/raspiblitz.git
/home/admin/XXsyncScripts.sh migrate-initwallet
sudo reboot
```

But this is still the case:
```
Generating new Wallet ....
/home/admin/70initLND.sh: line 194: /home/admin/python-env-lnd/bin/activate: No such file or directory
Traceback (most recent call last):
  File "/home/admin/config.scripts/lnd.initwallet.py", line 7, in <module>
    import grpc
ModuleNotFoundError: No module named 'grpc'
FAIL!! -> MISSING seedwords data - but also no err data ?!?
CHECK output data above - PRESS ENTER to restart 70initLND.sh
```

**Comment by frennkie** [comment]
I have another PR pending.. They depend on each other... Will submit it later today. 

On November 26, 2019 12:25:57 PM GMT+01:00, openoms <notifications@github.com> wrote:
>Built the SD 18h ago before the latest commit:
>https://github.com/rootzoll/raspiblitz/pull/878#issuecomment-558244166
>
>I got this error when creating a new wallet:
>```
>Generating new Wallet ....
>Traceback (most recent call last):
>File "/home/admin/config.scripts/lnd.initwallet.py", line 7, in
><module>
>    import grpc
>ModuleNotFoundError: No module named 'grpc'
>FAIL!! -> MISSING seedwords data - but also no err data ?!?
>CHECK output data above - PRESS ENTER to restart 70initLND.sh
>```
>Is it fixed now? Will do a XXsyncScripts and try again.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/rootzoll/raspiblitz/pull/841#issuecomment-558586810

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by frennkie** [comment]
@openoms PR #884 should fix this issue.

**Comment by frennkie** [comment]
@rootzoll I have a reminder for updating docs in this PR. But I actually don't see any important user-facing changes... this should be transparent. 

The only thing I think makes sense is to update the docs so that other contributors and user using third party stuff are aware of the dropped Python2 support.

What do you think?

**Comment by rootzoll** [comment]
@frennkie why not add into the header of every python file:

```
┏┓
┃┃╱╲ in
┃╱╱╲╲ this
╱╱╭╮╲╲house
▔▏┗┛▕▔ we
╱▔▔▔▔▔▔▔▔▔▔╲
like to use
python3 not2
╱╱┏┳┓╭╮┏┳┓ ╲╲
▔▏┗┻┛┃┃┗┻┛▕▔
```

or keep it short with one line :)

**Comment by openoms** [comment]
> @openoms PR #884 should fix this issue.

I have run the build_sdcard.sh changes in that commit manually and synced the scripts from the branch `remove-python2`.

still getting:
```
Generating new Wallet ....
Traceback (most recent call last):
  File "/home/admin/config.scripts/lnd.initwallet.py", line 15, in <module>
    import grpc
ModuleNotFoundError: No module named 'grpc'
FAIL!! -> MISSING seedwords data - but also no err data ?!?
CHECK output data above - PRESS ENTER to restart 70initLND.sh
```

Is there a branch now with all the changes, so I can build a clean SD?

**Comment by frennkie** [comment]
I was only was only installing the needed pip packages when BlitzTUI is installed. Fixed now.

**Comment by frennkie** [comment]
> Is there a branch now with all the changes, so I can build a clean SD

Yes.. Now: master.. 😉

**Comment by openoms** [comment]
I was still missing this:
```
Traceback (most recent call last):
  File "/home/admin/config.scripts/lnd.initwallet.py", line 17, in <module>
    from lndlibs import rpc_pb2_grpc as lnrpc
  File "/home/admin/config.scripts/lndlibs/rpc_pb2_grpc.py", line 4, in <module>
    import rpc_pb2 as rpc__pb2
ModuleNotFoundError: No module named 'rpc_pb2'
```
will build one from master then.

**Comment by frennkie** [comment]
The fix for that is included in #878.

**Comment by rootzoll** [comment]
In branch v1.4 I made 70initLND.sh made use the new lnd.initwallet2.py script, but it throws on generating a new wallet:
```
Traceback (most recent call last):
  File "/home/admin/config.scripts/lnd.initwallet2.py", line 7, in <module>
    from lndlibs import rpc_pb2_grpc as lnrpc
  File "/home/admin/config.scripts/lndlibs/rpc_pb2_grpc.py", line 4, in <module>
    import rpc_pb2 as rpc__pb2
ModuleNotFoundError: No module named 'rpc_pb2'
```
@frennkie what do I miss?

**Comment by frennkie** [comment]
Are you testing the v1.4 from scratch? The build_sdcard.sh includes a patch for the lnd lib file to make it compatible for both Python2 and 3.

70initLND.sh should actually use lnd.initwallet.py...

**Comment by rootzoll** [comment]
I changed `70iniLND.sh` back to `lnd.initwallet.py`. made a fresh protobuff build of lnd libs. And also applied the changes from build_sd card again ... but still getting that error.

@frennkie at the moment the v1.4 branch is not able to create a LND wallet on setup. This bug is a showstopper for a Release Candidate for the 1.4 Milestone. Any help to fix this is appreciated.

**Comment by rootzoll** [comment]
@frennkie seems I got it working ... it seems the customizing of the proto files did not worked on my instance. Doing more testing.

**Comment by rootzoll** [comment]
OK - fixed :) Show can go on ...

**Comment by phenomeus** [comment]
hey guys, I'm also stuck at this, running the script from my new rpi4 and dietpi 

any quick solution for me to continue? 

Bildschirmfoto 2020-01-03 um 09 57 48

**Comment by frennkie** [comment]
Which version are you using? The official 1.3. Release? Oder the 1.4. Release Candidate?

**Comment by phenomeus** [comment]
1.3, can I partially upgrade?

**Comment by frennkie** [comment]
There is a partial way (XXsync..) which does not guarantee to cover everything.

I was asking so that I know where to check. This might only affect 1.3. Or could also affect 1.4. I will have a look.

**Comment by frennkie** [comment]
OK, I'm sure that this is covered in the v1.4 branch. The v1.4 Release Candidate 1 was created before Christmas and we have since fixed a few other issues. So a v1.4 RC2 is due for sometime next week.

As you are using Diet Pi (which I don't)... Would you able and willing to test the latest v1.4?

**Comment by phenomeus** [comment]
I am willing to help. Latest Clean dietpi installed. 

How can I update and continue the lnd  process?

**Comment by frennkie** [comment]
From a clean dietpi all you need to do is follow these instructions:

https://github.com/rootzoll/raspiblitz/blob/master/alternative.platforms/dietpi/README.md

In the section **Run the RaspiBlitz build_sdcard.sh script** you run:

```
wget https://raw.githubusercontent.com/rootzoll/raspiblitz/v1.4/build_sdcard.sh && sudo bash build_sdcard.sh v1.4 rootzoll
```

**Comment by phenomeus** [comment]
Ok so I just cancel the ongoing 1.3 install, do a fresh build and it should overwrite everything necessary right?

**Comment by frennkie** [comment]
Yes.

**Comment by phenomeus** [comment]
can I reset the ongoing installation process from 1.3? renaming the RaspiBlitz.conf wasn't enough 

build 1.4 went through smoothly, now I just want to restart the whole configuration process.
on it:
https://github.com/rootzoll/raspiblitz/blob/master/FAQ.md#how-to-setup-freshcleanreset-and-not-getting-into-recovery-mode

**Comment by frennkie** [comment]
The old ongoing installation process should only be tracked by a file on the sdcard. But you made a clean, fresh sd, right? So that file should be gone... check for /home/admin/raspiblitz.**info**.

Otherwise, I'm not quite sure what you setup is.. do you  have funds on the HDD? LND wallet? the blockchain?

**Comment by frennkie** [comment]
Try `rm /home/admin/raspiblitz.info ; /home/admin/XXshutdown.sh reboot`

**Comment by phenomeus** [comment]
ok, had to do a fresh dietpi, redoing everything, stay tuned ;)

**Comment by phenomeus** [comment]
something is fckin up my clean installation and I cant tell what because I'm headless without hdmi… 

dietpi is ok, but the raspiblitz 1.4 installation is doing something so I can't get to reboot the pi twice without HDD. ssh login is refusing suddenly, cant get in… only a sd wipe is helping :/

its even not able to ping anymore. so no idea what's going on without a screen attached

**Comment by phenomeus** [comment]
so I can confirm that 1.4 is doing some stuff so I cant reconnect with ssh after reboot and with attached HDD, during or after install, I tried everything. 

1.3/master is working but I cant get through the lnd setup part because of the above error from the screenshot, the reason why I had to try 1.4 in the first place. 

without a micro hdmi I'm right now not able to debug further…

**Comment by phenomeus** [comment]
TOR is not getting installed with the above 1.4 build_card, I think because some dependencies are not figured out with dietpi 6.28.0 (newest version)

./internet.tor.sh prepare
Detect Base Image ...
OK running dietpi
*** INSTALL TOR REPO ***

*** Install dirmngr ***
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.       
Statusinformationen werden eingelesen.... Fertig
dirmngr ist schon die neueste Version (2.2.12-1+rpi1+deb10u1).
Probieren Sie »apt --fix-broken install«, um dies zu korrigieren.
Die folgenden Pakete haben unerfüllte Abhängigkeiten:
 xinput-calibrator : Hängt ab von: libx11-6 soll aber nicht installiert werden
                     Hängt ab von: libxext6 soll aber nicht installiert werden
                     Hängt ab von: libxi6 (>= 2:1.2.0) soll aber nicht installiert werden
E: Unerfüllte Abhängigkeiten. Versuchen Sie »apt --fix-broken install« ohne Angabe eines Pakets (oder geben Sie eine Lösung an).

*** Adding KEYS deb.torproject.org ***
torKeyAvailable=1
TOR key is available

*** Adding Tor Sources to sources.list ***
torSourceListAvailable=2
TOR sources are available

**Pull request merged**
