### PR TITLE
check for /boot/firmware dir during build

### PR DESCRIPTION
**Pull request by openoms**

### CODE REVIEW

**Comment by openoms** [comment]
From the build logs:
```
    arm.raspiblitz-arm64-rpi: # Adding Raspiblitz Edits to /boot/config.txt
    arm.raspiblitz-arm64-rpi:
    arm.raspiblitz-arm64-rpi: # Raspiblitz
    arm.raspiblitz-arm64-rpi: kernel=kernel8.img
    arm.raspiblitz-arm64-rpi: max_usb_current=1
    arm.raspiblitz-arm64-rpi: dtparam=nvme
    arm.raspiblitz-arm64-rpi: dtparam=watchdog=on
    arm.raspiblitz-arm64-rpi: dtoverlay=pi3-disable-bt
    arm.raspiblitz-arm64-rpi: dtoverlay=disable-bt
    arm.raspiblitz-arm64-rpi: * skipping tweak_boot_drive
    arm.raspiblitz-arm64-rpi: fsck.mode=force added to /boot/cmdline.txt
    arm.raspiblitz-arm64-rpi: fsck.repair=yes already in /boot/cmdline.txt
    arm.raspiblitz-arm64-rpi: [Login]
    arm.raspiblitz-arm64-rpi: HandlePowerKey=ignore
    arm.raspiblitz-arm64-rpi: nobody ALL=(ALL) NOPASSWD: /home/admin/config.scripts/blitz.shutdown.sh
    arm.raspiblitz-arm64-rpi: KEY_POWER    1    sudo /home/admin/config.scripts/blitz.shutdown.sh
```

let's see if it as applied when flashed on RPi5 and RPi4

**Review by rootzoll — APPROVED** [review]

**Comment by openoms** [comment]
ok it builds correctly now, the file when booting the image on RPi5:
```
cat /boot/firmware/config.txt 
# For more options and information see
# http://rptl.io/configtxt
# Some settings may impact device functionality. See link above for details

# Uncomment some or all of these to enable the optional hardware interfaces
#dtparam=i2c_arm=on
#dtparam=i2s=on
#dtparam=spi=on

# Enable audio (loads snd_bcm2835)
# dtparam=audio=on

# Additional overlays and parameters are documented
# /boot/firmware/overlays/README

# Automatically load overlays for detected cameras
camera_auto_detect=1

# Automatically load overlays for detected DSI displays
display_auto_detect=1

# Automatically load initramfs files, if found
auto_initramfs=1

# Enable DRM VC4 V3D driver

max_framebuffers=2

# Don't have the firmware create an initial video= setting in cmdline.txt.
# Use the kernel's default instead.
disable_fw_kms_setup=1

# Run in 64-bit mode
arm_64bit=1

# Disable compensation for displays with overscan
disable_overscan=1

# Run as fast as firmware / board allows
arm_boost=1

[cm4]
# Enable host mode on the 2711 built-in XHCI USB controller.
# This line should be removed if the legacy DWC2 controller is required
# (e.g. for USB device mode) or if USB support is not required.
otg_mode=1

[all]


# Raspiblitz
kernel=kernel8.img
max_usb_current=1
dtparam=nvme
dtparam=watchdog=on


dtoverlay=waveshare35a:rotate=90
```
```
₿ getconf PAGE_SIZE
4096
```

**Comment by openoms** [comment]
cherry picked to v1.11

**Comment by rootzoll** [comment]
@openoms there are more places where the config.txt is edited .. I will use this PR as a starting point and go thru them all in the `fix-moved-config` branch

**Pull request merged**
