### PR TITLE
Various spelling, grammar, capitalisation fixes

### PR DESCRIPTION
**Pull request by Enegnei**
I went throughout the readme to make various spelling, grammar, capitalisation fixes, and rephrased some things that were a little confusing to read. Keep whatever changes you like. :)

### CODE REVIEW

**Comment by CoderBoogs** [comment]
Join market info instructions

For beginners the instructions are a little confusing:

Start to use logging in to the 'joinmarket' user with: sudo su joinmarket 

I suggest the following 

Start using Joinmarket by logging into the 'joinmarket' user with command: sudo su joinmarket. Enter this into the command line in the console/terminal (item x on the main menu)

**Comment by rootzoll** [comment]
@CoderBoogs More JoinMarket Starter Instructions will be added with this video soon: https://www.youtube.com/watch?v=uGHRjilMhwY

**Comment by rootzoll** [comment]
Hi. @Enegnei thanks for your corrections of the README ... its a lot of changes and some conflict with latest changes on the v1.6 branch. WIll take some to check that thru.

**Comment by frennkie** [comment]
Merge most changes (there were three different PRs for some of these fixes). 
Please let us know if you find any thing else.

**Pull request closed without merging**
