### PR TITLE
feature: fee report on info screen

### PR DESCRIPTION
**Pull request by benthecarman**
Preview of changes, format is Daily - Weekly - Monthly

feereport

### CODE REVIEW

**Comment by rootzoll** [comment]
Thanks. Will take a look after the v1.2 release :)

**Comment by frennkie** [comment]
@benthecarman does this still fit on the LCD screen (even with RTL enabled)?

**Comment by benthecarman** [comment]
> @benthecarman does this still fit on the LCD screen (even with RTL enabled)?

When I tested it when I made it, it did. However, I don't have my node available anymore so I am unsure now, it's probably better to test it again.

**Comment by openoms** [comment]
I have tested this and found really useful for my headless setup already.

For the LCD it needs only one empty line removed  below the LN channel info to keep everything on the screen even with the electrs syncing message

**Comment by openoms** [comment]
As in the PR the top row gets cut when the Electrs message appears:
f2338dac-6a19-48d0-a1fd-a61ebb11f36f

ab69593a-1dd4-40bd-9ac8-9871831077b7

Fits all when the ampty line below the LN info removed:
052a0297-d1e4-497b-8459-9419caae9eff

The actual fee count function is working well on another node.
Capture

**Comment by openoms** [comment]
Edited to fit the screen. Would like to see this!

**Pull request merged**
