### PR TITLE
(lnd): update lnd to 0.16.4

### LINKED ISSUE #3897: Update to LND v0.16.4 - fixes performance issues
https://www.nobsbitcoin.com/lnd-v0-16-3-beta-released/

### PR DESCRIPTION
**Pull request by cstenglein**
fixes #3897

Install on my Test Blitz worked without issues.

### CODE REVIEW

**Comment by openoms** [comment]
`utACK`
will update soon and report

**Comment by cstenglein** [comment]
Maybe we should wait for that update, looks like there is a memory leak present in it:
https://github.com/lightningnetwork/lnd/pull/7767

**Comment by rootzoll** [comment]
This update should be team discussed

**Comment by openoms** [comment]
I am holding off waiting for this fix:
https://github.com/lightningnetwork/lnd/pull/7767

See:
https://twitter.com/nitesh_btc/status/1669731402110193666

**Comment by cstenglein** [comment]
@rootzoll @openoms updated the PR to 0.16.4-beta

**Review by rootzoll — APPROVED** [review]

**Pull request merged**
