### PR TITLE
Add installation instructions for QEMU with UTM

### PR DESCRIPTION
**Pull request by deverickapollo**

### CODE REVIEW

**Comment by rootzoll** [comment]
Cool tutorial might use that myself - do you see it ready to be part of v1.8.0 or is it still in the works?

**Comment by deverickapollo** [comment]
It should be good to go.  I've been using it for development over the past week.  I'll do another fresh install before we lock down v1.8.

**Comment by rootzoll** [comment]
With adding a GitHub Workflow - this PR gets a bit more complex to decide on.
@hashes4merkle can you outline a bit more what Github Workflows you want to introduce here?

@openoms can you join the discussion on GitHub workflows?
https://docs.github.com/en/actions/using-workflows/about-workflows

**Comment by deverickapollo** [comment]
I'll need to remove those commits.  I am testing a CI/CD pipeline integration on the dev branch and the changes merged with this PR. 

 I'll be happy to continue the discussion on the CI/CD pipeline on a separate issue - Perhaps, #2842.

**Comment by deverickapollo** [comment]
Conflicts removed

**Comment by rootzoll** [comment]
Yeah CI/CD pipeline is interesting - please share your experiences. Its just nothing to rush.

**Pull request merged**
