### PR TITLE
Torrent deprecation

### PR DESCRIPTION
**Pull request by vmavromatis**
https://github.com/rootzoll/raspiblitz/issues/1169

### CODE REVIEW

**Comment by bitsam** [comment]
Can you please leave the torrent option in 1.6 release. I still run an rpi 3B, and when I tried 1.6 rc3 the blockchain got corrupted.

**Comment by rootzoll** [comment]
Exactly for those cases its better to have a copy of the blockchain on your laptop ... it will repair much faster than torrent with "COPY OVER LAN" option.

**Comment by bitsam** [comment]
Ok, I am downloading to my laptop now, looks like it will download in about 10 hours.

**Comment by rootzoll** [comment]
The problem with the torrent: It got very slow over the last month (no constant good seeded and some clients had problems with trackers), its hard to maintain (needs to be updated constantly, eats into support/dev time) and it went also often wrong (data corruptions during download, etc) and people had to begin over and over again ... and its a not self-validated blockchain anyway.

So for a RaspberryPi 3 ... its really much more ressilient to download and self-validate the blockchain thru bitcoin-core on your laptop (keep that as a backup there just in case) and the use the "COPY OVER LAN" option.

"COPY over LAN" will take between 4 and 6 hours once you have the Blockchain on your Laptop.

**Pull request merged**
