### PR TITLE
Download Bitcoin whitepaper from the blockchain (service and command)

### PR DESCRIPTION
**Pull request by raulcano**
After my unsuccessful attempts here https://github.com/rootzoll/raspiblitz/pull/2017 and here https://github.com/rootzoll/raspiblitz/pull/2078 to rebase my original pull request (PR 2017), I have opened this one based on a new fork.
This one seems that captures only the intended commit and no other weird stuff.

For info about what it does , see the description in the PR #2017

### CODE REVIEW

**Comment by rootzoll** [comment]
much thanks ... this looks good :) will be part of v1.7RC1 release.

**Comment by raulcano** [comment]
cool, thanks  a lot!

**Comment by nyxnor** [comment]
@raulcano Can you make the pdf viewable through the terminal? I tried but did not accomplish this.

**Comment by raulcano** [comment]
> 
> 
> @raulcano Can you make the pdf viewable through the terminal? I tried but did not accomplish this.

Hmm, I haven´t tried that. 
Probably there are some tools for that but at the moment it just downloads the file to your raspiblitz, so you can copy & view in your remote computer.
If you know a way to view a pdf via terminal let me know and I´ll try to include that in the code.

**Comment by nyxnor** [comment]
I did SCP to confirm that yesterday, all good, just trying to make the pdf viewable on terminal but no solution yet worked for me,

**Comment by vv01f** [comment]
@raulcano
basically there is two options …
1. simple text: e.g. `pdftotext ${pdf} -` will show the content as Text. An alternative is `poppler-utils` or `mc`. 
2. graphical on the framebuffer with e.g. `fbgs` for a very basic result or nicer is [green](https://github.com/schandinat/green)

have fun.

**Comment by nyxnor** [comment]
Thanks @vv01f, did with `pdftotext` :100: . I think this is the best we can get through ssh, as we cant view images through ssh, so fbgs or green wont work, as Blitz dont use a graphical enviroment (just for the lcd screen). 

@raulcano Maybe do this mod to add a copy of the whitepaper in .txt with `pdftotext`, so there will be 2 files, .pdf and .txt, and remember to exclude them.
Also, when I run through the terminal, not from the menu, I end up in the config.scripts folder, remember to go back to home folder.

**Pull request merged**
