### PR TITLE
specter update to 2.0.4

### PR DESCRIPTION
**Pull request by openoms**
Adding specter desktop 2.0.0 which needs python 3.10. As it is not available for Debian currently it is installed from the deadsnakes repo and not made default.

- [x] tested the update so far
- [x] need to test the new install

The install runs ok, but needs 
- [x] https://github.com/cryptoadvance/specter-desktop/issues/2393
- [x] https://github.com/cryptoadvance/specter-desktop/pull/2399
to be fixed.

### CODE REVIEW

**Comment by rootzoll** [comment]
On testing I found two problems:

1) specter systemd service was not "started" after install while status of raspiblitz was `state="ready"` 

2) after systemd starting manually and calling server in browser after entering password B I got:
Bildschirm­foto 2023-03-20 um 16 06 14

**Comment by rootzoll** [comment]
@openoms should I merge for rc3?

**Comment by openoms** [comment]
This python 3.10 requirement needs more testing. Not working out of the box on the RPi either.

**Comment by rootzoll** [comment]
If possible I would like to get the rc3 out by tomorrow - should I wat for this PR to include?

**Comment by openoms** [comment]
This PR has details about the config changes: https://github.com/cryptoadvance/specter-desktop/pull/2072

**Comment by rootzoll** [comment]
I get this error when I try to run the script on a v1.9.0rc2 base:
Bildschirm­foto 2023-04-04 um 02 00 26

**Comment by openoms** [comment]
The latest state building on Raspiblitz v1.9.0 rc4 with the specter release v2.0.2-pre2:
```
May 07 08:40:02 raspberrypi python3[592060]: [2023-05-07 08:40:02,676] INFO in server: Initializing Specter with data-folder /home/specter/.specter
May 07 08:40:02 raspberrypi python3[592060]: [2023-05-07 08:40:02,677] INFO in service_manager: ----> starting service discovery Static
May 07 08:40:02 raspberrypi python3[592060]: [2023-05-07 08:40:02,695] INFO in reflection:   Found class SwanService
May 07 08:40:02 raspberrypi python3[592060]: [2023-05-07 08:40:02,714] INFO in reflection:   Found class LiquidissuerService
May 07 08:40:02 raspberrypi python3[592060]: [2023-05-07 08:40:02,723] INFO in reflection:   Found class DevhelpService
May 07 08:40:03 raspberrypi python3[592060]: [2023-05-07 08:40:03,082] INFO in reflection:   Found class NotificationsService
May 07 08:40:03 raspberrypi python3[592060]: [2023-05-07 08:40:03,096] INFO in reflection:   Found class ExfundService
May 07 08:40:03 raspberrypi python3[592060]: [2023-05-07 08:40:03,099] INFO in reflection:   Found class FaucetService
May 07 08:40:03 raspberrypi python3[592060]: [2023-05-07 08:40:03,103] INFO in reflection:   Found class ElectrumService
May 07 08:40:04 raspberrypi python3[592060]: Traceback (most recent call last):
May 07 08:40:04 raspberrypi python3[592060]:   File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
May 07 08:40:04 raspberrypi python3[592060]:     return _run_code(code, main_globals, None,
May 07 08:40:04 raspberrypi python3[592060]:   File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
May 07 08:40:04 raspberrypi python3[592060]:     exec(code, run_globals)
May 07 08:40:04 raspberrypi python3[592060]:   File "/home/specter/.env/lib/python3.10/site-packages/cryptoadvance/specter/__main__.py", line 7, in <module>
May 07 08:40:04 raspberrypi python3[592060]:     entry_point()
May 07 08:40:04 raspberrypi python3[592060]:   File "/home/specter/.env/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
May 07 08:40:04 raspberrypi python3[592060]:     return self.main(*args, **kwargs)
May 07 08:40:04 raspberrypi python3[592060]:   File "/home/specter/.env/lib/python3.10/site-packages/click/core.py", line 1055, in main
May 07 08:40:04 raspberrypi python3[592060]:     rv = self.invoke(ctx)
May 07 08:40:04 raspberrypi python3[592060]:   File "/home/specter/.env/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
May 07 08:40:04 raspberrypi python3[592060]:     return _process_result(sub_ctx.command.invoke(sub_ctx))
May 07 08:40:04 raspberrypi python3[592060]:   File "/home/specter/.env/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
May 07 08:40:04 raspberrypi python3[592060]:     return ctx.invoke(self.callback, **ctx.params)
May 07 08:40:04 raspberrypi python3[592060]:   File "/home/specter/.env/lib/python3.10/site-packages/click/core.py", line 760, in invoke
May 07 08:40:04 raspberrypi python3[592060]:     return __callback(*args, **kwargs)
May 07 08:40:04 raspberrypi python3[592060]:   File "/home/specter/.env/lib/python3.10/site-packages/cryptoadvance/specter/cli/cli_server.py", line 151, in server
May 07 08:40:04 raspberrypi python3[592060]:     init_app(app, hwibridge=hwibridge)
May 07 08:40:04 raspberrypi python3[592060]:   File "/home/specter/.env/lib/python3.10/site-packages/cryptoadvance/specter/server.py", line 166, in init_app
May 07 08:40:04 raspberrypi python3[592060]:     specter.service_manager = ExtensionManager(
May 07 08:40:04 raspberrypi python3[592060]:   File "/home/specter/.env/lib/python3.10/site-packages/cryptoadvance/specter/managers/service_manager/service_manager.py", line 56, in __init__
May 07 08:40:04 raspberrypi python3[592060]:     class_list = get_classlist_of_type_clazz_from_modulelist(
May 07 08:40:04 raspberrypi python3[592060]:   File "/home/specter/.env/lib/python3.10/site-packages/cryptoadvance/specter/util/reflection.py", line 94, in get_classlist_of_type_clazz_from_modulelist
May 07 08:40:04 raspberrypi python3[592060]:     module = import_module(fq_module_name)
May 07 08:40:04 raspberrypi python3[592060]:   File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
May 07 08:40:04 raspberrypi python3[592060]:     return _bootstrap._gcd_import(name[level:], package, level)
May 07 08:40:04 raspberrypi python3[592060]:   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
May 07 08:40:04 raspberrypi python3[592060]:   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
May 07 08:40:04 raspberrypi python3[592060]:   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
May 07 08:40:04 raspberrypi python3[592060]:   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
May 07 08:40:04 raspberrypi python3[592060]:   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
May 07 08:40:04 raspberrypi python3[592060]:   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
May 07 08:40:04 raspberrypi python3[592060]:   File "/home/specter/.env/lib/python3.10/site-packages/cryptoadvance/specterext/spectrum/service.py", line 15, in <module>
May 07 08:40:04 raspberrypi python3[592060]:     from cryptoadvance.specterext.spectrum.spectrum_node import SpectrumNode
May 07 08:40:04 raspberrypi python3[592060]:   File "/home/specter/.env/lib/python3.10/site-packages/cryptoadvance/specterext/spectrum/spectrum_node.py", line 4, in <module>
May 07 08:40:04 raspberrypi python3[592060]:     from cryptoadvance.specterext.spectrum.bridge_rpc import BridgeRPC
May 07 08:40:04 raspberrypi python3[592060]:   File "/home/specter/.env/lib/python3.10/site-packages/cryptoadvance/specterext/spectrum/bridge_rpc.py", line 15, in <module>
May 07 08:40:04 raspberrypi python3[592060]:     from cryptoadvance.spectrum.spectrum import RPCError as SpectrumRpcError
May 07 08:40:04 raspberrypi python3[592060]:   File "/home/specter/.env/lib/python3.10/site-packages/cryptoadvance/spectrum/spectrum.py", line 26, in <module>
May 07 08:40:04 raspberrypi python3[592060]:     from .db import UTXO, Descriptor, Script, Tx, TxCategory, Wallet, db
May 07 08:40:04 raspberrypi python3[592060]:   File "/home/specter/.env/lib/python3.10/site-packages/cryptoadvance/spectrum/db.py", line 7, in <module>
May 07 08:40:04 raspberrypi python3[592060]:     from flask_sqlalchemy import SQLAlchemy
May 07 08:40:04 raspberrypi python3[592060]:   File "/home/specter/.env/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 5, in <module>
May 07 08:40:04 raspberrypi python3[592060]:     from .extension import SQLAlchemy
May 07 08:40:04 raspberrypi python3[592060]:   File "/home/specter/.env/lib/python3.10/site-packages/flask_sqlalchemy/extension.py", line 23, in <module>
May 07 08:40:04 raspberrypi python3[592060]:     from .session import _app_ctx_id
May 07 08:40:04 raspberrypi python3[592060]:   File "/home/specter/.env/lib/python3.10/site-packages/flask_sqlalchemy/session.py", line 8, in <module>
May 07 08:40:04 raspberrypi python3[592060]:     from flask.globals import app_ctx
May 07 08:40:04 raspberrypi python3[592060]: ImportError: cannot import name 'app_ctx' from 'flask.globals' (/home/specter/.env/lib/python3.10/site-packages/flask/globals.py)
May 07 08:40:06 raspberrypi systemd[1]: specter.service: Main process exited, code=exited, status=1/FAILURE
```

**Comment by openoms** [comment]
Rebased. Now with the RPi base image on Debian12 only minimal chnages are needed overall.

**Comment by openoms** [comment]
The install runs ok, but needs 
- [ ] https://github.com/cryptoadvance/specter-desktop/issues/2393
- [x] https://github.com/cryptoadvance/specter-desktop/pull/2399
to be fixed.

**Comment by openoms** [comment]
The dependencies causing the install error are updated, but since we are installing Specter with pip will need a new release to include the fix.

**Comment by rootzoll** [comment]
@openoms what is the latest status here? Do we still target this v1.11.1?

**Comment by openoms** [comment]
There was still no release of Specter, we might need to look into deprecating it if there is  no continued maintenance.

**Comment by openoms** [comment]
New Specter releases are out so due to test.

**Comment by openoms** [comment]
Updated successfully on RPi5 and amd64, old data was preserved.

**Review by rootzoll — APPROVED** [review]
tACK

**Comment by rootzoll** [comment]
Maybe in the future we can already perconfigure the local Bitcoin Core with a fresh Specter install - see #4593

Buit this looks good for v1.11.1 release

**Pull request merged**
