### PR TITLE
Blitzapi: Install with venv and user

### PR DESCRIPTION
**Pull request by ChuckNorrison**
This should respect the python environment much better and maybe fix the current python environment mismatch.

### CODE REVIEW

**Comment by rootzoll** [comment]
Thx - I will merge into `sdcard-fix` branch & make an sdcard build test.

**Comment by rootzoll** [comment]
OK that looked good - build ran thru - will merge 'sdcard-fix' branch into dev.

**Comment by rootzoll** [comment]
Ah celebrated too early .. Blitz-Api is now not starting (constant re-start) up when testing the build image:
```
Nov 21 18:12:21 raspberrypi python[10818]: /usr/bin/python: No module named uvicorn
Nov 21 18:12:21 raspberrypi systemd[1]: blitzapi.service: Main process exited, code=exited, status=1/FAILURE
Nov 21 18:12:21 raspberrypi systemd[1]: blitzapi.service: Failed with result 'exit-code'.
Nov 21 18:13:21 raspberrypi systemd[1]: blitzapi.service: Scheduled restart job, restart counter is at 2.
Nov 21 18:13:21 raspberrypi systemd[1]: Stopped BlitzBackendAPI.
Nov 21 18:13:21 raspberrypi systemd[1]: Starting BlitzBackendAPI...
Nov 21 18:13:21 raspberrypi blitz.web.api.sh[20361]: # Update Web API CONFIG (Mon 21 Nov 18:13:21 GMT 2022)
Nov 21 18:13:21 raspberrypi blitz.web.api.sh[20361]: # use existing secret
Nov 21 18:13:21 raspberrypi blitz.web.api.sh[20361]: # CONFIG Web API ... still in setup, skip bitcoin & lightning
Nov 21 18:13:21 raspberrypi blitz.web.api.sh[20361]: # '.env' config updates - blitzapi maybe needs to be restarted
Nov 21 18:13:21 raspberrypi systemd[1]: Started BlitzBackendAPI.
Nov 21 18:13:21 raspberrypi python[20383]: /usr/bin/python: No module named uvicorn
Nov 21 18:13:21 raspberrypi systemd[1]: blitzapi.service: Main process exited, code=exited, status=1/FAILURE
Nov 21 18:13:21 raspberrypi systemd[1]: blitzapi.service: Failed with result 'exit-code'.
```

I think its now the wrong env we start the service in ... lets see.

**Comment by ChuckNorrison** [comment]
OK we need to create the service file with venv. i will take a look

**Comment by rootzoll** [comment]
I think I found it .. blitzapi starting up now

**Comment by ChuckNorrison** [comment]
ExecStart should be

`ExecStart=/bin/sh -c 'cd /home/blitzapi/blitz_api && ./venv/bin/uvicorn app.main:app --port 11111 --host=0.0.0.0 --root-path /api'`

// ExecStart tested successful

**Comment by rootzoll** [comment]
see https://github.com/rootzoll/raspiblitz/commit/476e628497c51310686e34a7860177868dccfa77 ... will make a re-test of building the sd card image and teststart again. If this then works - will merge `sdcard-fix` to `dev`.

**Comment by rootzoll** [comment]
OK this worked now ... merging into `dev` :)

**Comment by ChuckNorrison** [comment]
> OK this worked now ... merging into `dev` :)

did you see my approach with the ExecStart command? It works for me and was based on lnbits service file.

**Comment by rootzoll** [comment]
systemd service is already setting the working directory with another parameter (no need to have cd in the exec) and to simplify the lnbits call (without an additional shell call) is on my list.

**Pull request merged**
