### PR TITLE
add a C-lightning FAQ page

### PR DESCRIPTION
**Pull request by openoms**
* to be extended with more detailed info about the implementation in RaspiBlitz
* can be linked from the main FAQ.md
* included a manpage-like list of the short script help outputs 

* suggestions, additions and comments are welcome

Link to read until merged:
https://github.com/openoms/raspiblitz/blob/cln-FAQ/FAQ.cl.md

### CODE REVIEW

**Comment by Fonta1n3** [comment]
Any chance of installing an http server plugin so light clients can communicate directly with lightning-cli?

**Comment by openoms** [comment]
@Fonta1n3 it would worth to have a dedicated issue for this. Is that the BlockchainCommons one used to connect Fully Noded to CLN?

**Comment by Fonta1n3** [comment]
> @Fonta1n3 it would worth to have a dedicated issue for this. Is that the BlockchainCommons one used to connect Fully Noded to CLN?

Sure. Its just a hidden service which controls port 8080 for c-lightning. http://rpcuser:rpcpassword@xxx.onion:8080

I can certainly look at adding support for clighting rest but I really much prefer to deal directly with lighting-cli rather then a third party api.

**Comment by rootzoll** [comment]
@openoms is the FAQ ready to merge?

**Comment by openoms** [comment]
It can be merged, but need to be extended a bit more with at least the backups and recovery options on the end.
Will add to if there are new services or important concepts appear. Also reviews and PRs are easier if it is in a main branch.

**Comment by rootzoll** [comment]
Merging so I can add it to the README.

**Pull request merged**
