### PR TITLE
Add new Service LightningTipBot

### PR DESCRIPTION
**Pull request by ChuckNorrison**
A tip bot and Bitcoin Lightning wallet on Telegram based on LNBits

https://github.com/LightningTipBot/LightningTipBot

### CODE REVIEW

**Comment by ChuckNorrison** [comment]
After the Service was installed, the telegram `api_key` and `lnbits_public_url` in config.yaml needs to be updated.

LNBits needs to be configured for LightningTipBot to work:

1. Create a wallet in LNbits (reachable by the bot via lnbits_url).
2. Get the Admin key in the API Info tab of your user (lnbits_admin_key).
3. Enable the User Manager extension.
4. Get the Admin ID of the User Manager (lnbits_admin_id).

Everything is explained:
https://github.com/LightningTipBot/LightningTipBot#configuration

This Feature can be tested :100:

**Comment by rootzoll** [comment]
Nice - I did put it on "testing" status for next release. 

TODO: Add info to CHANGES file

**Comment by rootzoll** [comment]
Also is there a chance to get this PR based on `dev` branch?

**Comment by ChuckNorrison** [comment]
> Also is there a chance to get this PR based on `dev` branch?

tried to rebase branch with dev but seems i messed it up.. i can create a fresh PR on dev

// https://github.com/rootzoll/raspiblitz/pull/3445

**Pull request closed without merging**
