### PR TITLE
cln update to v23.11, dependency cleanup, clnrest

### PR DESCRIPTION
**Pull request by openoms**
- [x] test on amd64
- [x] test on RPi (Debian12)
- [x] check clnrest - compare with c-lightning-REST

### CODE REVIEW

**Comment by rootzoll** [comment]
ah sorry I already made the cln version update before i saw this ... but please do all the testing and the clean ups, mine was just a quick commit.

**Comment by openoms** [comment]
> ah sorry I already made the cln version update before i saw this ... but please do all the testing and the clean ups, mine was just a quick commit.

reverted it as the build was failing: https://github.com/raspiblitz/raspiblitz/discussions/4282#discussioncomment-770707

the signing key needs updating and
there is clnrest to be disabled at least

**Comment by openoms** [comment]
ok clnrest is disabled by default:

>Configuration
If clnrest-port is not specified, the plugin will disable itself.

https://docs.corelightning.org/docs/rest#configuration

but it will be ready to be used.

**Review by rootzoll — APPROVED** [review]

**Comment by rootzoll** [comment]
Tested install ... ran thru good so far, just some **No such file or directory** errors at the end.

```
- OK the installation of Core Lightning vv23.11 is successful
# Make sure bitcoin is in the debian-tor group
# Add plugin-dir: /home/bitcoin/cl-plugins-enabled
# Add plugin-dir: /home/bitcoin/cl-plugins-available
# Store the lightning data in /mnt/hdd/app-data/.lightning
# Symlink to /home/bitcoin/
ls: cannot access '/home/bitcoin/.lightning/config': No such file or directory
# Create /home/bitcoin/.lightning/config
# lightningd configuration for bitcoin mainnet

network=bitcoin
log-file=cl.log
log-level=info
plugin-dir=/home/bitcoin/cl-plugins-enabled

# Tor settings
proxy=127.0.0.1:9050
bind-addr=127.0.0.1:9736
addr=statictor:127.0.0.1:9051/torport=9736
always-use-proxy=true

ls: cannot access '/home/bitcoin/.lightning/bitcoin/hsm_secret': No such file or directory
```

**Comment by openoms** [comment]
Tested all updates again. Ready to be merged.

**Pull request merged**
