### PR TITLE
Bitcoin install script fails during gpg key download

### PR DESCRIPTION
**Pull request by flyerbear**
Adding port 80 to hkp://keyserver.ubuntu.com in `bitcoin.install.sh` allows the script to successfully import the key and continue running.

### CODE REVIEW

**Comment by openoms** [comment]
This problem with pgp trying to use Tor (while it is not set in anywhere obvious) is not solved by this unfortunately.

A simple test on my debian 11 machine:

```
~ ₿ gpg --keyserver hkp://keyserver.ubuntu.com --recv-key "71A3 B167 3540 5025 D447 E8F2 7481 0B01 2346 C9A6"
gpg: key 74810B012346C9A6: 8 duplicate signatures removed
gpg: key 74810B012346C9A6: "Wladimir J. van der Laan <laanwj@protonmail.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
~ ₿ sudo systemctl stop tor
~ ₿ gpg --keyserver hkp://keyserver.ubuntu.com --recv-key "71A3 B167 3540 5025 D447 E8F2 7481 0B01 2346 C9A6"
gpg: WARNING: Tor is not running
gpg: keyserver receive failed: Connection refused
~ ₿ gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-key "71A3 B167 3540 5025 D447 E8F2 7481 0B01 2346 C9A6"
gpg: WARNING: Tor is not running
gpg: keyserver receive failed: Connection refused
```


I think we should use wget to get the key instead.

**Comment by openoms** [comment]
For the simplest workaround to avoid downloading with gpg could use:

```
  # receive signer key
  wget -O pubkey.asc "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x71A3B16735405025D447E8F274810B012346C9A6"
  if ! gpg --import pubkey.asc
  then
    echo "# FAIL # Couldn't import Wladimir J. van der Laan's PGP pubkey"
    rm pubkey.asc
    exit 1
  fi
  rm pubkey.asc
```

**Comment by openoms** [comment]
sorry not meant to close it, but change is requested

**Comment by flyerbear** [comment]
Interesting. Maybe there are two issues happening? The behavior on my current node is slightly different - I haven't seen any tor-related error messages this time around, and starting or stopping tor has no effect for me. But I guess switching to wget could solve both?

It seems like most other keys are downloaded all at once in another part of the script. Why is the bitcoin key handled differently?

**Comment by openoms** [comment]
bitcoin core has multiple signers and is not predictable who will there be still for the next update. For example laanwj has stepped down as a maintainer so it could be that v0.24.0.1 was the last one he signed. 

See the related changes in https://github.com/rootzoll/raspiblitz/pull/3758

**Pull request merged**
