### PR TITLE
Service and command to download Bitcoin whitepaper from the blockchain

### PR DESCRIPTION
**Pull request by raulcano**
The idea of this pull request is to have a service menu item to download the Bitcoin whitepaper from the blockchain into the Raspiblitz easily.

This adds a new item in the "additional services" menu to enable (download whitepaper) or disable (remove whitepaper) the service.

Also, this PR adds the command 'whitepaper' to the command line, which is a shortcut to enabling the service.

The paper is downloaded to:
/home/admin/bitcoin.pdf

The command used for the download is this one:
sudo -u bitcoin bitcoin-cli getblock 00000000000000ecbbff6bafb7efa2f7df05b227d5c73dca8f2635af32a2e949 0 | tail -c+92167 | for ((o=0;o<946;++o)) ; do read -rN420 x ; echo -n ${x::130}${x:132:130}${x:264:130} ; done | xxd -r -p | tail -c+9 | head -c184292 > $DownloadPath/$WhitepaperFilename

image

image

image

### CODE REVIEW

**Comment by rootzoll** [comment]
very sweet :D Will add PR for next release

**Comment by rootzoll** [comment]
Hey @raulcano love to add your PR for the next release .. can you rebase your PR on the `dev` branch?

**Comment by raulcano** [comment]
> 
> 
> Hey @raulcano love to add your PR for the next release .. can you rebase your PR on the `dev` branch?

Sure! I'm new to rebasing, so it's taking a while. 
I pulled the latest version from the repo but still I get 24 conflicts when I run "git rebase". It's weird because I haven't touched any of the files in conflict. If you have any pointers or suggestion, I'd appreciate it. Thanks!

edit: ok , I'm starting to understand this thing. It seems I was doing it reverse (I assumed merge and rebase where equivalent, which is not the case).  I'll let you know when I'm done.

**Comment by rootzoll** [comment]
Rebasing after a while can be tricky ... easiest sometimes is: make a fresh branch of `dev` and copy your changes over manually, close this PR and make fresh PR.

**Comment by raulcano** [comment]
Thanks, I'll see if I manage with the rebase, if not I'll do what you suggest. cheers!

**Comment by raulcano** [comment]
It seems that I managed to rebase the branch. Let me know if there's sth else I need to do from here.

**Comment by rootzoll** [comment]
hmmm ... ich changed the base for this PR to dev and there seems a lot of changes from the v1.6 branch still in it. @raulcano if you can make a fresh PR that uses the dev branch from the beginning that would be best.

**Comment by raulcano** [comment]
Ok, I'll do that and open a new PR. Cheers!

**Comment by raulcano** [comment]
Created a new PR from a fresh dev branch, but I still see many conflicts ... if that's not correct I'll start from a fresh fork altogether.
https://github.com/rootzoll/raspiblitz/pull/2078

**Comment by rootzoll** [comment]
Finally merged thru #2081 .. will be part of v1.7

**Pull request closed without merging**
