### PR TITLE
reduce bitcoind memory usage w  MALLOC_ARENA_MAX=1

### PR DESCRIPTION
**Pull request by openoms**
Source: https://github.com/bitcoin/bitcoin/blob/master/doc/reduce-memory.md#linux-specific

Got 4x memory usage reduction on my server. No obvious change in performance.

### CODE REVIEW

**Comment by openoms** [comment]
To set it on a running blitz paste this to modify the bitcoind.service and restart bitcoind:
```
CHAIN="mainnet"
bitcoinlogpath="/mnt/hdd/bitcoin/debug.log"
prefix=""

echo "
[Unit]
Description=Bitcoin daemon on ${CHAIN}

After=network-online.target
Wants=network-online.target

[Service]
Environment='MALLOC_ARENA_MAX=1'
ExecStart=/usr/local/bin/bitcoind \\
                                  -daemonwait \\
                                  -conf=/mnt/hdd/bitcoin/bitcoin.conf \\
                                  -datadir=/mnt/hdd/bitcoin \\
                                  -debuglogfile=${bitcoinlogpath}

# Make sure the config directory is readable by the service user
PermissionsStartOnly=true
ExecStartPre=/bin/chgrp bitcoin /mnt/hdd/bitcoin

# Process management
####################
Type=forking
Restart=on-failure
TimeoutStartSec=infinity
TimeoutStopSec=600

# Directory creation and permissions
####################################
# Run as bitcoin:bitcoin
User=bitcoin
Group=bitcoin

StandardOutput=null
StandardError=journal

# Hardening measures
####################
# Provide a private /tmp and /var/tmp.
PrivateTmp=true
# Mount /usr, /boot/ and /etc read-only for the process.
ProtectSystem=full
# Deny access to /home, /root and /run/user
ProtectHome=true
# Disallow the process and all of its children to gain
# new privileges through execve().
NoNewPrivileges=true
# Use a new /dev namespace only populated with API pseudo devices
# such as /dev/null, /dev/zero and /dev/random.
PrivateDevices=true
# Deny the creation of writable and executable memory mappings.
MemoryDenyWriteExecute=true

[Install]
WantedBy=multi-user.target
" | sudo tee /etc/systemd/system/${prefix}bitcoind.service

sudo systemctl daemon-reload
# restart
sudo systemctl restart bitcoind
```

**Comment by ghost** [comment]
Failed to restart bitcoind.service: Unit bitcoind.service has a bad unit file setting.
See system logs and 'systemctl status bitcoind.service' for details.

**Comment by openoms** [comment]
> Failed to restart bitcoind.service: Unit bitcoind.service has a bad unit file setting.
See system logs and 'systemctl status bitcoind.service' for details. 

Got the problem `-mainnet` shouldn't be there. It was only an issue in the comment.
Edit with:
`sudo systemctl edit --full bitcoind`
or try the edited paste again.

**Comment by ts8network** [comment]
Good experience with this setting:
https://t.me/raspiblitz/128506
IMG_20230506_165119

**Comment by spcmnks** [comment]
Looking forward to it since my Pi4 4GB after 10 days decreases its ram ~1GB.

**Review by rootzoll — APPROVED** [review]

**Pull request merged**
