### PR TITLE
2669tor/89fe36095adcc8128f314b41b5e6fd22e94febb618464d117931b8cd3bdb80d4

### PR DESCRIPTION
**Pull request by peterzion45**
89fe36095adcc8128f314b41b5e6fd22e94febb618464d117931b8cd3bdb80d4

### CODE REVIEW

**Comment by peterzion45** [comment]
89fe36095adcc8128f314b41b5e6fd22e94febb618464d117931b8cd3bdb80d4

**Comment by openoms** [comment]
Please add a description and rebase against the `dev` branch.

New PR-s are expected to be opened to `dev` (changed already).

**Comment by peterzion45** [comment]
bitcoin/address/bc1qwqdg6squsna38e46795at95yu9atm8azzmyvckulcc7kytlcckxswvvzej

**Comment by openoms** [comment]
closing this for lack of communication

**Comment by peterzion45** [comment]
0a2f6ffff49b1e633b34526597e03da8871c7ff95f87f0c9992e8fa5308c1a33

**Pull request closed without merging**
