### PR TITLE
add LND repair menu

### PR DESCRIPTION
**Pull request by openoms**
discussed in: #2832

### CODE REVIEW

**Comment by openoms** [comment]
WIP
Restoring from the rescue file and seed works so far, but seed + SCB leads to:
```
ERROR in lnd-scb-import --> lnd.backup.sh scb-import returned error on Tue 21 Dec 00:27:04 GMT 2021\nDETAIL --> /home/admin/config.scripts/lnd.backup.sh scb-import /mnt/hdd/temp/upload/channel.backup --> unknown parameter\nDEBUG -->  --> /home/admin/error-lnd-scb-import-1640046424.log
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                               │  
ERROR in lnd-scb-import --> lnd.backup.sh scb-import returned error on Tue 21 Dec 00:27:04 GMT 2021\nDETAIL --> /home/admin/config.scripts/lnd.backup.sh scb-import /mnt/hdd/temp/upload/channel.backup --> unknown parameter\nDEBUG -->            │                                │  
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!─
```

**Comment by openoms** [comment]
Importing SEED+ SCB manually fails with:

```
$ /home/admin/config.scripts/lnd.initwallet.py "scb" "mainnet" "password" "24 words.... " "/mnt/hdd/temp/upload/channel.backup"
# OK SCB file exists
# *** RECOVERING LND WALLET FROM SEED + SCB ***

...

Traceback (most recent call last):
  File "/home/admin/config.scripts/lnd.initwallet.py", line 300, in <module>
    main()
  File "/home/admin/config.scripts/lnd.initwallet.py", line 292, in main
    scb(stub, wallet_password, seed_words, seed_password, file_path_scb)
  File "/home/admin/config.scripts/lnd.initwallet.py", line 120, in scb
    channel_backups=scb_hex_str.encode()
AttributeError: 'bytes' object has no attribute 'encode'
```

**Comment by openoms** [comment]
Quick test (CAREFUL):
```
seedWords="24words . ... "
# upload SCB with:  scp ./channel.backup bitcoin@192.168.x.xxx:/mnt/hdd/temp/upload/

passwordC="password"
staticchannelbackup="/mnt/hdd/temp/upload/channel.backup"

source <(/home/admin/config.scripts/network.aliases.sh getvars lnd mainnet)

echo "Delete wallet"
sudo rm -r /mnt/hdd/lnd

/home/admin/config.scripts/lnd.install.sh on $CHAIN >/dev/null
sudo systemctl start ${netprefix}lnd

# check that lnd started
lndRunning=0
loopcount=0
while [ ${lndRunning} -eq 0 ]
do
  lndRunning=$(systemctl status lnd.service | grep -c running)
  if [ ${lndRunning} -eq 0 ]; then
    date +%s
    echo "LND not ready yet ... waiting another 60 seconds."
    sleep 10
  fi
  loopcount=$(($loopcount +1))
  if [ ${loopcount} -gt 100 ]; then
    echo "lnd-start-fail" "lnd service not getting to running status" "sudo systemctl status lnd.service | grep -c running --> ${lndRunning}"
    exit 8
  fi
done
echo "OK - LND is running"
sleep 10

# Check LND health/fails (to be extended)
tlsExists=$(ls /mnt/hdd/lnd/tls.cert 2>/dev/null | grep -c "tls.cert")
if [ ${tlsExists} -eq 0 ]; then
  echo "lnd-no-tls" "lnd not created TLS cert" "no /mnt/hdd/lnd/tls.cert"
  exit 9
fi
  
# WALLET --> SEED + SCB 
if [ "${seedWords}" != "" ] && [ "${staticchannelbackup}" != "" ]; then
  echo "WALLET --> SEED + SCB "
  if ! pip list | grep grpc; then sudo -H python3 -m pip install grpcio==1.38.1; fi
  source <(/home/admin/config.scripts/lnd.initwallet.py scb mainnet ${passwordC} "${seedWords}" "${staticchannelbackup}")
fi

**Comment by openoms** [comment]
Still comes to:
```
WALLET --> SEED + SCB 
grpcio                   1.38.1
Traceback (most recent call last):
  File "/home/admin/config.scripts/lnd.initwallet.py", line 300, in <module>
    main()
  File "/home/admin/config.scripts/lnd.initwallet.py", line 292, in main
    scb(stub, wallet_password, seed_words, seed_password, file_path_scb)
  File "/home/admin/config.scripts/lnd.initwallet.py", line 120, in scb
    channel_backups=scb_hex_str.encode()
AttributeError: 'bytes' object has no attribute 'encode'
-bash: be0c8a35d55626ad3cb95bc70b0d3b9bb1f9d2e8514cafcc......
...c6: command not found
```

**Comment by openoms** [comment]
@rootzoll could you please have a look here on the SCB encoding error?
seem to be similar to: https://github.com/rootzoll/raspiblitz/issues/2507

**Comment by openoms** [comment]
To help testing and to create a new LND wallet after RESET-LND in v1.7.1:

```
#download
wget -O 99lndRepairMenu.sh https://raw.githubusercontent.com/openoms/raspiblitz/lndRepairMenu/home.admin/99lndRepairMenu.sh

#make executable
chmod +x 99lndRepairMenu.sh

#start the menu (choose RESET to create a new LND wallet)
./99lndRepairMenu.sh
```

**Comment by openoms** [comment]
> Importing SEED+ SCB manually fails with:
> 
> ```
> $ /home/admin/config.scripts/lnd.initwallet.py "scb" "mainnet" "password" "24 words.... " "/mnt/hdd/temp/upload/channel.backup"
> # OK SCB file exists
> # *** RECOVERING LND WALLET FROM SEED + SCB ***
> 
> ...
> 
> Traceback (most recent call last):
>   File "/home/admin/config.scripts/lnd.initwallet.py", line 300, in <module>
>     main()
>   File "/home/admin/config.scripts/lnd.initwallet.py", line 292, in main
>     scb(stub, wallet_password, seed_words, seed_password, file_path_scb)
>   File "/home/admin/config.scripts/lnd.initwallet.py", line 120, in scb
>     channel_backups=scb_hex_str.encode()
> AttributeError: 'bytes' object has no attribute 'encode'
> ```


making a string out of the `channel.backup` gives another error.
```
Traceback (most recent call last):
  File "/home/admin/config.scripts/lnd.initwallet.py", line 302, in <module>
    main()
  File "/home/admin/config.scripts/lnd.initwallet.py", line 294, in main
    scb(stub, wallet_password, seed_words, seed_password, file_path_scb)
  File "/home/admin/config.scripts/lnd.initwallet.py", line 117, in scb
    request = lnrpc.InitWalletRequest(
TypeError: Parameter to MergeFrom() must be instance of same class: expected lnrpc.ChanBackupSnapshot got bytes.
```

Not sure what else should happen with it?

**Comment by openoms** [comment]
it seems that restoring the wallet and the SCB needs to be two separate steps:
first using:
https://api.lightning.community/?python#initwallet
and then:
https://api.lightning.community/?python#restorechannelbackups

**Comment by openoms** [comment]
Manual testing:

```
#download
wget -O 99lndRepairMenu.sh https://raw.githubusercontent.com/openoms/raspiblitz/lndRepairMenu/home.admin/99lndRepairMenu.sh
wget -O config.scripts/lnd.initwallet.py https://raw.githubusercontent.com/openoms/raspiblitz/lndRepairMenu/home.admin/config.scripts/lnd.initwallet.py

#make executable
chmod +x 99lndRepairMenu.sh

#start the menu (choose RESET to create a new LND wallet)
./99lndRepairMenu.sh
```

**Comment by openoms** [comment]
Will need to add 
https://raw.githubusercontent.com/lightningnetwork/lnd/master/lnrpc/lightning.proto

following: 
https://github.com/rootzoll/raspiblitz/blob/v1.7/home.admin/config.scripts/lndlibs/README.md

the big change is that `lightning.proto`took the place of `rpc.proto`

**Comment by openoms** [comment]
the SCB restore is now functional according my initial tests

will now need to make sure the `_provision.setup.sh` is accommodated to the changes in `lnd.initwallet.py`

**Comment by openoms** [comment]
image

**Comment by rootzoll** [comment]
Looks good but needs to be tested with new sd card build - so merging PR to `dev`. For detailed next testing steps see:
https://github.com/rootzoll/raspiblitz/issues/2832#issuecomment-1005092977

**Pull request merged**
