### PR TITLE
Maximum package added

### PR DESCRIPTION
**Pull request by LightRider5**
A maximum package is now included. Also the pimoroni.de links have been removed due to the closing of their German store.

### CODE REVIEW

**Comment by openoms** [comment]
See my suggestions fro the maximal package:
https://github.com/rootzoll/raspiblitz/issues/905

Good move to replace the Crucial SSD to the Sandisk, had only good experience so far with the latter.

The X825 SATA-USB board has many advantages allowing extra non-shim fans, compatible with the ZKDS-metal case and I think CryptoCloaks is working with it too.

**Comment by openoms** [comment]
TBH I am doing my best to get rid of the shim fan recommendation altogether because even with plymouth uninstalled it causes weird problems for people using the LCD.
Literally every debugging conversation I have now starts with :
- are you using a shim-fan? Remove it!

Seen the `sudo shutdown` and `reboot` not working and SD card read I/O errors during the manual SDcard build too.

**Comment by LightRider5** [comment]
I have the `sudo shutdown` issue also all the time.

**Comment by openoms** [comment]
FYI https://github.com/rootzoll/raspiblitz/issues/1006#issuecomment-585778441

The Touchscreenn with power pins is now widely available:
https://www.amazon.de/s?k=touchscreen+fan+raspberry

**Comment by rootzoll** [comment]
@animalmother1988 merged the new universal shopping list with the maximal package into the main README. Closing this PR - please check if the shopping list in the README is the latest version. thx.

**Pull request closed without merging**
