### PR TITLE
feat: add lnproxy server, webui and check payment hashes as a client

### PR DESCRIPTION
**Pull request by openoms**
related: #3636

### CODE REVIEW

**Comment by openoms** [comment]
with IP2Tor coming back will add nginx configs here as well for the lnproxy-webui

**Comment by openoms** [comment]
the webui works over clearnet
The api needs retesting

also will add to the main menu and SERVICES once all working

**Review by rootzoll — APPROVED** [review]
Looks good for RC2 testing

**Comment by rootzoll** [comment]
@openoms status of PR is still DRAFT - feel free to merge if you like to have it as part of RC2

**Comment by openoms** [comment]
ok, as the webui is working it could be good to test. Won't expose in the menu until all works.

**Pull request merged**
