### PR TITLE
lnbits: update branding and installation script

### PR DESCRIPTION
**Pull request by eillarra**
Hi @rootzoll 

The PR includes some changes to the LNbits installations script and other minor stuff:

- All references to LNBits have been changed to LNbits (branding).
- The installation script has been updated:
  - only the `.env` file is updated now (no need to mess around with the Python code)
  - Instead of using the LND API, it uses the LND gRPC now. `LND_GRPC_ENDPOINT`, `LND_GRPC_PORT` and `LND_CERT` need to be checked
  - no development packages are installed with PIpenv (no `--dev` flag)
  - `gunicorn` runs with `gevent`now
  - the code is pulled from the 0.1.0 tag

There is one thing that we might need to leave as it was, for backwards compatibility. I have changed the HDD data folder to `/mnt/hdd/app-data/lnbits` (lowercase), because it seems more appropriate for a folder, but maybe it messes up the few installation already out there, so you might want to keep `LNBits`.

Another thing you might want to change is how the code is pulled. We could also have a "raspiblitz" tag, that moves, or maybe users can choose to install another version during installation... or master. Or maybe have an option to update to a new version? I don't know what the best option is...

Cheers.

### CODE REVIEW

**Comment by rootzoll** [comment]
On a quick check: I would not remommned to rename the directory on the HDD `/mnt/hdd/app-data/lnbits` because this could break the settings on updating your RaspiBlitz from older versions. If you really need to add renaming you would need to rename existing directories. I would recommend just to stay with the old name on the directory.

**Comment by rootzoll** [comment]
I changed the base for the merge from master to v1.5 .. and made the needed confict resolves.

**Comment by rootzoll** [comment]
Also changeing the "LNBits" to "LNbits" in the config will make trouble for prople having LNbits installed on a v1.4.  I can make a quick dirty fix - that will result for those people (might not be many) to have then both values in the config afterwards.

**Comment by rootzoll** [comment]
After install: firefox is not able to open LNbits over https - givng a: "PR_END_OF_FILE_ERROR"
see https://appuals.com/pr-end-of-file-error/

But logs it self from LNbits look good:
```
Apr 23 12:52:32 raspberrypi sh[1240]: Loading .env environment variables…
Apr 23 12:52:33 raspberrypi sh[1240]: [2020-04-23 12:52:33 +0100] [1242] [INFO] Starting gunicorn 20.0.4
Apr 23 12:52:33 raspberrypi sh[1240]: [2020-04-23 12:52:33 +0100] [1242] [INFO] Listening at: http://0.0.0.0:5000 (1242)
Apr 23 12:52:33 raspberrypi sh[1240]: [2020-04-23 12:52:33 +0100] [1242] [INFO] Using worker: gevent
Apr 23 12:52:33 raspberrypi sh[1240]: [2020-04-23 12:52:33 +0100] [1701] [INFO] Booting worker with pid: 1701
```

**Comment by rootzoll** [comment]
Why is LNbits forwarding to https when i call for example `http://192.168.178.94:5000`?

**Comment by rootzoll** [comment]
I think its OK to have it running just on http for now ... provding a https forwarding for apps like LNbits will come with a later version of RaspiBlitz. LNbits is not the olny app needing this.

**Comment by eillarra** [comment]
There is an env var called `LNBITS_FORCE_HTTPS` that is True by default (1). In an ideal world, it should always be True, and just become False if the page is being served via Tor.

But you can already change it to `LNBITS_FORCE_HTTPS=0` and it should work. Only the withdraw extension won't work, because LNURL requires https or Tor.

**Comment by eillarra** [comment]
> Also changeing the "LNBits" to "LNbits" in the config will make trouble for prople having LNbits installed on a v1.4. I can make a quick dirty fix - that will result for those people (might not be many) to have then both values in the config afterwards.

Of course, this can be `LNBits` if changing it is problematic. Only the texts shown to people and docs need to be updated actually, just for branding consistency.

**Comment by rootzoll** [comment]
OK now its starting after the install :)

When I want to create my first "test" wallet I get an 500 error ... here are the logs:

```
*** LAST 20 LNbits LOGS ***
sudo journalctl -u lnbits -b --no-pager -n20
-- Logs begin at Thu 2020-04-23 16:40:19 BST, end at Thu 2020-04-23 22:24:06 BST. --
Apr 23 22:23:56 raspberrypi sh[24502]:     response = self.full_dispatch_request()
Apr 23 22:23:56 raspberrypi sh[24502]:   File "/home/admin/.local/share/virtualenvs/lnbits-ztOIulw8/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
Apr 23 22:23:56 raspberrypi sh[24502]:     rv = self.handle_user_exception(e)
Apr 23 22:23:56 raspberrypi sh[24502]:   File "/home/admin/.local/share/virtualenvs/lnbits-ztOIulw8/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
Apr 23 22:23:56 raspberrypi sh[24502]:     reraise(exc_type, exc_value, tb)
Apr 23 22:23:56 raspberrypi sh[24502]:   File "/home/admin/.local/share/virtualenvs/lnbits-ztOIulw8/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
Apr 23 22:23:56 raspberrypi sh[24502]:     raise value
Apr 23 22:23:56 raspberrypi sh[24502]:   File "/home/admin/.local/share/virtualenvs/lnbits-ztOIulw8/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
Apr 23 22:23:56 raspberrypi sh[24502]:     rv = self.dispatch_request()
Apr 23 22:23:56 raspberrypi sh[24502]:   File "/home/admin/.local/share/virtualenvs/lnbits-ztOIulw8/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
Apr 23 22:23:56 raspberrypi sh[24502]:     return self.view_functions[rule.endpoint](**req.view_args)
Apr 23 22:23:56 raspberrypi sh[24502]:   File "/home/admin/lnbits/lnbits/decorators.py", line 78, in wrapped_view
Apr 23 22:23:56 raspberrypi sh[24502]:     return view(**kwargs)
Apr 23 22:23:56 raspberrypi sh[24502]:   File "/home/admin/lnbits/lnbits/core/views/generic.py", line 61, in wallet
Apr 23 22:23:56 raspberrypi sh[24502]:     user = get_user(create_account().id)
Apr 23 22:23:56 raspberrypi sh[24502]:   File "/home/admin/lnbits/lnbits/core/crud.py", line 17, in create_account
Apr 23 22:23:56 raspberrypi sh[24502]:     db.execute("INSERT INTO accounts (id) VALUES (?)", (user_id,))
Apr 23 22:23:56 raspberrypi sh[24502]:   File "/home/admin/lnbits/lnbits/db.py", line 32, in execute
Apr 23 22:23:56 raspberrypi sh[24502]:     self.cursor.execute(query, values)
Apr 23 22:23:56 raspberrypi sh[24502]: sqlite3.OperationalError: no such table: accounts
```

**Comment by eillarra** [comment]
My fault. I forgot that you need to do `flask migrate` first... sorry :(

Maybe in the same `ExecStart`:

```
ExecStart=/bin/sh -c 'cd /home/admin/lnbits && pipenv run flask migrate && pipenv run gunicorn -b :5000 lnbits:app -k gevent'
```

**Comment by eillarra** [comment]
This needs to be fixed too: L86
https://github.com/eillarra/raspiblitz/blob/ec191d73627a38da2705406be7506b2dcf871523/home.admin/config.scripts/bonus.lnbits.sh#L86

And these lines have to be revised (not sure I took the right values): L123, L124
https://github.com/eillarra/raspiblitz/blob/ec191d73627a38da2705406be7506b2dcf871523/home.admin/config.scripts/bonus.lnbits.sh#L123

**Comment by rootzoll** [comment]
@eillarra will you make a new commit/PR for those things to be fixed?

**Pull request merged**
